### ISSUE TITLE
Extraction of Document Structure ( ToC ), List of Images

### ISSUE THREAD

**Issue by MartinSenne** [asciidoctor/asciidoctor.js#1062]
Hi all,

first, thanks for the great work on AsciiDoc(tor) so far to all, really great!

Context: Browser and asciidoctor.js.

Within the browser, I want to extract information (e.g. document structure, list of figures / images) of a AsciiDoc document given as string, so that I can use this extracted information to render separate (React) components for navigation in the rendered HTML document. Navigation components here are potentially

* Navigation sidebar component (based on table contents)
* Breadcrumb navigation component
* List component with images / figures

Clicking on the respective entries in the components allows a backlink into the HTML-renderer document.

## Example

If the document is something like

```adoc
== Hello
foobar foobar

=== Funny
Some fun not to forget.

=== World
Lorem ipsum ....
```

ideally a JSON like

```json
{
	"title": "Hello",
	"ref": "_hello",
	"children": [{
			"title": "Funny",
			"ref": "_funny",
			"children": []
		},
		{
			"title": "World",
			"ref": "_world",
			"children": []
		}
	]
}
```
is extracted.

## Questions / Comments

* I could parse / alter the rendered HTML ToC, but this sounds somewhat like a very fragile approach. (e.g. collapsible extension (here Java) does something like this https://gitlab.com/puravida-software/asciidoctor-extensions/-/blob/master/asciidoctor-extensions/src/main/java/com/puravida/asciidoctor/collapsable/CollapsablePostProcessor.java and the respective collapse.js in resources folder)
* Using https://asciidoctor-docs.netlify.app/asciidoctor.js/extend/converter/custom-converter/ seems to be the right approach. Can you help with an indication / sketch?
  * In my understanding, this requires setting up a second AsciiDoctor instance with a custom converter (creating the JSON) attached to it. Is this the right approach? Or can it be achieved easier?
* How does the toc generation work internally?. (I was not able to find any docs on that). 
  * And is there code that one can (re)use?

**Comment by Mogztter** [comment]
Hi @MartinSenne,

> I could parse / alter the rendered HTML ToC, but this sounds somewhat like a very fragile approach. (e.g. collapsible extension (here Java) does something like this gitlab.com/puravida-software/asciidoctor-extensions/-/blob/master/asciidoctor-extensions/src/main/java/com/puravida/asciidoctor/collapsable/CollapsablePostProcessor.java and the respective collapse.js in resources folder)

You can use [`asciidoctor.load(input, options)`](http://asciidoctor.github.io/asciidoctor.js/master/#asciidoctorload) it will return a [`Document`](http://asciidoctor.github.io/asciidoctor.js/master/#document). On this `Document`, you can retrieve the sections using `getSections()`.

> Using asciidoctor-docs.netlify.app/asciidoctor.js/extend/converter/custom-converter seems to be the right approach. Can you help with an indication / sketch?

I don't think that you need to use a custom converter. You can retrieve the information from the `Document` object.

> How does the toc generation work internally?. (I was not able to find any docs on that).
And is there code that one can (re)use?

You can take a look at how the built-in HTML 5 converter generates the Table Of Contents from the `Document` object: https://github.com/asciidoctor/asciidoctor/blob/82c5044d1ae5a45a83a8c82d26d5b5b86fcbc179/lib/asciidoctor/converter/html5.rb#L341-L378

> List component with images / figures

If you want to extract images, you will need to set `catalog_assets` to `true` in the options.
See: https://github.com/asciidoctor/asciidoctor.js/blob/ec5ff6d2c399912dcc5abac17ac0002e737d4702/packages/core/spec/node/asciidoctor.spec.js#L684-L698

Feel free to submit a pull request to extend the documentation: [Extract information from a document](https://asciidoctor-docs.netlify.app/asciidoctor.js/processor/extract-api/) (you can click on "Edit this page" on the top right).


Have a nice day 🌞

**Comment by Mogztter** [comment]
If you have additional questions please ask in the community chat at https://asciidoctor.zulipchat.com.
