### ISSUE TITLE
Sprockets tilt  not found

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#108]
Hello, when i build slim-block, I'm getting below output. What can be reason of that?

```
Warning: Command failed: rake aborted!
Sprockets::FileNotFound: couldn't find file 'tilt'
  (in E:/asciidoctor.js/extensions-lab/lib/slim-block/extension.rb)
E:/asciidoctor.js/Rakefile:47:in `block (2 levels) in <top (required)>'
E:/asciidoctor.js/Rakefile:47:in `each'
E:/asciidoctor.js/Rakefile:47:in `block in <top (required)>'
Tasks: TOP => dist
(See full trace by running task with --trace)
 Use --force to continue.
```

Thanks

**Comment by rahmanusta** [comment]
Also, I tried it in Linux, and Im getting the same. Indeed, tilt 1.4.1 is installed.

**Comment by mojavelinux** [comment]
I don't think tilt is going to work in the Asciidoctor.js environment. Or at least, we haven't tested it yet to my knowledge.

**Comment by rahmanusta** [comment]
I get it. Can I say slim-block extension is not available for browser environment? How can I integrate https://github.com/asciidoctor/asciidoctor-reveal.js to browser environment?

Thanks.

**Comment by mojavelinux** [comment]
> How can I integrate https://github.com/asciidoctor/asciidoctor-reveal.js to browser environment?

We're still trying to solve that problem. The solution may be getting tilt / slim to work. The solution may be to rewrite the backend for JavaScript in jade or something. It's an open issue.

**Comment by rahmanusta** [comment]
I get it. I can try to develop an extension for JavaScript for example deckjs or like, with Jade or handlebars.

* I wonder, is there a way to attach dynamically new converter without modifiying factory.rb?,
* I wonder, which converter can I get for base to develop in JS. I tried to port from DocbookConverter. But, first try was failed.

**Comment by rahmanusta** [comment]
I want to say @mojavelinux  , I ported slim to jade and wrote a new converter for reveal slides in JavaScript. I'm working on that.

**Comment by Mogztter** [comment]
@rahmanusta Wow this is awesome news! I'm really looking forward to integrate this Javascript converter into the Chrome extension !

**Comment by rahmanusta** [comment]
Thanks @Mogztter .I will inform the Asciidoctor team for that work progress.

**Comment by mojavelinux** [comment]
Fantastic news @rahmanusta! We are all very excited about this work! Getting Jade working for Asciidoctor.js is going to be huge!

**Comment by rahmanusta** [comment]
Thank you so much @mojavelinux :) This times, I have little workloads :) But, I will finalize this work as soon as possible.

**Comment by mojavelinux** [comment]
I found a port of Slim to JavaScript. See https://github.com/slm-lang/slm

**Comment by rahmanusta** [comment]
Hello @mojavelinux @Mogztter.  We released AsciidocFX 1.3.7-RC1 today. It supports now revealjs and deckjs backends with jade templates.

If you want to try it; Click Workdir Panel, and right click to any folder and follow new > slide menu items.

I rewrote haml and slim templates to jade for this work . And I'm ready to share my knowledge to any asciidoctor related projects.

**Comment by mojavelinux** [comment]
That's great news @rahmanusta! I know that @Mogztter is very interested in the reveal.js converter in Asciidoctor.js for the Chrome and other extensions.

I'd really like to see the jade templates be migrated to a shared repository where all the tools based on Asciidoctor.js can leverage them. Would you be willing to do that? We could publish the templates using bower or something similar so that they can be managed as a dependency.

**Comment by anthonny** [comment]
I'm really interested in the reveal.js converter too 

:clap: @rahmanusta

**Comment by rahmanusta** [comment]
Thank you guys! Yes, I'm willing to do that. I created a repository and added you as admin. For first step, I'm thinking to push a working example with asciidoctor.js slide backends. What do you think, is it OK for you?

**Comment by mojavelinux** [comment]
@rahmanusta I actually think it makes sense if we include it in the same repository as the slim templates. That way, they can be worked on together.

See https://github.com/asciidoctor/asciidoctor-reveal.js

We can just create a folder named templates/jade.

We don't yet have a dedicated repository for the deck.js backend, but we should and we might as well create it now. It should mirror the structure of the reveal.js repository. Then, we'll need to import the haml templates from asciidoctor-backends while preserving the git history for that folder (just like we did with the reveal.js templates).

**Comment by rahmanusta** [comment]
Of course @mojavelinux , I created a pull request for reveal jade templates. After creating deck repository, I will push deck templates also.  https://github.com/asciidoctor/asciidoctor-reveal.js/pull/39

**Comment by rahmanusta** [comment]
I just uploaded a demo https://github.com/asciidocfx/asciidoctor.js-reveal-demo

**Comment by mojavelinux** [comment]
>  I created a pull request for reveal jade templates.

Super! Thanks @rahmanusta!

I'll setup the deck.js repository asap and let you know when it's ready.

**Comment by rahmanusta** [comment]
Thank you @mojavelinux !

**Comment by mojavelinux** [comment]
@rahmanusta The repository is now ready to import the jade templates for deck.js. Send a pull request at your convenience.

https://github.com/asciidoctor/asciidoctor-deck.js

With that done, I think we can close this issue? Agreed, or is there further work to be done?

**Comment by rahmanusta** [comment]
Thank you @mojavelinux . I pulled a request for deckjs jade templates. 

Everything is Ok for me, we can close this issue. Also, I'm ready to help for any work for this jade templates.

**Comment by mojavelinux** [comment]
:+1:
