### ISSUE TITLE
Detect end of Conversion

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#109]
How can I detect the last element or EOF conversion in a custom Converter.

For example is there any method or property to check last element.

node.isEnd() or node.isLast() like

**Comment by Mogztter** [comment]
What is your use case ? Do you want to put something at the end of the document (a footer) ? Or do you want to execute arbitrary code at this precise moment ?

**Comment by rahmanusta** [comment]
I want to execute something at the end of the rendering last element

**Comment by mojavelinux** [comment]
We are missing several convenience methods in the AST that would make this simpler. See https://github.com/asciidoctor/asciidoctor/issues/401. We can consider adding this method.

Until then, you could calculate yourself by traversing the graph to check if the node is the last element in each level of the hierarchy.

You could also register a Postprocessor, which gets invoked immediately after conversion is complete.

**Comment by rahmanusta** [comment]
Thanks @mojavelinux ,

I think this methods help developers to access elements easily.

**Comment by Mogztter** [comment]
We now have a Postprocessor extension in the public API. @rahmanusta can I close this issue ?

**Comment by rahmanusta** [comment]
@Mogztter yes we can close it.
