### ISSUE TITLE
Publish the Node module as an ES6 module (instead of a CommonJS module)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#1106]
Node.js now supports ECMAScript modules and it's now possible to publish Node package as ES6 module: https://nodejs.org/api/esm.html
Currently, the Node package is published as a CommonJS module.

**Comment by mojavelinux** [comment]
@Mogztter Are you aware of the exports keyword in package.json? Apparently, it can be used not only to set up the default import/require script in a portable way, but also to define other aliases that don't necessarily map 1-to-1 with files. See https://nodejs.org/api/packages.html#conditional-exports

For an example, see: https://github.com/nodeca/js-yaml/blob/master/package.json#L29-L35

**Comment by Mogztter** [comment]
Yes, I know that this keyword exists but I've never experimented with it.
Might need to define all (`browser`, `main`, `module`, `type` and `exports`) to make sure that it's working across the board.
