### ISSUE TITLE
Timings#printReport - all parameter should be optional

### ISSUE THREAD

**Issue by bitPogo** [asciidoctor/asciidoctor.js#1113]
Compare the [types](https://github.com/asciidoctor/asciidoctor.js/blob/cb0db00597ae7ecfd65cc717f3e67f8c284d5abe/packages/core/types/index.d.ts#L442) with the [actual code](https://github.com/asciidoctor/asciidoctor.js/blob/cb0db00597ae7ecfd65cc717f3e67f8c284d5abe/packages/core/src/asciidoctor-core-api.js#L3013).

**Comment by Mogztter** [comment]
You're correct :+1:
