### ISSUE TITLE
Inline#create - opts should be object

### ISSUE THREAD

**Issue by bitPogo** [asciidoctor/asciidoctor.js#1116]
See the [type definition](https://github.com/asciidoctor/asciidoctor.js/blob/cb0db00597ae7ecfd65cc717f3e67f8c284d5abe/packages/core/types/index.d.ts#L2251) and compare with the [actual code](https://github.com/asciidoctor/asciidoctor.js/blob/cb0db00597ae7ecfd65cc717f3e67f8c284d5abe/packages/core/src/asciidoctor-core-api.js#L2311).

**Comment by Mogztter** [comment]
I guess that's true!
Could you please make sure that we will still be able to pass a Ruby hash?

```js
Opal.hash2(Object.keys({foo: "foo"}), {foo: "foo"})
```
