### ISSUE TITLE
JSON and any

### ISSUE THREAD

**Issue by bitPogo** [asciidoctor/asciidoctor.js#1119]
Some type definitions speak of `any` and the doc refers to `JSON`. Do those references mean in fact `object`?

See an [example](https://github.com/asciidoctor/asciidoctor.js/blob/cb0db00597ae7ecfd65cc717f3e67f8c284d5abe/packages/core/types/index.d.ts#L1589-L1591)

**Comment by Mogztter** [comment]
In this example yes, `getRefs` returns an "object" :+1:

**Comment by ggrossetie** [comment]
@bitPogo did a lot of improvements. If some type definitions are still inaccurate, please open a new issue.
