### ISSUE TITLE
Wrong return value of AbstractNode#isAttribute

### ISSUE THREAD

**Issue by bitPogo** [asciidoctor/asciidoctor.js#1120]
`isAttribute` of `AbstractNode` is currently type with a return value of `void` but should be boolean. See [here](https://github.com/asciidoctor/asciidoctor.js/blob/cb0db00597ae7ecfd65cc717f3e67f8c284d5abe/packages/core/types/index.d.ts#L2716).
Additionally it might be more expressive if the body of the function changes from:
```javascript
AbstractNode.prototype.isAttribute = function (name, expectedValue, fallbackName) {
  const result = this['$attr?'](name, expectedValue, fallbackName)
  return result === Opal.nil ? false : result
}
```
to:
```javascript
AbstractNode.prototype.isAttribute = function (name, expectedValue, fallbackName) {
  const result = this['$attr?'](name, expectedValue, fallbackName)
  return !(result === Opal.nil)
```

See  also [here](https://github.com/asciidoctor/asciidoctor.js/blob/cb0db00597ae7ecfd65cc717f3e67f8c284d5abe/packages/core/src/asciidoctor-core-api.js#L950-L953).

**Comment by Mogztter** [comment]
Nice catch :beetle: 
Indeed, it should be boolean :sweat_smile: 

> Additionally it might be more expressive if the body of the function changes from:

We are using this idiom in a lot of places so I would prefer to keep it that way.
Also this code will return `true` if `result` is `false` (which is incorrect, it should return `false`)

1. `(false === Opal.nil)` -> `false` 
2. `!false` -> `true`

**Comment by bitPogo** [comment]
Ah I see `const result` is actually a boolean by itself? Because this confuses me alot:
```javascript
result === Opal.nil ? false : result
```
instead of:
```javascript
result === Opal.nil ? false : true
```

**Comment by Mogztter** [comment]
> Ah I see const result is actually a boolean by itself? Because this confuses me alot:

 I thought the Ruby method `AbstractNode#attr?` could return `true`, `false` or `nil` but now that I'm reading the code again I can't see how the result value can be `nil`:

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/abstract_node.rb#L105-L111

So, unless I'm missing something it could be simplified to:

```js
return this['$attr?'](name, expectedValue, fallbackName)
```
