### ISSUE TITLE
toc is not working

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/asciidoctor.js#113]
I've added:

````
:toc:

toc::[]
````

to my files and it is not working with asciidoctor.js but it does work on github and command line asciidoctor.

**Comment by mojavelinux** [comment]
You have to set the position as well:

```
:toc: macro
```

See http://asciidoctor.org/docs/user-manual/#manual-placement

**Comment by nawroth** [comment]
With `1.5.3-preview.4` I have the `toc` attribute working with an empty value, `preamble` or `macro`. And `:toc!:` shuts it off. Time to close this issue?

**Comment by mojavelinux** [comment]
Indeed. If more clarification is needed, feel free to reopen.
