### ISSUE TITLE
generate anchors for simpler use with livereload

### ISSUE THREAD

**Issue by maxandersen** [asciidoctor/asciidoctor.js#114]
when using livereload with asciidoctor.js the page scrolls to the top.

If asciidoctor.js would generate clickable anchors for headers then I could just click the nearest header to where i would like livereload to go to.

**Comment by mojavelinux** [comment]
You can enable section anchors using the following document-level attribute.

```
:sectanchors:
```

You can also make them links:

```
:sectlinks:
```

See http://asciidoctor.org/docs/user-manual/#links

**Comment by maxandersen** [comment]
is there a way to set this to default on ? (i'm not the original author of all these docs ;/ and some are partials/included in others so it would be wrong to have them there )

**Comment by mojavelinux** [comment]
Yes, where ever the Asciidoctor API is called you can pass in these attribute values to set defaults. This is done in many of the tools, including the Atom extension. See https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/master/app/js/renderer.js#L117

You'd need something like this in the value of the attributes option:

```
sectanchors sectlinks
```

**Comment by maxandersen** [comment]
so should I open a feature request on allowing to specify default options (like setanchors etc.) for asciidoctor.js or can we just convert this issue into it ?

**Comment by mojavelinux** [comment]
I think I need to know more about how you are invoking Asciidoctor.js to know where these options belong. Asciidoctor.js itself is just a library, and is compiled directly from Asciidoctor core. It doesn't have any code of its own except for integration / wrapper code to get it to run on different platforms (e.g., npm).

You should be setting the options where Asciidoctor (or Asciidoctor.js is run). In other words, in the application, browser extension or build-tool plugin. Asciidoctor does have some default options, but `sectanchors` isn't one of them atm. I suppose we could consider changing that in asciidoctor/asciidoctor (which is where the issue would need to be filed).

We have been talking about having a personal or project-level options file that gets fed into Asciidoctor when it's run from the cli. See https://github.com/asciidoctor/asciidoctor/issues/566.

**Comment by maxandersen** [comment]
clicking the asciidoc button in firefox ;)

just realize this is probably better reported against https://github.com/asciidoctor/asciidoctor-firefox-addon

**Comment by mojavelinux** [comment]
Aha! Exactly. It should have an options screen with default settings like
the Chrome extension. Probably best to test the Chrome extension to get an
idea of what could be done as it has a lot of options.

**Comment by Mogztter** [comment]
There's also an issue with the Firefox addon and LiveReload. See https://github.com/asciidoctor/asciidoctor-firefox-addon/issues/26

**Comment by maxandersen** [comment]
Chrome is just such a performance killer these days :)
anyways I opened issue on firefox addon to suggest adding similar options for it.

**Comment by maxandersen** [comment]
Since ffox livereload is still open I tried with chrome.

But when I add `:sectanchors: :sectlinks:` in options nothing changes. section's are still just "dead" text.

**Comment by mojavelinux** [comment]
Remove the colons when adding it to the options screen. The colons are only
needed when defining an attribute in the document.

**Comment by maxandersen** [comment]
I think we should close this since its now supported in both chrome and firefox.
