### ISSUE TITLE
Upgrade to Opal 0.8.x

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#115]
Cross compilation is working fine but I get the following error at runtime:

```
TypeError: asciidoctor: FAILED: <stdin>: Failed to parse source, no implicit conversion of NilClass into String
    at OpalClass.$new (opal.js:3361)
    at module_constructor.<anonymous> (opal.js:3037)
    at module_constructor.self.$$proto.$load (asciidoctor.js:13160)
    at updateBody (renderer.js:72)
    at Object.callback (renderer.js:58)
    at safeCallbackApply (VM31121 extensions::sendRequest:21)
    at handleResponse (VM31121 extensions::sendRequest:72)
```

I opened an issue https://github.com/opal/opal/issues/904

**Comment by mojavelinux** [comment]
The real source of the error is showing because of the stacktrace swallowing issue https://github.com/asciidoctor/asciidoctor/issues/1248, which is fixed in the upcoming 1.5.3. You need to comment out the rescue block on line 1361 and 1362 to get insight into what's really going on.

I see from your comments in the Opal issue that you have discovered the root issue.

I tried to compile with 0.8.0.rc1, but everything seems to get wrapped inside of Opal.modules and nothing gets triggered. Either it's really broken or I'm missing some documentation somewhere as to how to use this new structure.

**Comment by mojavelinux** [comment]
I think it's safe to say that we are skipping 0.7.x and going right to 0.8. 0.7.x seems to be a transitional version and not worth using.

**Comment by Mogztter** [comment]
> I think it's safe to say that we are skipping 0.7.x and going right to 0.8.x. 0.7.x seems to be a transitional version and not worth using.

Ok !

> which is fixed in the upcoming 1.5.3

What needs to be done for 1.5.3 ? Do you need help on some tasks ?

**Comment by mojavelinux** [comment]
Apparently we have to now require modules explicitly, so some changes will be necessary in how we load Asciidoctor.js when we switch to Opal 0.8.x.

Details: https://twitter.com/elia/status/607093057201307648

> What needs to be done for 1.5.3 ? Do you need help on some tasks ?

Yes! I'll follow-up on the list.

**Comment by mojavelinux** [comment]
I'd really like to see if we can make this happen soon because we don't want to get stuck on Opal 0.6.x and miss out on critical improvements, such as Ruby 2 features.

**Comment by Mogztter** [comment]
The following is working:
```javascript
var content = "http://asciidoctor.org[*Asciidoctor*] " +
  "running on http://opalrb.org[_Opal_] " +
  "brings AsciiDoc to the browser!";
var options = Opal.hash2(['doctype', 'attributes'], {doctype: 'inline', attributes: ['showtitle']});
Opal.require('asciidoctor');
var html = Opal.Asciidoctor.$convert(content, options);
```

**Comment by mojavelinux** [comment]
That's great news!

This is the part I was missing when I tried it: `Opal.require('asciidoctor');`. Now it all makes sense.

(As a sidenote, remember we don't need to use Opal.hash2 anymore. Opal.hash is all that's necessary).

**Comment by mojavelinux** [comment]
Does the example file work for you?

**Comment by Mogztter** [comment]
> Does the example file work for you?

I didn't try, I just experimented with this file https://github.com/Mogztter/asciidoctor.js/blob/issue-115/spec/share/basic.html

**Comment by Mogztter** [comment]
I've upgraded the example file to Opal 0.8.0.
There were two issues:

1. First, we need to be specific about the file when using `Opal::Environment`, see [Rakefile](https://github.com/Mogztter/asciidoctor.js/blob/issue-115/Rakefile#L71). Without the file extension Opal was cross-compiling the html file... :stuck_out_tongue: 
2. Second, we need to require `asciidoctor` and `asciidoctor_example` because everything is a module! See [asciidoctor_example.html](https://github.com/Mogztter/asciidoctor.js/blob/issue-115/examples/asciidoctor_example.html#L15)

**Comment by Mogztter** [comment]
Opal v0.8.0 is out! https://github.com/opal/opal/tree/v0.8.0

**Comment by mojavelinux** [comment]
Fantastic! I'll do some testing asap!

**Comment by Mogztter** [comment]
I can confirm that the `asciidoctor_example` but not the `userguide_example`.

I get the same error with Opal 0.8.0.rc2 and Opal 0.8.0. Full stacktrace:

```javascript
Uncaught NoMethodError: undefined method `[]=' for #<MatchData " http://asciidoc.org/article-standalone.html[]" 1:" " 2:"http://asciidoc.org/article-standalone.html" 3:"">
(anonymous function) @ opal.js:3607
Opal.defn.TMP_1 @ opal.js:2486
method_missing_stub @ opal.js:722
Opal.defn.$a.$$p.TMP_28 @ asciidoctor-core.js:4078
def.$gsub.TMP_4 @ opal.js:10511
(anonymous function) @ asciidoctor-core.js:4143
(anonymous function) @ asciidoctor-core.js:3539
Opal.defn.$a.$$p.TMP_2 @ asciidoctor-core.js:3543
Opal.yield1 @ opal.js:830
def.$each.TMP_9 @ opal.js:7253
(anonymous function) @ asciidoctor-core.js:3543
(anonymous function) @ asciidoctor-core.js:5853
def.$content.TMP_2 @ asciidoctor-core.js:5866
def.$paragraph @ asciidoctor-core.js:7261
Opal.defn.TMP_1 @ opal.js:2389
def.$convert @ asciidoctor-core.js:6047
def.$convert @ asciidoctor-core.js:5343
def.$content.$a.$$p.TMP_2 @ asciidoctor-core.js:5353
Opal.yield1 @ opal.js:830
def.$collect.TMP_4 @ opal.js:7017
def.$content @ asciidoctor-core.js:5353
(anonymous function) @ asciidoctor-core.js:6758
def.$section @ asciidoctor-core.js:6759
Opal.defn.TMP_1 @ opal.js:2389
def.$convert @ asciidoctor-core.js:6047
def.$convert @ asciidoctor-core.js:5343
def.$content.$a.$$p.TMP_2 @ asciidoctor-core.js:5353
Opal.yield1 @ opal.js:830
def.$collect.TMP_4 @ opal.js:7017
def.$content @ asciidoctor-core.js:5353
(anonymous function) @ asciidoctor-core.js:6756
def.$section @ asciidoctor-core.js:6759
Opal.defn.TMP_1 @ opal.js:2389
def.$convert @ asciidoctor-core.js:6047
def.$convert @ asciidoctor-core.js:5343
def.$content.$a.$$p.TMP_2 @ asciidoctor-core.js:5353
Opal.yield1 @ opal.js:830def.$collect.TMP_4 @ opal.js:7017
def.$content @ asciidoctor-core.js:5353
def.$content.TMP_14 @ asciidoctor-core.js:8888
def.$embedded @ asciidoctor-core.js:6684
Opal.defn.TMP_1 @ opal.js:2389
def.$convert @ asciidoctor-core.js:6047
def.$convert @ asciidoctor-core.js:8853
self.$$proto.$convert @ asciidoctor-core.js:13862
$gvars.global.$addEventListener.$a.$$p.TMP_1 @ userguide_test.js:790
```

**Comment by mojavelinux** [comment]
> we need to be specific about the file when using Opal::Environment, see Rakefile. Without the file extension Opal was cross-compiling the html file... 

That seems like a bug. (I remember something similar happening before). With that said, I have no problem specifying the extension. Better to be more specific than less specific.

> I can confirm that the asciidoctor_example but not the userguide_example.

I'll give it a go, see if I notice something.

**Comment by mojavelinux** [comment]
I traced the error back to the following patch that we apply in the Opal environment.

https://github.com/asciidoctor/asciidoctor/blob/v1.5.2/lib/asciidoctor/substitutors.rb#L755

Firefox sometimes sets the value of a regexp group to empty string instead of null. This breaks subsequent logic. To fix it, we set the value of the group explicitly. However, this isn't a supported method in Ruby. Opal was allowing it, but Opal 0.8.0 is now compliant and thus "fixes" the issue. I sent a pull request with a patch to implement this method. With that change, I'm happy to say that the user guide example now works!

https://github.com/Mogztter/asciidoctor.js/pull/7

**Comment by mojavelinux** [comment]
One question I think we should consider is whether we should auto-require the library when the JavaScript is added to the page (to mimic the behavior of Opal 0.6). I'm not sure what the right answer is in this case. If we decide to keep them separate, we'll need to update the docs to explain that an explicit require statement is now necessary.

**Comment by Mogztter** [comment]
I think we should mimic the behavior of Opal 0.6 and auto-require the library. Having say that we should also provide a way to manually require the library for advanced users.

**Comment by mojavelinux** [comment]
I was thinking that too. Except, if they use other Opal-generated libraries (like their own extensions), the behavior will be different. But I suppose in that case it's okay since it's new code anyway.

We could also consider having a global variable that can be used to disable auto-require in case someone is using it in an Opal application and wants to restore the default behavior.
