### ISSUE TITLE
Asciidoctor Codemirror Question

### ISSUE THREAD

**Issue by jamroks** [asciidoctor/asciidoctor.js#117]
Sorry in advance  if the subject has already been discussed . 

i went confidently to the codemirror website looking for the "asciidoctor mode" , and oh imagine my disappointment  when i realized that there  no implementation.  when i see the tons of not even relavent syntax language that have already a mode in codemirror , it's just ( how to say it ....crazy !)  not to have something for asciidoctor . 

I have to say i'm not a developper so it's easy for me to say even if i occasionally do some python,  groovy and bash automation  as a sysadmin.  what brought me to the codemirror website is that, even if i don't know anything about javascript , i was reviewing the Ghost ( blogging platform ) code to see what will it take to swap out markdown and integrate asccidoctor via asciidoctor.js ,  i was  pretty happy with what i was discovering so far and wass learning javascript and nodejs and emberjs  and typescript at the same time ... but for a newbie like me there too much obstacle now .  Ghost in using codemirror markdown mode for live preview editor in the fontend ... 

So sad right now because even if the asccidoc mode would exist the integration with ghost was going to be hard but now ...man it's just too much at list for me . 

 is there anyone working on this subject  ?  so just i know and stop dreaming about asciidoctorjs in Ghost ? 

Thanks

**Comment by mojavelinux** [comment]
See my response on the discussion list:

http://discuss.asciidoctor.org/ASciidoc-Codemirror-editor-td3507.html

Long story short, there's an AsciiDoc mode for CodeMirror that lives in the Brackets extension repository. See: https://github.com/asciidoctor/brackets-asciidoc-preview/blob/master/mode/asciidoc.js

**Comment by anthonny** [comment]
I use the same mode in HubPress
https://github.com/HubPress/hubpress.io/blob/development/src/hubpress/scripts/utils/codemirror/mode/asciidoc.js

:+1: to break it out into it's own repository

**Irrelevant**
@jamroks  I saw that you use Ghost, if you have some times could you try https://github.com/HubPress/hubpress.io and give me some feedback?

**Comment by mojavelinux** [comment]
> Irrelevant
> @jamroks I saw that you use Ghost, if you have some times could you try https://github.com/HubPress/hubpress.io and give me some feedback?

Not irrelevant at all! That was my very first thought when reading it :)

Just look at how beautiful the posts are! https://jaredmorgs.github.io/2015/07/17/Sometimes-You-Need-To-Pay-It-Forward.html

**Comment by mojavelinux** [comment]
> I use the same mode in HubPress

Then definitely let's promote it! We can also make it available to npm, Bower and all that jazz.

**Comment by jamroks** [comment]
Thank you @mojavelinux for the reply and very helpful answer. 
And yes not irrelevant at all @anthonny, i will actually have a deeper look at hubpress but from what i see, it already look like pur awesomeness !! 
Thank you guys so much. Damnn i love this community . 
Asciidoctor rock !!

+1 for making it available as an npm module . i have open an issue for that in Thomas Kern repo.  

Cheers

**Comment by mojavelinux** [comment]
:+1: 

> Damnn i love this community.

\o/

I'll follow up with comments in the related issue. See https://github.com/asciidoctor/brackets-asciidoc-preview/issues/25.

**Comment by nerk** [comment]
Just noticed this issue. I guess this can be closed now that we've got an external repo.

**Comment by Mogztter** [comment]
@nerk Ok, thanks
