### ISSUE TITLE
Attribute list parsing differs from Asciidoctor behavior

### ISSUE THREAD

**Issue by djencks** [asciidoctor/asciidoctor.js#1178]
The attribute list in:
```
link:https:example.com/foo.html[1=>2 posits the problem of inequality]
```
 is parsed by Ruby Asciidoctor as a named attribute '1' with value '>2 posits the problem of inequality'

It's parsed by asciidoctor.js as a positional attribute.  The html output includes
```
1&#8658;2 posits the problem of inequality
```
so it appears that the two characters `=>` are getting collapsed into one somehow.

**Comment by Mogztter** [comment]
> The html output includes
1&#8658;2 posits the problem of inequality
so it appears that the two characters => are getting collapsed into one somehow.

I get the same output for both Asciidoctor.js 2.2.1 and Asciidoctor 2.0.12.
`=>` is automatically replaced by Asciidoctor:

https://github.com/asciidoctor/asciidoctor/blob/v2.0.12/lib/asciidoctor.rb#L511

I don't remember exactly when `sub_replacements` is called but it seems that `=>` is replaced before the attributes are parsed.

> The attribute list in:
link:https:example.com/foo.html[1=>2 posits the problem of inequality]
is parsed by Ruby Asciidoctor as a named attribute '1' with value '>2 posits the problem of inequality'

I cannot reproduce that.
If you want a named attribute "1" with value ">2 posits the problem of inequality" then you need to use double quotes:

```
link:https:example.com/foo.html[1=">2 posits the problem of inequality"]
```

Escaping `>` should probably work too:

```
link:https:example.com/foo.html[1=\>2 posits the problem of inequality]
```

**Comment by Mogztter** [comment]
ping @djencks :wink:

**Comment by djencks** [comment]
You are completely correct, I was comparing the results of one step in Asciidoctor Ruby with the entire processing chain in Asciidoctor.js. I'd suggest closing as 'user error' :-)

**Comment by Mogztter** [comment]
Alright, no worries 😀
