### ISSUE TITLE
Update "changes to Asciidoctor" section in README

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#12]
The changes to Asciidoctor section in the README should be updated to reflect which accommodations Asciidoctor core makes for the Opal compiler / environment.

This section will be important for ensuring that developers who work on Asciidoctor core understand the constraints for allowing the code to be cross compiled.

**Comment by mojavelinux** [comment]
Should this issue still be open? It's attached to 1.5.2, which has already been released.

**Comment by Mogztter** [comment]
We've updated the "changes to Asciidoctor" section as part of #54. I think we can close this issue and create dedicated issues if we want to write about an advanced topic.

**Comment by mojavelinux** [comment]
:+1:
