### ISSUE TITLE
Setting document attribute after loading document

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#120]
I want to change document lang after if document content has not lang attribute set. I followed this way;

```javascript
var doc = Opal.Asciidoctor.$load(content, Opal.hash2(Object.keys(options), options));

if (doc.$attr('lang')['$nil?']()) {
   var isSet = doc.$set_attribute('lang', defaultLanguage); 
}

var rendered = doc.$render();
```

isSet prints true, but when I examine doc.$attr('lang') it's value is nil. Also, I examined attributes object in firebug, it see that has no lang attribute.

**Comment by mojavelinux** [comment]
This is an open issue in core. https://github.com/asciidoctor/asciidoctor/issues/1255

**Comment by rahmanusta** [comment]
Thanks @mojavelinux. I will follow up that.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
This is basically the same issue as #96. It will be resolved as of 1.5.3.

**Comment by Mogztter** [comment]
@rahmanusta Could you please test with the latest release `1.5.3.preview.2` ?

**Comment by Mogztter** [comment]
I've added a test:

```javascript
var doc = Asciidoctor.$load('= Document Title\n:lang: fr\n\ncontent is in {lang}');
doc.$set_attribute('lang', 'us'); // modify lang 'fr' to 'us'
var html = doc.$convert(); // <div class="paragraph"><p>content is in us</p></div>
```

**Comment by mojavelinux** [comment]
Nice!

**Comment by rahmanusta** [comment]
:+1:

**Comment by rahmanusta** [comment]
@Mogztter How can I set an attribute as nil? or How to unset an attribute?

**Comment by rahmanusta** [comment]
```
doc.attributes.$delete("data-uri");
doc.attribute_overrides.$delete("data-uri");
```

**Comment by Mogztter** [comment]
> doc.attributes.$delete("data-uri");
doc.attribute_overrides.$delete("data-uri");

Is this the answer ?

**Comment by rahmanusta** [comment]
Yes, it works

**Comment by Mogztter** [comment]
Cool :smile:
Would you mind sending a pull to request on this subject to improve the user manual https://github.com/asciidoctor/asciidoctor.js/blob/master/manual.adoc ?
You could add a section to explain how to add, update or remove attributes with a simple use case. What do you think ?

**Comment by rahmanusta** [comment]
Sure, here it is https://github.com/asciidoctor/asciidoctor.js/compare/master...rahmanusta:patch-1

**Comment by Mogztter** [comment]
This is great thanks! Could you open a pull request ? I will gladly merge
it !
Le 19 déc. 2015 3:02 PM, "Rahman Usta" <notifications@github.com> a écrit :

Sure, here it is master...rahmanusta:patch-1
<https://github.com/asciidoctor/asciidoctor.js/compare/master...rahmanusta:patch-1>

—
Reply to this email directly or view it on GitHub
<https://github.com/asciidoctor/asciidoctor.js/issues/120#issuecomment-165986415>
.

**Comment by rahmanusta** [comment]
Thank you @Mogztter , it is honor for me :)
