### ISSUE TITLE
= LEVEL 0 header =  is missing from html output

### ISSUE THREAD

**Issue by mrft** [asciidoctor/asciidoctor.js#122]
```
= LEVEL 0 header =

This should be the document title
```
returns
```
<div class="paragraph">
<p>This should be the document title</p>
</div>
```

but reading [the userguide about titles](http://www.methods.co.nz/asciidoc/userguide.html#X46) I think it is strange that it disappears...

**Comment by Mogztter** [comment]
Hello @mrft, you are rendering an embedded document, in that case you have to add the attribute `showtitle`. You can read more about that here: http://asciidoctor.org/docs/user-manual/#document-title

**Comment by mrft** [comment]
Thanks. My mistake.

**Comment by Mogztter** [comment]
@mrft No worries, you're welcome :smile:
