### ISSUE TITLE
Update TravisCI to use a container

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor.js#123]
TravisCI offers the option to run in a container, supposedly is faster, better, ...
From my experience I've seen that builds start immediately on a PR, other than that I cannot appreciate much differences.

I have used a asciidoctor.js fork as a test ground and confimed it only requires one line as long as you don't need to use `sudo`: https://github.com/abelsromero/asciidoctor.js/blob/master/.travis.yml#L2.

Details here:
http://docs.travis-ci.com/user/migrating-from-legacy/

PS: This may be interesting for more projects, just copy who you consired.

**Comment by mojavelinux** [comment]
Absolutely. We should do this for all the projects because it is indeed way faster.

Here's the config in core for reference: https://github.com/asciidoctor/asciidoctor/blob/master/.travis.yml#L2

It really just came down to adding `sudo: false` and we never looked back.
