### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by KnIfER** [asciidoctor/asciidoctor.js#1257]
Unable to run sample.js
```
const asciidoctor = require('asciidoctor')() // (1)
const content = 'http://asciidoctor.org[*Asciidoctor*] ' +
  'running on https://opalrb.com[_Opal_] ' +
  'brings AsciiDoc to Node.js!'
const html = asciidoctor.convert(content) // (2)
console.log(html) // (3)
```

**Comment by KnIfER** [comment]
Is require.js a necessary dependency?

**Comment by Mogztter** [comment]
In which environment are you running this code? I'm guessing on a browser environment? 
If so, you should include Asciidoctor.js as a `<script>` tag. After that, Asciidoctor.js will be available as a global variable `Asciidoctor`.

See: https://docs.asciidoctor.org/asciidoctor.js/latest/setup/install/#basic-browser-setup

**Comment by KnIfER** [comment]
Yes, just javascript, I  figured it out laterly.  ……

[Here](https://github.com/KnIfER/Extesions/tree/master/MarkdownEngines) is my WIP utilization of this wonderful js in Notepad++!
