### ISSUE TITLE
Use a variable in section title

### ISSUE THREAD

**Issue by wiibaa** [asciidoctor/asciidoctor.js#126]
Hello,
I'm trying to DRY my docby using variables and include and it works great but I bumped into trying to use a variable in a section title.
Am I doing something wrong ? Is it a bug or not achievable for some reason ?

Example Asciidoctor gist: http://gist.asciidoctor.org/?8f9b874594faab2e84ca
I would expect that `{VAR}` in the title is replaced by the variable value as it is done in the paragraph.

**Comment by Mogztter** [comment]
I don't know this syntax `{set:VAR:my variable}` but it's working with the following document:

```
= My VAR is {VAR}
:VAR: my variable

My VAR is `{VAR}`
```
http://gist.asciidoctor.org/?a4511ea8c7d86cd9c3c5

**Comment by wiibaa** [comment]
Thanks for the quick reply, that solves it for my use case.

For info, I used the syntax from http://asciidoctor.org/docs/user-manual/#assigning-document-variables-inline, as it says it should be equivalent to the main one.

So it is up to you to decide if it is a bug or a feature of inline-scoped variable?

**Comment by Mogztter** [comment]
I think inline variables are interpreted/read after the document (and the document title) is loaded. Having said that I don't quite understand the documentation:

> This is important for being able to assign document attributes in places where attribute entry lines are not normally processed, such as in a table cell.

Maybe @mojavelinux can enlighten us :bulb: :book: :smile:

**Comment by wiibaa** [comment]
@Mogztter Using a variable in the document title is not my goal, but I'm impressed that it is possible. 
I was working with Section Titles, and just got suprised that a variable defined with the "main" syntax vs a variable defined "inline" do not behave the same in the section title.
I have updated my gist to highlight my point http://gist.asciidoctor.org/?a4511ea8c7d86cd9c3c5 where

**Comment by mojavelinux** [comment]
In short, `{set:...}` is for edge cases. You shouldn't really be using it except as a last resort. The preferred way to define attributes is using the attribute entry syntax as you showed:

```
:VAR: my variable
```

We really only implemented `{set:...}` in Asciidoctor for compliance reasons. I really don't like it.

> I think inline variables are interpreted/read after the document (and the document title) is loaded.

They are defined at the time attributes are resolved, which is currently during the render phase (except for titles which can happen in the parse phase).

>  just got suprised that a variable defined with the "main" syntax vs a variable defined "inline" do not behave the same in the section title.

Correct, they are just different. That's just how AsciiDoc was defined. Certainly something to consider when we look at the spec for UniDoc. As far as AsciiDoc goes, it's just like that.

**Comment by Mogztter** [comment]
@wiibaa Does that answer your question ?
@mojavelinux Do you think we need to improve the documentation on this specific topic (ie. track an issue in https://github.com/asciidoctor/asciidoctor.org) before closing this issue ?
