### ISSUE TITLE
Adding line-number info to rendered HTML element

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#127]
Hello;

We are following complex path to feature smooth scrolling in AsciidocFX. Is it possible to add line-number info to rendered HTML elements by it's number? Or do you have any idea for the smooth scrolling (scrolling by asciidoc content line position)?

**Comment by mojavelinux** [comment]
The line number info is available at the block level if you add the following option when invoking the processor:

```
sourcemap: true
```

However, you'd still need to modify the converter (or templates) to pull information from the `source_location` field (if available) and add it to the HTML. I have not yet attempted to do something like this, but in theory it should work.

**Comment by rahmanusta** [comment]
I'm thinking to implement a new TreeProcessor for this need. Is it possible iterate all nodes in a document?

**Comment by mojavelinux** [comment]
I'm pretty sure calling `find_by` on the document returns all nodes.

**Comment by rahmanusta** [comment]
Yes, I tried it and +find_by+ with no argument returns all nodes :+1:

**Comment by mojavelinux** [comment]
:+1:
