### ISSUE TITLE
How to invoke sub_replacements method?

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#129]
How can I invoke https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/substitutors.rb#L394 method in Asciidoctor.js ?

**Comment by mojavelinux** [comment]
The quickest way to answer questions like this is to write it in Ruby, cross compile the result with Opal and then see what it output. It may not be exactly what you want, but it should give you the idea.

It will look something like:

```
block.$sub_replacements("...");
```

Assuming you have a reference a block (i.e., node) in the AST.

**Comment by rahmanusta** [comment]
Thanks Dan.  I did it as you said, @mojavelinux what do you think about first implementation in following gif?

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/1158804/10518076/6eb6e442-7368-11e5-8660-186ca4765720.gif)

**Comment by mojavelinux** [comment]
Exactly what I had in mind! Very, very nice!

What I really like about this is that you still get to use the replacement syntax in AsciiDoc as a shorthand (good author experience), but we change _when_ the replacements happen. Instead of waiting until conversion, and only seeing the result in the output, authors get to tap into the functionality of Asciidoctor directly from the editor. This is the stuff a good IDE is made of.

**Comment by rahmanusta** [comment]
Thank you Dan!!

I wonder whether there is any missing concept for applying replacements feature?

Btw, I copied the replacements methods to a Ruby class and compiled it to JS via Opal. If I understand it truely, $sub_replacements is only accessible over block objects. If  we make it directly public, I can call it directly. What do you think about that?

Thanks.

**Comment by mojavelinux** [comment]
You are correct that it's not yet public, though I'm not sure I want it to be public in its current state. What's probably best is to create a separate little utility project that does this that can be used in extensions and other places like IDEs. In other words, we want the behavior, but we don't want to couple to the implementation in core, which could change over time.

**Comment by mojavelinux** [comment]
One thing I learned from working the JavaScript community recently is that no function is too small for a project :)

**Comment by rahmanusta** [comment]
Haha :) It is Ok for me, I will append the replecements code as an addon. Thanks :)
