### ISSUE TITLE
initializeClass helper does not work with methods that accept a block

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#1297]
The way the initializeClass helper registers methods, it does not provide a way to access or yield to the block argument. This, in turn, impacts a custom logger registered using the LoggerManager.newLogger helper. The Logger#add method can accept the message as a block argument. And, indeed, some logger calls in Asciidoctor core pass the message as a block. In these cases, the custom logger can only see an undefined message.

Here's a possible solution to the problem that emulates how Opal handles blocks. In the initializeClass helper, first store a reference to the function passed to Opal.def:

```js
var $function
Opal.def(scope, '$' + functionName, $function = function () {
```

Then, before dispatching to userFunction, detect and append the block as the final argument:

```js
var $block = $function.$$p
if ($block) {
  args[args.length] = function () { return Opal.yield1($block) }
  args.length += 1
  $function.$$p = null
}
```

This assumes the block itself doesn't take any arguments. Ideally, the generated function would account for block arguments. And there may be a better way of doing this altogether. But, at least when registering a custom logger using newLogger, the block argument to Logger#add should be honored.

**Comment by Mogztter** [comment]
> The way the initializeClass helper registers methods, it does not provide a way to access or yield to the block argument. This, in turn, impacts a custom logger registered using the LoggerManager.newLogger helper. 

I will see what I can do.

> The Logger#add method can accept the message as a block argument. And, indeed, some logger calls in Asciidoctor core pass the message as a block. In these cases, the custom logger can only see an undefined message.

@mojavelinux Why do we pass the message as a block argument? What are the benefits?

```rb
logger.info { %(dropping line containing reference to missing attribute: #{key}) }
```

**Comment by Mogztter** [comment]
> Why do we pass the message as a block argument? What are the benefits?

I assume that this is for performance reason? We don't want to perform the string concatenation if the message is not appended (for instance, when the message severity is not high enough)?

**Comment by mojavelinux** [comment]
> Why do we pass the message as a block argument? What are the benefits?

It defers any computation of the message so that it is not performed if the level is not enabled. Obviously, there's not going to be a measurable difference in this case, but I did it this way for consistency. But regardless of what core does, it's a valid usage of the Logger API. So it's possible it's done this way by extensions that use the Asciidoctor logger. So it's probably best to support it.

I do sort of which Opal provided a cleaner API for detecting and invoking the block. It's kind of weird to have to access it off the function name.
