### ISSUE TITLE
Travis CI - Test should fail

### ISSUE THREAD

**Issue by anthonny** [asciidoctor/asciidoctor.js#130]
Test should fail because Opal is undefined but the job pass

![image](https://cloud.githubusercontent.com/assets/2006548/10366016/d4ccfbbe-6dc7-11e5-9904-d5e61578e07c.png)

https://travis-ci.org/asciidoctor/asciidoctor.js/builds/83552848

**Comment by mojavelinux** [comment]
Probably the return value of the build is not making it back to the shell?

**Comment by Mogztter** [comment]
https://github.com/mhevery/jasmine-node/issues/212

**Comment by Mogztter** [comment]
I tried to update `grunt-jasmine-node` to `0.3.1` but this version is trying to load Bower spec files:

```
Exception loading: /home/guillaume/workspace/opensource/asciidoctor.js/spec/bower/bower.spec.js
[ReferenceError: commonSpec is not defined]
Failed to execute "jasmine.executeSpecsInFolder": ReferenceError: commonSpec is not defined
```

The config `all: ['spec/npm']` is somehow ignored.
With this version `ReferenceError` terminates Grunt build with exit code 0...

**Comment by Mogztter** [comment]
I think this issue is now outdated :wink:
