### ISSUE TITLE
Publish version 1.5.3-preview.1 to npmjs

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#131]
@anthonny Could you please publish version [1.5.3-preview.1](https://github.com/asciidoctor/asciidoctor.js/tree/v1.5.3-preview.1) to npmjs ? 

I'm not a maintainer so I can't do it :disappointed: 
https://docs.npmjs.com/cli/owner

**Comment by Mogztter** [comment]
Ref: #128

**Comment by mojavelinux** [comment]
@anthonny Could you add @Mogztter as a maintainer of the package?

**Comment by anthonny** [comment]
@Mogztter why don't we use another version of opal-npm-wrapper (0.7.x or 0.8.0) ?

@mojavelinux  Sure i can, i just need his username on the npm website ;)

**Comment by Mogztter** [comment]
> Sure i can, i just need his username on the npm website ;)

Ops, my username is `ggrossetie`.

> why don't we use another version of opal-npm-wrapper (0.7.x or 0.8.0) ?

We didn't take the time to update to Opal 0.7.0 because there was already a release candidate of Opal 0.8.0.
Version `1.5.3-preview.1` is cut from `opal063` branch. This branch includes all the commits before the migration to Opal 0.8.0. So `1.5.3-preview.1` is a stable version with Asciidoctor 1.5.2 and Opal 0.6.3 (including 143a6867).

**Comment by anthonny** [comment]
> Ops, my username is ggrossetie.

Done ;)

**Comment by Mogztter** [comment]
And done! :tada:

**Comment by mojavelinux** [comment]
:beers:
