### ISSUE TITLE
Move opal_ext from core to Asciidoctor.js

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#132]
Since Asciidoctor.js now has its own build and tests (i.e., its own lifecycle), I think we should move the [opal_ext](https://github.com/asciidoctor/asciidoctor/tree/master/lib/asciidoctor/opal_ext) folder from core to Asciidoctor.js.

This will also allow us to make any changes necessary when Opal is upgraded without waiting on a core release. The only Opal-related code that would remain in core are the internal patches necessary to handle logic that is specific to the Opal environment.

**Comment by Mogztter** [comment]
Yes :+1:

**Comment by mojavelinux** [comment]
Cool. Let's try to get this done for 1.5.3. Would you like me to send the PR to Asciidoctor.js to move the files?

When we move the files, we need to figure out where the require 'asciidoctor/opal_ext' belongs. I think for anything that isn't part of Asciidoctor itself, we should include it from Asciidoctor.js.

That would mean the following two lines get added to opal_ext.rb:

```
require 'encoding'
require 'strscan'
```

Then the Asciidoctor.js build requires 'asciidoctor/opal_ext'.

wdyt?

**Comment by mojavelinux** [comment]
This way, if any stdlib changes happen in Opal, you can now deal with them in Asciidoctor.js.

Of course, the ultimate goal is that all references to Opal can get eliminated from core, but that's a gradual process as Opal matures.

**Comment by mojavelinux** [comment]
I'm really excited about this because it's a big day for Asciidoctor.js to be getting ever closer to building the Asciidoctor gem without any external assistance. After 1.5.3, we can start sifting through core and seeing if we can get rid of any Opal-specific logic (or as much as reasonable).

**Comment by mojavelinux** [comment]
I made the equivalent PR on the core side. I won't merge it until the files are in the Asciidoctor.js repository.

https://github.com/asciidoctor/asciidoctor/pull/1518

**Comment by mojavelinux** [comment]
Removed. Let me know if you run into any trouble.

**Comment by Mogztter** [comment]
I found an issue, we need to `require("asciidoctor/opal_ext");` at [the top of `asciidoctor.rb`](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L8) before [constants are resolved](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor.rb#L172).

If we don't want to modify `asciidoctor.rb`, I can use a regexp to add `require("asciidoctor/opal_ext");` but the problem is there's no "unique code" to search for.

**Comment by mojavelinux** [comment]
I'm totally comfortable with adding the require statement in core. Even if one day we don't need anything in that file, that gives Asciidoctor.js 100% control over what to feed into that require statement. I've gone ahead and added it to core.

**Comment by Mogztter** [comment]
Thanks, that's perfect +1:
I will do some more testing and upgrade the Chrome Extension to the latest version to make sure everything is working fine.

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
I've done some testing of my own and this looks ready to go!

The examples/userguide_test.html seems to require the AsciidoctorConfiguration block that is present in the asciidoctor_example.html file:

```
AsciidoctorConfiguration = { autoLoadModule: false }
```

and

```
Opal.require('asciidoctor');
```

https://github.com/asciidoctor/asciidoctor.js/blob/master/examples/userguide_test.html

**Comment by Mogztter** [comment]
@mojavelinux Hmmm, if `AsciidoctorConfiguration` is undefined then the `asciidoctor` module is automatically loaded. See https://github.com/asciidoctor/asciidoctor.js/blob/master/src/append-require-core.js#L2

Both userguide_test.html and asciidoctor_example.html are working on my machine. Do you see an error in the console with userguide_test.html ?

**Comment by mojavelinux** [comment]
It may have been a temporary glitch in my build. As long as the two html
files in examples are loading Asciidoctor the same way, we're good.

**Comment by mojavelinux** [comment]
:+1:
