### ISSUE TITLE
Registering block extension with Opal v0.8.0

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#134]
Hello;

I'm trying current code base, it works well but I couldn't register a block extension. Is there any code example or path to follow ?

**Comment by rahmanusta** [comment]
I explicitly registered tree-block extension as below;

```
Opal.require('tree-block');
Opal.require('tree-block/extension"');
```

Thanks.

**Comment by Mogztter** [comment]
Yes, you can have a look at the Chrome extension: https://github.com/asciidoctor/asciidoctor-chrome-extension/pull/110/files#diff-9d0e9e361d809a50cf0b6b5f3cef6b13R138

I think we should also automatically require extension when we cross-compile them to stay consistent with: https://github.com/asciidoctor/asciidoctor.js/blob/master/dist/asciidoctor-core.js#L13972
