### ISSUE TITLE
Release a preview version based on Asciidoctor 1.5.3

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#136]
The title says it all!

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
You've accomplished this issue, so I think you can close...unless you want to update the title to "final version".

**Comment by Mogztter** [comment]
True...
I still need to solve some issues but hopefully 1.5.3 final will be out this week or the next week !

**Comment by mojavelinux** [comment]
:+1: 

I would like to try to get that file:// prefix problem resolved. I'm trying my best to get to it.

**Comment by Mogztter** [comment]
> I would like to try to get that file:// prefix problem resolved. 

You refer to https://github.com/asciidoctor/asciidoctor/issues/1561 ?

**Comment by mojavelinux** [comment]
Yep. It's not a blocker for Asciidoctor.js 1.5.3 (unless you want it to be). I'm shooting to get it resolved in 1.5.4. I'm just not sure where the code goes yet (core or Asciidoctor.js). Investigation will reveal.
