### ISSUE TITLE
Custom Template "helpers" only work for first file

### ISSUE THREAD

**Issue by yGuy** [asciidoctor/asciidoctor.js#1361]
Unless you disable template caching, the "helpers.js" file declarations in a templates directory are only available for the first file.
The `helpers` context variable is not available (or rather has a value of `undefined`) for all but the first document that gets converted.

Test case: use the following directory structure:
```
+ templates
    +helpers.js
    +block_image.html.js
test.adoc
test2.adoc
```
with helpers.js like this:
```
module.exports.works="works"
```
and the template `block_image.html.js` like this:
```
module.exports = function({node, opts, helpers}) {
    return helpers.works;
}
````
and the two adoc files both like this:
```
image::test.png[]
```

Then observe that this works:
```
npx asciidoctor --template-dir ./templates test.adoc
```
while this fails:
```
npx asciidoctor --template-dir ./templates test.adoc test2.adoc
```
When disabling the `template_cache` in code, this actually works.
It seems the `self.helpers` is a different `self` for the first run, but for the subsequent "cached runs" `self` does not have a `helpers` value anymore and `undefined` is passed as the value. 
I don't know how (or even whether) to fix this is in Ruby, but the templates feature is really cool, but does not work for me with caching enabled, which when disabled becomes really slow.

**Comment by Mogztter** [comment]
Hi @yGuy and thanks for the detailed report.
It sounds like a bug, I will try to reproduce it (using a unit test) and fix it 👍🏻

**Comment by yGuy** [comment]
Thanks - I just realized that there was a copy paste error in my report - the first (supposed to be working) test failed, too, because it was identical to the failing test :-/
