### ISSUE TITLE
[Question]  Binding click handlers on code blocks?

### ISSUE THREAD

**Issue by luchillo17** [asciidoctor/asciidoctor.js#1364]
Working with React, and trying to render an Asciidoc string that contains code blocks, we want to bind some `onClick` handlers to those blocks so we know when the user clicks on them, then run some actions.

So far it looks like the only 2 ways to do it, with a custom extension that overrides the code block, or outside of Asciidoc targeting the generated HTML to attach the code, the latter is just hacky and prone to breaking if the way the code blocks are rendered in HTML changes, the former doesn't feel like it plays well with React since you attach the extensions to the whole library, can't override the code blocks only in that specific render, and would have to declare a global click handler function and somehow bind it to React so I can inform React when it was clicked.

Is there another way to do this that is more compatible with React?

**Comment by Mogztter** [comment]
Hello @luchillo17,

React does not play nice with raw HTML. Maybe you could encapsulate the raw HTML produced by Asciidoctor.js in your component:

```js
return (<div onClick={this.handleClick}>
  <div dangerouslySetInnerHTML={createMarkup()} />
</div>)
```

> So far it looks like the only 2 ways to do it, with a custom extension that overrides the code block, or outside of Asciidoc targeting the generated HTML to attach the code

You can select a block from an Asciidoctor `Document` and convert it to HTML:


```js
const sourceBlocks = asciidoctorDocument.findBy((block) => block.getNodeName() === 'listing' && block.getStyle() === 'source' && block.getAttribute('language') === 'typescript')
const html = sourceBlocks && sourceBlocks.length > 0 ? sourceBlocks[0].convert() : ''
```

In the future, please ask usage questions in the community chat at https://asciidoctor.zulipchat.com.

**Comment by luchillo17** [comment]
So basically I would have to separately render the blocks so I can wrap only those with the `onClick` handler? that sounds better than my previous assumption, I thought I would have to override the `code` block macro or something to add an event listener to it and bind that to the react function or a global event bus, this solution feels better, though it indeed requires some looping if I want to render everything in order.

**Comment by Mogztter** [comment]
> Basically would be something close to this, right?:

A block can contains blocks so you will need to traverse all nodes/blocks but otherwise you get the idea.
In theory, it might be possible to use a custom converter to return JSX instead of HTML using the same technique (i.e., returning `<div dangerouslySetInnerHTML={content}/>` instead of plain HTML as string)
