### ISSUE TITLE
How to make 'include::' work?

### ISSUE THREAD

**Issue by saneef** [asciidoctor/asciidoctor.js#1369]
I'm using asciidoctor.js to convert some Asciidoc documents. Including code files is a crucial need for the project. This is the script I'm using. _But, the `include::` doesn't seem to be working. The output only has `link::` or `<a>`._

test.js
```js
const asciidoctor = require("asciidoctor")();

const html = asciidoctor.convertFile("./a.adoc", {
	to_file: false,
	standalone: true,
});

console.log(html);
```

a.doc
```asciidoc
= A document

[source,ruby]
----
include::./c.rb[]
----

include::./b.adoc[]
```

b.doc
```asciidoc
= B Document

A line of text.

```

c.rb
```rb
print "hello world";
```

And the output I'm getting:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Asciidoctor 2.0.15">
<title>A document</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic%7CNoto+Serif:400,400italic,700,700italic%7CDroid+Sans+Mono:400,700">
<link rel="stylesheet" href="./asciidoctor.css">
</head>
<body class="article">
<div id="header">
<h1>A document</h1>
</div>
<div id="content">
<div class="listingblock">
<div class="content">
<pre class="highlight"><code class="language-ruby" data-lang="ruby">link:./c.ruby[]</code></pre>
</div>
</div>
<div class="paragraph">
<p><a href="./b.adoc" class="bare">./b.adoc</a></p>
</div>
</div>
<div id="footer">
<div id="footer-text">
Last updated 2021-07-21 17:36:39 +0550
</div>
</div>
</body>
</html>
```

**Comment by saneef** [comment]
Made it working! Figured that `safe: 'unsafe'` should be set in asciidoctor options to make `include::` work.

**Comment by saneef** [comment]
It would be great if the dependency of `include` with `safe` is noted in the [converter options](https://docs.asciidoctor.org/asciidoctor.js/latest/processor/convert-options/) documentation. I figured it out from [CLI options](https://docs.asciidoctor.org/asciidoctor.js/latest/cli/options/).

**Comment by Mogztter** [comment]
That's a good suggestion!
I've created #1372 to improve the documentation.

Please note that you can edit the documentation by clicking on "Edit this page" (on the right):

![image](https://user-images.githubusercontent.com/333276/126750126-ba349764-de48-4455-92d3-6b4157d80b02.png)
