### ISSUE TITLE
Error when trying to convert .adoc file 

### ISSUE THREAD

**Issue by hiren3897** [asciidoctor/asciidoctor.js#1375]
Hello Team,

I am trying to convert `file.adoc` in my directory to display it in my app as an HTML but it gives me the following error you can see in the image below.

![assicError](https://user-images.githubusercontent.com/59652404/126972107-ea63ee98-3226-4c83-921b-f15dda93c848.png)

### My Code
```javascript
import Asciidoctor from 'asciidoctor';
const asciidoctor = Asciidoctor();

const html = asciidoctor.convertFile('file.adoc', { to_file: false, standalone: true });
console.log(html);
```

but it doesn't work it gives an error for `mtime undifined`

Can you please help me to resolve this?

Thank you in advance.

**Comment by Mogztter** [comment]
Hello @hiren3897,

Here's the related issue: https://github.com/asciidoctor/asciidoctor.js/issues/523

**Comment by hiren3897** [comment]
hello @Mogztter 

Do we have any solution yet for this error?

**Comment by Mogztter** [comment]
It depends on what you want to achieve. If you want to create a web application that converts an AsciiDoc document, then you should fetch the content of this document from an URL (for instance, using `XMLHttpRequest` or `fetch`). Then, use `convert`.


>
```js
 const html = asciidoctor.convert('file.adoc', { to_file: false, standalone: true });
console.log(html);

**Comment by hiren3897** [comment]
Thanks, it worked for me! :tada:
