### ISSUE TITLE
Webpack loader for asciidoc?

### ISSUE THREAD

**Issue by hiren3897** [asciidoctor/asciidoctor.js#1376]
Is there any webpack loader available for loading .adoc files while building the project? 

OR any plugin that can be used to load the asciidoc?

**Comment by Mogztter** [comment]
Not a Webpack expert but I suppose you can use https://v4.webpack.js.org/loaders/raw-loader/ (or similar) if you want to read the file at build time.

**Comment by Mogztter** [comment]
You can also take a look at: https://github.com/hypery2k/webpack-asciidoctor-plugin (does not seem to be maintained but you can probably borrow some ideas).

Please ask integration questions in the community chat at https://asciidoctor.zulipchat.com. The issue tracker should be reserved for reporting bugs and tracking features we've decided to implemented.

**Comment by hiren3897** [comment]
> Not a Webpack expert but I suppose you can use https://v4.webpack.js.org/loaders/raw-loader/ (or similar) if you want to read the file at build time.

Thank you so much, this worked for loading asciidoc files in the project.
