### ISSUE TITLE
Build is failing on AppVeyor with Asciidoctor 1.5.3 and Nashorn JDK 8

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#139]
Investigate this issue before releasing version 1.5.3 "final"

Build log: https://ci.appveyor.com/project/asciidoctor/asciidoctor-js/build/411

**Comment by Mogztter** [comment]
There's indeed an issue when running Asciidoctor.js on Nashorn: https://github.com/opal/opal/issues/658

**Comment by rahmanusta** [comment]
I switched to v1.5.3 yet, and see  this problem in Nashorn engine :-1:

**Comment by Mogztter** [comment]
Yes, I'm trying to resolve this issue before releasing 1.5.3 "final".
My knowledge on Nashorn is limited so any help will be greatly appreciated :smile:
Here is an open pull request to run the Nashorn engine against the rubyspec: https://github.com/opal/opal/pull/1195

**Comment by rahmanusta** [comment]
@Mogztter When we replace (1) to (2), it works

(1) Opal.cdecl($scope, 'DEFAULT_STYLESHEET_KEYS', ["", "DEFAULT"].$to_set());
(2) Opal.cdecl($scope, 'DEFAULT_STYLESHEET_KEYS', ["", "DEFAULT"]);

**Comment by rahmanusta** [comment]
Also, when an exception throwed, it doesn't give the reason what the exception is, but if we wrap line 3607 with new Error object, it gives me the reason. like below;

throw exception;  -> throw new Error(exception);

**Comment by Mogztter** [comment]
Resolved in 4cb32ed353fe3d2403c218c7c5885140d1262380
@rahmanusta I've just released [v1.5.3-preview.5](https://github.com/asciidoctor/asciidoctor.js/tree/v1.5.3-preview.5), could you please test if Nashorn engine is now working in AsciidocFX ?

**Comment by mojavelinux** [comment]
Awesome!

**Comment by rahmanusta** [comment]
@Mogztter Thank you so much, it works very well! :+1:

**Comment by Mogztter** [comment]
Cool :smile:
