### ISSUE TITLE
Asciidoctor core needs an official API to access document level attributes

### ISSUE THREAD

**Issue by nerk** [asciidoctor/asciidoctor.js#140]
Asciidoctor API needs to be extended to allow read/write access to document level defined attributes. Asciidoctor 1.5.3 already solves this problem for header level attributes (see #96).

**Comment by mojavelinux** [comment]
Thanks for reporting. Shouldn't we file this in core?

**Comment by nerk** [comment]
This is now https://github.com/asciidoctor/asciidoctor/issues/1575

**Comment by Mogztter** [comment]
Thanks Thomas for creating this issue
