### ISSUE TITLE
Remove "opal_ext/dir.rb" override

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#144]
The implementation in Opal is quite close and I think it's safe to remove this "override".

One difference is that Opal is using `Opal.current_dir || '.'` instead of `ENV['PWD'] || '.'` for `pwd` method. See: https://github.com/opal/opal/blob/master/opal/corelib/dir.rb

**Comment by mojavelinux** [comment]
We definitely want to start getting rid of these patches, so +1. It seems like `Opal.current_dir` is the effectively the same, though we probably want to mention it in the release notes.
