### ISSUE TITLE
Inline attribute doesn't work for ifdef, ifndef and ifeval

### ISSUE THREAD

**Issue by myatmin** [asciidoctor/asciidoctor.js#1459]
```
Test-1
{set:test:TESTING}
ifdef::test[]
Test is defined.
endif::[]

Test-2
ifeval::["{test}" == "TESTING"]
Test is defined
endif::[]

:test: TESTING
Test-3
ifdef::test[]
Test is defined
endif::[]

Test-4
ifeval::["{test}" == "TESTING"]
Test is defined
endif::[]
```

Above syntax output as follow:
```
Test-1

Test-2

Test-3 Test is defined

Test-4 Test is defined
```

Not too sure about this is intentional or issue at the upstream.

**Comment by mojavelinux** [comment]
Your observation is correct. Inline attribute definitions are not processed until the document is converted, which is well after the preprocessor runs. So this is not a supported scenario.

**Comment by myatmin** [comment]
Thanks for the clarification, @mojavelinux !
