### ISSUE TITLE
Remove task runner (Grunt)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#146]
Task runner (Grunt, Gulp...) relies on plugins. This is good but also bad because only a few of them are actively maintained.

http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/

I think we should just use npm as a task runner and remove Grunt:

http://blog.teamtreehouse.com/use-npm-task-runner
http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

What do you think ?

**Comment by mojavelinux** [comment]
:+1: sounds reasonable to me. If we do reintroduce a build tool, I think it should be Gulp, not Grunt. I much prefer Gulp and it has a modular design that is easier for us to control.

**Comment by Mogztter** [comment]
NOTE: Do not forget to backport Uglify max line length setting. See https://github.com/asciidoctor/asciidoctor.js/pull/156

**Comment by mojavelinux** [comment]
I just tried this out and it works great!

I did have to install node 0.12 before I could run the build, so we should probably document that as a prerequisite in CONTRIBUTING-CODE.adoc. I think we should recommend using nvm (at least for those on *nix systems).
