### ISSUE TITLE
Table shown in single column

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#147]
In Version 1.5.3-preview.5 , tables are shown in single column like below;

It it a bug ?

![image](https://cloud.githubusercontent.com/assets/1158804/11627164/1ff5a66a-9cf1-11e5-9ecf-e9ba1df49832.png)

**Comment by Mogztter** [comment]
Can you confirm that this behavior is only in `1.5.3-preview.5` (and not in `1.5.3.preview.4`) ?

**Comment by Mogztter** [comment]
This is working with Asciidoctor `1.5.3` (Ruby). I think something changed in Opal 0.9.0.beta2.

**Comment by rahmanusta** [comment]
Yes sir if I didn't make a mistake

**Comment by Mogztter** [comment]
I will need @mojavelinux's help to know where to look for... Usually this is a Regexp issue but I'm not familiar with the [table.rb](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/table.rb) class :disappointed:

**Comment by mojavelinux** [comment]
This appears to be a bug in Opal, though it's very surprising.

The condition on the following line is returning true when all the conditions indicate it should return false:

https://github.com/asciidoctor/asciidoctor/blob/v1.5.3/lib/asciidoctor/table.rb#L492

It boils down to the following comparison:

```ruby
@col_count != -1
```

which compiles to (minus all the boolean comparison of the result value):

```js
self.col_count['$!='](-1)
```

That is returning true when the value of `@col_count` is -1. It should be false.

If I change it to a greater than comparison:

```ruby
@col_count > -1
```

which compiles to:

```js
$rb_gt(self.col_count, -1)
```

then it works (it returns false when the value of `@col_count` is -1).

So I'd say this is a bug in Opal with regard to a simple number comparison. I'd hate to have to change core to fix this problem.

**Comment by Mogztter** [comment]
@mojavelinux Thanks for the detailed analysis, I will try to debug further. Do you any special techniques to find the root cause ?

**Comment by mojavelinux** [comment]
In theory, a simple test case should reproduce the number comparison
problem. Then we can debug the != method.

**Comment by mojavelinux** [comment]
We override the != method in comparable.rb. I wonder if we're introducing
this bug.

**Comment by Mogztter** [comment]
@mojavelinux you are right, the method override in comparable.rb is the root cause. Just removed the file and now this is working fine.

**Comment by mojavelinux** [comment]
Great! I think we had that file because at one point Opal was spinning into an infinite loop trying to compare numbers. I'm hopeful that error is now gone.
