### ISSUE TITLE
`TypeError: converter.$==` is not a function on custom converter

### ISSUE THREAD

**Issue by flobilosaurus** [asciidoctor/asciidoctor.js#1475]
Hi, im the maintainer of the asciidoc slides vscode extension which depends on @asciidoctor/core@2.2.5 and @asciidoctor/reveal.js: 5.0.0-rc.1, and when i try to convert a document by

```javascript
const vscode = require('vscode');
var asciidoctor = require('@asciidoctor/core')()
var asciidoctorRevealjs = require('@asciidoctor/reveal.js')
asciidoctorRevealjs.register()
var content = '= Document title'
asciidoctor.convert(asciidocText, { safe: 'safe', backend: 'revealjs', attributes: { docDir: this.absoluteDocumentDirectory } });
```

I get the following error message:

```
rejected promise not handled within 1 second: TypeError: converter.$== is not a function
```

This error seams to appear since vscode version >= 1.61.2 and did not appear before.
Is it a misconfiguration on my side or may be a bug on your side?

**Comment by flobilosaurus** [comment]
Ah thanks for investigating. Is the fix easy or complex ?

**Comment by Mogztter** [comment]
> Ah thanks for investigating. Is the fix easy or complex ?

Relatively easy but the testing part takes time.
I just opened https://github.com/asciidoctor/asciidoctor-vscode/issues/478 because I think the Asciidoctor VS code should not replace the built-in HTML5. It will most likely have unattended effects on other converters (like reveal.js).
