### ISSUE TITLE
TypeError: undefined is not an object (evaluating '$a.$$p = block.$to_proc()')

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#151]
There is a bug while using labeledlist.

When you type a labeled list, after pressing second ":" , it throws following error, it causes JVM crash in AsciidocFX for Mac users (Crash is not normal)

TypeError: undefined is not an object (evaluating '$a.$$p = block.$to_proc()')

{"line":23352,"column":63,"sourceURL":"http://localhost:65117/afx/resource/js/asciidoctor-all.js"}

**Comment by mojavelinux** [comment]
I vaguely remember having a double colon issue before. Seems similar to https://github.com/asciidocfx/AsciidocFX/issues/94.

I wonder if this is related to the recent fix that we made in Asciidoctor.js to fix comparison problems. See https://github.com/asciidoctor/asciidoctor.js/commit/3f2173262dd8a7c32a2e9250bfee8f7407a94f43. Have you tried with the latest master?

**Comment by mojavelinux** [comment]
The best way forward now to solve these problems in Asciidoctor.js is to try to create a test case that demonstrates the error. That way we a) aren't guessing and b) are sure it stays fixed.

**Comment by rahmanusta** [comment]
While writing test spec, I understand that it is not caused from Asciidoctor.js, it is about my treeprecessor implementation to apply elements' line number:

```javascript
document.$find_by().forEach(function (node) {
        if (node && node.$source_location)
            if (node.$source_location().lineno) {
                var nodeName = node.node_name;
                var lineno = node.$source_location().lineno;
                node.$attributes()['$[]=']("role", "data-line-" + lineno);
            }
});
```

Is there any limitation for labeled lists ?

**Comment by mojavelinux** [comment]
> Is there any limitation for labeled lists ?

Not that I know of. Do you know which line is failing?

> node.$attributes()['$[]=']("role", "data-line-" + lineno);

There's an add_role method on AbstractNode that you can use here.

**Comment by mojavelinux** [comment]
The problem appears to be when the dlist only consists of a single key:

```
key::
```

**Comment by mojavelinux** [comment]
This looks like a bug in core.

**Comment by mojavelinux** [comment]
This happens because the list item (the value) for a dlist can be nil. This needs to be considered when recursing into blocks in the tree.

I'm not sure what the workaround is atm.

**Comment by mojavelinux** [comment]
We will have a 1.5.4 out soon, as early as this weekend.

**Comment by mojavelinux** [comment]
You can monkeypatch the NilClass to have a find_by object that returns an empty array.

```ruby
class NilClass
  def find_by selector = {}
    []
  end
end
```

Ugly, but it works.

**Comment by mojavelinux** [comment]
> TypeError: undefined is not an object

This usually indicates a null pointer.

**Comment by Mogztter** [comment]
> We will have a 1.5.4 out soon, as early as this weekend.

WHAT ?! This is awesome :smile:

**Comment by mojavelinux** [comment]
Yep. That TOC issue in AsciiDoc table cells is big and we really need to get a fix out to cover it. Plus, we're over 10 resolved issues now, so time to move.

**Comment by rahmanusta** [comment]
Thanks @mojavelinux ! the monkeypatch solves the issue.

**Comment by mojavelinux** [comment]
:+1: This is also fixed upstream now too.

**Comment by Mogztter** [comment]
Hopefully resolved with the first RC of Asciidoctor.js 1.5.4 in https://github.com/asciidoctor/asciidoctor.js/commit/cb688947e6cafdd0b765006d63d5c74793a26239

Feel free to reopen if that's not the case.
