### ISSUE TITLE
Upgrade to Opal 0.9.2

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#152]
https://github.com/opal/opal/tree/v0.9.2

**Comment by Mogztter** [comment]
0.9.0 is released: https://github.com/opal/opal/tree/v0.9.0

https://github.com/opal/opal/blob/v0.9.0/CHANGELOG.md#090-edge

Require attention:
> Renamed:
Hash.keys => Hash.$$keys
Hash.map => Hash.$$map
Hash.smap => Hash.$$smap

**Comment by mojavelinux** [comment]
I wonder if we should alias these for compatibility.

**Comment by Mogztter** [comment]
@mojavelinux Yes definitively! A good candidate for the first public API of Asciidoctor.js (https://github.com/asciidoctor/asciidoctor.js/issues/92). We could also provide a simpler syntax because I'm not a big fan of `doc.attributes.smap`. `doc.attributes.smap['sectnums']` -> `doc.attributes['sectnums']`

**Comment by mojavelinux** [comment]
I absolutely agree. We want to present something as close to the Ruby API as possible so there isn't extra friction.

**Comment by mojavelinux** [comment]
Seems like we're up to Opal 0.9.2 now.

**Comment by Mogztter** [comment]
I saw 0.9.1 yesterday, must have been an error during the release.

**Comment by mojavelinux** [comment]
:+1:
