### ISSUE TITLE
Publish a release candidate version before 1.5.3 final

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#154]

**Comment by Mogztter** [comment]
Done: https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.3-rc.1

@rahmanusta @nerk @mojavelinux @nawroth Hopefully `1.5.3-rc.1` is the last release before `1.5.3` (final) ! Let me know if you find any issue, thanks :smile:

**Comment by nawroth** [comment]
@Mogztter I'm seeing this warning in the console: `Object freezing is not supported by Opal`
Should I open an issue for that?

**Comment by mojavelinux** [comment]
That warning should be harmless, but we could clean it up with a patch in
opal_ext. Ideally, I'd like to see it removed from Opal (or an option if it
isn't already) because it really is unnecessary.

**Comment by Mogztter** [comment]
AFAIK `freeze` method allow to prevent further modifications to an object. In Asciidoctor core, we are using `freeze` to prevent modifications on `options`: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L251

As a result, I think we can safely ignore this warning. I'll add a patch in `opal_ext` for now and I also open an issue: https://github.com/opal/opal/issues/1253

**Comment by rahmanusta** [comment]
Thanks @Mogztter , it seems ready for v1.5.3 !!

**Comment by nerk** [comment]
Works for me.
