### ISSUE TITLE
Add asciidoctor.js to cdnjs

### ISSUE THREAD

**Issue by nawroth** [asciidoctor/asciidoctor.js#158]
See
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md

I'd suggest we go for this once we have a stable 1.5.3 out.
As asciidoctor.js is already published to npmjs, it should be possible to make cdnjs fetch new releases automatically.

**Comment by Mogztter** [comment]
:+1:

**Comment by nrayapati** [comment]
I have logged a issue to cdnjs 

https://github.com/cdnjs/cdnjs/issues/10129

**Comment by Mogztter** [comment]
Thanks @nrayapati !

**Comment by Mogztter** [comment]
Thanks to @sufuf3 and @nrayapati, Asciidoctor.js is now available on cdnjs!
https://cdnjs.com/libraries/asciidoctor.js
