### ISSUE TITLE
Upgrade to Asciidoctor 1.5.4

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#160]
I'm opening this issue to track the progress of upgrading to Asciidoctor 1.5.4.

Asciidoctor 1.5.4 introduces one change to the DocBook output that breaks an existing test. Instead of using "xlink" for the xlink namespace prefix, we now use "xl".

I also noticed that the examples/userguide_test.html doesn't work unless I explicitly require the asciidoctor gem (e.g., `Opal.require("asciidoctor")`). Is this an expected requirement?

**Comment by Mogztter** [comment]
> I'm opening this issue to track the progress of upgrading to Asciidoctor 1.5.4.

Good job :+1: 

> Asciidoctor 1.5.4 introduces one change to the DocBook output that breaks an existing test. Instead of using "xlink" for the xlink namespace prefix, we now use "xl".

Ok.

> I also noticed that the examples/userguide_test.html doesn't work unless I explicitly require the asciidoctor gem (e.g., Opal.require("asciidoctor")). Is this an expected requirement?

`userguide_test.html` is loading `asciidoctor-core.js`: https://github.com/asciidoctor/asciidoctor.js/blob/master/dist/asciidoctor-core.js#L12384

`AsciidoctorConfiguration` should be `undefined` so explicity `Opal.require('asciidoctor');` should be unnecessary... I will try to reproduce this issue

**Comment by mojavelinux** [comment]
> AsciidoctorConfiguration should be undefined so explicity Opal.require('asciidoctor'); should be unnecessary... I will try to reproduce this issue

I now understand what is happening. The asciidoctor-core.js in *build* is different than the one in *dist*. The one in *dist* has the following line:

```js
if (typeof AsciidoctorConfiguration === 'undefined' || typeof AsciidoctorConfiguration.autoRequireModule === 'undefined' || Boolean(AsciidoctorConfiguration.autoRequireModule)) {
  Opal.require('asciidoctor');
}
```

This brings us back to #73 (and probably #72). I really don't like having the dist files in the master of the repository because it leads to a dirty repository after every build. I think they can be in a tag, but I'd rather not have them in master.

**Comment by Mogztter** [comment]
> This brings us back to #73 (and probably #72). I really don't like having the dist files in the master of the repository because it leads to a dirty repository after every build.

Me neither but the good thing is that everyone can download the latest version of Asciidoctor.js.

> I think they can be in a tag, but I'd rather not have them in master.

Something like:

 * Build, tests and examples tasks
  * Use `build` directory (`build` directory is added to `.gitignore`)

 * Release task
  * Create `dist` directory and copy files from `build` directory
  * Stage `dist` directory and commit
  * Tag and publish
  * Remove `dist` directory and commit

Wdyt ?

**Comment by mojavelinux** [comment]
> the good thing is that everyone can download the latest version of Asciidoctor.js

I'd rather people looking for the compiled version to be using a release (even if it's a prerelease). Anyone testing master should be building it.

Your proposal is exactly how I imagined it. :+1:

**Comment by Mogztter** [comment]
[First RC of Asciidoctor.js 1.5.4 is available](https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.4-rc.1) and final is coming soon!

**Comment by mojavelinux** [comment]
:+1:
