### ISSUE TITLE
Add case in File.read for PhantomJS

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#162]
PhantomJS has a fs module, but its API differs from the one in node. We need to update the File.read method to handle this special case. Here's the code we can use:

``` js
 %x(return typeof phantom !== 'undefined' ? require('fs').read(path) : require('fs').readFileSync(path, 'utf8');)
```

Note that the global variable "phantom" is always available in the PhantomJS environment. Otherwise, it identifies itself as node.

**Comment by Mogztter** [comment]
@mojavelinux Resolved in https://github.com/asciidoctor/asciidoctor.js/pull/248

**Comment by mojavelinux** [comment]
:+1:
