### ISSUE TITLE
Minify does not work with latest Java version

### ISSUE THREAD

**Issue by benjaminleonard** [asciidoctor/asciidoctor.js#1664]
This is due to integer version numbers formatted in a way that is not handled by the regex.
`openjdk version "19" 2022-09-20`

Submitted PR here:
https://github.com/bestikk/bestikk-uglify/pull/16

**Comment by Mogztter** [comment]
Should be fixed in https://github.com/asciidoctor/asciidoctor.js/commit/67581d39217e63a6ad41c7420d0bc4ce2f0e0eb2
Thanks for the fix!
