### ISSUE TITLE
Remove Asciidoctor namespace in type definition

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#1669]
It might be less confusing:

**Current**
```ts
import asciidoctor, { Asciidoctor } from '@asciidoctor/core';

const processor = asciidoctor();
const Converter = ({ node }: { node: Asciidoctor.AbstractBlock }) => { /* ... */};
```

**Proposal**
```ts
import Asciidoctor, { AbstractBlock } from '@asciidoctor/core';

const asciidoctor = Asciidoctor();
const Converter = ({ node }: { node: AbstractBlock }) => { /* ... */};
```

And TypeScript seems to recommend that approach:

> Consumers of your module should have as little friction as possible when using things that you export. Adding too many levels of nesting tends to be cumbersome, so think carefully about how you want to structure things.

> Exporting a namespace from your module is an example of adding too many layers of nesting. While namespaces sometime have their uses, they add an extra level of indirection when using modules. This can quickly become a pain point for users, and is usually unnecessary.

https://www.typescriptlang.org/docs/handbook/modules.html#guidance-for-structuring-modules

**Comment by mojavelinux** [comment]
Personally, I think our recommendation for the name of the resolved Asciidoctor instance should be `Asciidoctor`, not `asciidoctor`. That makes the code more consistent with the Ruby side. Plus, while it is technically an instantiated object, it acts more like a class.

**Comment by Mogztter** [comment]
You mean:

```js
import asciidoctor, { AbstractBlock } from '@asciidoctor/core';

const Asciidoctor = asciidoctor();
```

Ideally, we should have:

```js
import { convert, AbstractBlock } from '@asciidoctor/core';

const html = convert('Hello _world_');
```

The reason we have to instantiate something is mostly a limitation/workaround for Opal.
