### ISSUE TITLE
Tables: Cell alignment wrongly inherited after cell spans

### ISSUE THREAD

**Issue by fbruetting** [asciidoctor/asciidoctor.js#1670]
# Problem

I just tried to span a cell along three rows. But the cells in the column after the spanned cell (except for the first one) all *inherit the alignment of the column of the spanned cell* instead of their own column’s default. I would expect all `c`s of the third column to get centered, because I never changed the format of that column.

I tested with the Firefox-Extension “Asciidoctor.js Live Preview” v2.7.0.

# Code

````asciidoc
[cols="^.^4, >.^2, ^.^4"]
|===
| Center     | Right  | Center

| a          | b      | c
| a      .3+<| b      | c
| a                   | c
| a                   | c
| a          | b      | c
|===
````

# Result
![Bildschirmfoto vom 2022-11-10 15-42-52](https://user-images.githubusercontent.com/10520767/201121510-b99df4ca-2f77-4149-9a1a-7105d595f341.png)

**Comment by mojavelinux** [comment]
This is a known issue in Asciidoctor core. Using row spans can throw off the mapping of the colspec. In these cases, you need to put the alignment on the cell itself.
