### ISSUE TITLE
How to provide `template_dir` to a Custom Converter following composition pattern?

### ISSUE THREAD

**Issue by saneef** [asciidoctor/asciidoctor.js#1687]
I'm extending the default HTML5 converter following [the composition pattern](https://docs.asciidoctor.org/asciidoctor.js/latest/extend/converter/custom-converter/#composition-pattern). In the past, we were relying on [Template Converter](https://docs.asciidoctor.org/asciidoctor.js/latest/extend/converter/template-converter/) to render some nodes.

Would it be possible to provide the `template_dir` or `template_dirs` to the parent, `asciidoctor.Html5Converter`, of a custom converter? 

Following the composition pattern, `asciidoctor.convert(content, { template_dir: "<...>" })`, doesn't work for me.

**Comment by ggrossetie** [comment]
We do have a test where we are using a template converter with the built-in Html5Converter: https://github.com/asciidoctor/asciidoctor.js/blob/9e208c77d0889522738f488309976bcfaba06e88/packages/core/spec/node/asciidoctor.spec.js#L3067-L3074

You can probably use a CompositeConverter to use your custom converter with a fallback to a TemplateConverter.

If you need support, please ask your questions on the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). Thanks!
