### ISSUE TITLE
Compile Ruby code from Node.js

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#169]
Once [Opal compiler](https://github.com/opal/opal/blob/master/lib/opal/builder.rb) will be available in Node.js (https://github.com/opal/opal/issues/1290), we should be able to remove completely Ruby from the build (and have a 100% JavaScript build!).

Related to #72

**Comment by mojavelinux** [comment]
Incredible. It's pretty amazing to think that Opal not only runs Ruby in JavaScript, but doesn't even get Ruby involved at all.

**Comment by Mogztter** [comment]
Made some progress today, this is gonna be awesome!!!

>  It's pretty amazing to think that Opal not only runs Ruby in JavaScript, but doesn't even get Ruby involved at all.

Yep, Opal on Opal :loop: 
We compile Ruby code to JavaScript in JavaScript (without Ruby) "mind blown" :wink:

**Comment by Mogztter** [comment]
And done as part of #182
