### ISSUE TITLE
The display of some emojis(zero to nine and hash) is not working.

### ISSUE THREAD

**Issue by atsushi-ide** [asciidoctor/asciidoctor.js#1701]
asciidoctor-emoji-inline-macro.js

hash: '23 - 20e3',
zero: '30 - 20e3',
one: '31 - 20e3',
two: '32 - 20e3',
three: '33 - 20e3',
four: '34 - 20e3',
five: '35 - 20e3',
six: '36 - 20e3',
seven: '37 - 20e3',
eight: '38 - 20e3',
nine: '39 - 20e3',

please fix these below

hash: '23-20e3',
zero: '30-20e3',
one: '31-20e3',
two: '32-20e3',
three: '33-20e3',
four: '34-20e3',
five: '35-20e3',
six: '36-20e3',
seven: '37-20e3',
eight: '38-20e3',
nine: '39-20e3',

**Comment by ggrossetie** [comment]
I guess it belongs to https://github.com/ggrossetie/asciidoctor-emoji ?
