### ISSUE TITLE
How to produce other output formats (pdf, markdown) with asciidoctor.js?

### ISSUE THREAD

**Issue by stefaneidelloth** [asciidoctor/asciidoctor.js#1703]
What is the recommended way to produce other output formats than html with asciidoctr.js?
Or is asciidoctor.js limited to html and if I want to have other output formats, I have to use
the original asciidoc application and need to install ruby?

I would like to use asciidoctor.js on Windows command line and in GitLab CI pipelines (running on Linux) to:

a) produce *.html documentation

b) produce *.pdf documentation

c) produce *.md documentation

Related:

https://github.com/ggrossetie/asciidoctor-web-pdf/issues/686

https://github.com/opendevise/downdoc/issues/12

**Comment by ggrossetie** [comment]
Please direct usage question to the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). You can find more information about the support policy on the following page in the docs: [docs.asciidoctor.org/about/support](https://docs.asciidoctor.org/about/support/).
