### ISSUE TITLE
How to get a search bar in the html output?

### ISSUE THREAD

**Issue by stefaneidelloth** [asciidoctor/asciidoctor.js#1704]
How can I include a search bar in my html output, similar to the one used in the Asciidoc documentation:

![image](https://github.com/asciidoctor/asciidoctor.js/assets/12675339/3a434176-755a-4872-b2fc-7d3e605a3810)

or the one provided by MkDocs:

https://www.mkdocs.org/getting-started/#adding-pages

Similar to the feature for an automatic table of contents

https://docs.asciidoctor.org/asciidoc/latest/toc/

I would expect a feature for an automatic search bar:

`:search:`

I found an old article

https://rmannibucau.metawerx.net/asciidoctor-search-index-creation.html

but as a newbie to asciidoc.js I don't know where to start. 

=> Could you please include a section about search bar / client search in the documentation and describe if search is supported at all. If there are some extensions for it etc. 

If documentation already exists on this topic, please let me know the link. I could not find it.

**Comment by ggrossetie** [comment]
@stefaneidelloth could you please direct usage question to the project chat at [chat.asciidoctor.org](https://chat.asciidoctor.org/). The issue tracker is for verifiable bugs, regressions, security vulnerabilities, and formal and specific change requests. It is not a support portal. Thanks!
