### ISSUE TITLE
Update dependency for package pug to fix a vulnaribilty issue

### ISSUE THREAD

**Issue by VGalata** [asciidoctor/asciidoctor.js#1705]
Package `pug` has several versions affected by [this vulnerability issue](https://github.com/advisories/GHSA-p493-635q-r6gr).
Are there plans to update the dependency to the next major version in the `asciidoctor` package? The current version is `^2.0.4` (see [here](https://github.com/asciidoctor/asciidoctor.js/blob/b0623fd8567f28099a8ddce90c17ccacf9da37df/packages/asciidoctor/package.json#L53)).

**Comment by VGalata** [comment]
Update: it seems to be addressed in https://github.com/asciidoctor/asciidoctor.js/pull/1689.

**Comment by ggrossetie** [comment]
Please note that Pug is included in the "all-in-one" package `asciidoctor` but you can also use/install `@asciidoctor/core` with your own version of Pug (if you are using it).

**Comment by VGalata** [comment]
Thank you, @ggrossetie! But, `asciidoctor` is only a transitive dependency in our case.

**Comment by ggrossetie** [comment]
Should be fixed, the version in the package-lock.json is now `3.0.2`
