### ISSUE TITLE
Don't work in simple browser

### ISSUE THREAD

**Issue by ProgrammeurZero** [asciidoctor/asciidoctor.js#1707]
When write:
`var asciidoctor = Asciidoctor()`
my console tell me that `Asciidoctor is undefined'.

**Comment by ggrossetie** [comment]
Asciidoctor.js is most likely not correctly set up.

Please direct usage questions to the chat first: https://chat.asciidoctor.org. If we determine there is a bug, then we can proceed with a new issue. This helps us to better maintain the project.

Thanks.
