### ISSUE TITLE
"Module not found" error when using v3.0.3 in a Next.js app

### ISSUE THREAD

**Issue by korva** [asciidoctor/asciidoctor.js#1723]
Seems like something changed between asciidoctor.js 3.0.2 and 3.0.3 that prevents importing the package in an Next.js framework app.

Steps to reproduce:
1. Create a Next.js app skeleton (using defaults) with https://nextjs.org/docs/pages/api-reference/create-next-app
2. Add asciidoctor.js as per instructions in readme
3. Build and run app with 'npm run dev' -> following error happens at build time:

```
/node_modules/asciidoctor/index.js:1:0
Module not found: Default condition should be last one

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./app/page.tsx
```

Downgrading to asciidoctor.js 3.0.2 removes the error.
Using latest Next.js 14.1.0.

**Comment by ggrossetie** [comment]
Hey! It has been fixed in https://github.com/asciidoctor/asciidoctor.js/pull/1722 and will be part of the next release
