### ISSUE TITLE
Issue with NPM latest tag

### ISSUE THREAD

**Issue by sinedied** [asciidoctor/asciidoctor.js#1728]
Hello,

It seems there's an issue with your NPM release on the `latest` tag (the default one).

<img width="784" alt="image" src="https://github.com/asciidoctor/asciidoctor.js/assets/593151/c3fa6430-7366-4744-a763-cf06dff8fa7d">

It shows that `2.2.7` is the latest version and running `npm outdated` shows that updating to latest would downgrade from v3 to v2:

<img width="852" alt="image" src="https://github.com/asciidoctor/asciidoctor.js/assets/593151/74dcdab6-a1d0-400c-8ae2-494d2ca35d90">

`3.0.4` should still be the one tagged as `latest`, and updates to the older versions should be pushed to another tag I believe.

Could you have a look?

**Comment by ggrossetie** [comment]
Argh, nice catch 😬 
I moved the latest tag back to 3.0.4.

Thanks for the heads-up!
