### ISSUE TITLE
asciidoctor.loadFile and convert has no css

### ISSUE THREAD

**Issue by virtualdreams** [asciidoctor/asciidoctor.js#1729]
Hello,

I don't know what's wrong, but there is no stylesheet in the produced HTML.
However, when I render from a string, a stylesheet is also included.

```js
const asciidoctor = require('asciidoctor')
const ad = asciidoctor()

// has no stylesheet link
var doc = ad.loadFile(file, { safe: 'unsafe' })
var html = doc.convert({ standalone: true, attributes: { stylesdir: '/static/' } })

// has a stylesheet link
var html = ad.convert('= Welcome\n\nHello, _AsciiDoctor_', { standalone: true, attributes: { 'stylesdir': '/static/' } }
```

Why?

**Comment by ggrossetie** [comment]
Did you try to move the options in the `loadFile` function?

```js
var doc = ad.loadFile(file, { safe: 'unsafe', standalone: true, attributes: { stylesdir: '/static/' } })
var html = doc.convert()
```

As far as I recall, some options/attributes need to be defined on the Document (and will be "ignored" when calling `convert` on `Document`).

**Comment by ggrossetie** [comment]
In the future, please direct questions to the project chat:  https://asciidoctor.zulipchat.com/
