### ISSUE TITLE
Mutable String methods are not supported in Opal.

### ISSUE THREAD

**Issue by nathany** [asciidoctor/asciidoctor.js#173]
NotImplementedError : String#sub! not supported. Mutable String methods are not supported in Opal.

Asciidoctor.js Live Preview 1.5.4.100
Chrome Version 48.0.2564.97 (64-bit)

Some AsciiDoc files are reporting this error in the Chrome extension. They were rendering before, so perhaps this issue was introduced in an update?

**Comment by mojavelinux** [comment]
Oops, it looks like this might be the new whitespace expansion logic in verbatim blocks. I forgot about the fact that we can't use sub! gsub! in Opal. This would occur if you have tabs in your verbatim blocks. It's actually harmless since it will simply skip expanding the tabs. However, we'll definitely want to clean this up for 1.5.5.

**Comment by mojavelinux** [comment]
This change will need to happen in core.

**Comment by Mogztter** [comment]
@nathany Just to clarify, the document is rendering but there's an error in the console ?

**Comment by nathany** [comment]
No, the document isn't rendering.

![asciidoc-error](https://cloud.githubusercontent.com/assets/4566/12766454/2dd9d31c-c9c1-11e5-92d7-1147e6474b1e.png)

**Comment by Mogztter** [comment]
Urgh!

@mojavelinux Can we monkey-patch the `sub!` method in Asciidoctor.js ?

**Comment by Mogztter** [comment]
@nathany Could you please provide an example ? I tried to create a document with tabs in a verbatim block but the document is rendered.

**Comment by mojavelinux** [comment]
The behavior is triggered when either the `indent` or `tabsize` attributes are set on the block.

We can certainly monkeypatch for this. In fact, it's a simple one liner (applied to lib/asciidoctor/parser.rb)

`line.(g)?sub!\(` needs to become `line = line.\1sub(`

Opal can't make this translation, but we can do it easily.

**Comment by mojavelinux** [comment]
To be more clear:

```
line.sub!(...
```

needs to become

```
line = line.sub(...
```

And the same for gsub.

**Comment by nathany** [comment]
It sounds like a good change, especially with Ruby (MRI) adopting immutable (frozen) strings throughout in coming versions. Maybe the Asciidoctor core could run tests under [Ruby 2.3](https://www.ruby-lang.org/en/news/2015/12/25/ruby-2-3-0-released/) with some of the frozen pragmas/flags enabled?

As for a minimal example, all my files specify tabsize at the top. Commenting that out appears to resolve the issue.

```asciidoc
= Learn Go

:source-language: go
:tabsize: 4

[[playground.go,Listing 1.1]]
.Listing 1.1 Hello, playground: playground.go
[source]
----
package main //<1>

import "fmt" //<2>

func main() { //<3>
	fmt.Println("Hello, playground") //<4>
}
----
<1> Declare the package the following code belongs to
<2> Make the `fmt` (format) package available for use
<3> Declare a function named main
<4> Print *Hello, playground* to the screen
```

Sometimes I specify `[source,indent=0]` when including a section of a file with tags, but that doesn't appear to be triggering the issue.

**Comment by mojavelinux** [comment]
That's because the source also has to have a tab in it. You can see the logic here:

* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L1077-L1083
* https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/parser.rb#L2668-L2675

We generally have a policy in Asciidoctor of not modifying strings. We only use it in two very hot places in the code for performance reasons. I'll remove them once I'm satisfied that it won't affect performance. We have a special guard for Opal to not use sub!/gsub!, but I forgot about it when I ported this code from Asciidoctor PDF.

**Comment by mojavelinux** [comment]
> Maybe the Asciidoctor core could run tests under Ruby 2.3 with some of the frozen pragmas/flags enabled?

I do like this idea, though.

**Comment by nathany** [comment]
Thanks. Glad I have a workaround for now.

**Comment by Mogztter** [comment]
I will also add a post compile task to check if asciidoctor-*.js contains `$gsub!` or `$sub!` methods calls.

**Comment by mojavelinux** [comment]
I would make that a test. I think the test suite rather than the build itself should have that types of defensive check. But otherwise, :+1:

**Comment by nerk** [comment]
A fix for 1.5.5 would be really great. Some people over here just got bitten by this using the Brackets plugin.

**Comment by nathany** [comment]
Still can't use :tabsize: with the Chrome extension.

**Comment by Mogztter** [comment]
Hey @nathany, the Chrome extension is still using Asciidoctor.js 1.5.4.
I've already upgraded master branch to Asciidoctor.js 1.5.5-4 but I need to do some testing before releasing this version.
Sorry about that 😐

**Comment by nathany** [comment]
Okay, no worries. Is there an issue I can subscribe to so I know when the new Chrome extension goes out? Thanks!

**Comment by Mogztter** [comment]
Fresh out of the oven: https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/136 😉
