### ISSUE TITLE
Using asciidoctor.js in browser

### ISSUE THREAD

**Issue by slavos1** [asciidoctor/asciidoctor.js#1733]
I was trying to use Asciidoctor.js **3.0.4** in a browser (just plain HTML and vanilla JS).

I had the same problem as #1257 but [the solution](https://docs.asciidoctor.org/asciidoctor.js/latest/setup/install/#basic-browser-setup):
```html
<script src="node_modules/@asciidoctor/core/dist/browser/asciidoctor.js"></script>
var asciidoctor = Asciidoctor()
```
did not work for me.

What I tried:
1. `pnpm i asciidoctor` (using pnpm instead of node should not matter here I guess)
2. put `<script src="node_modules/.pnpm/@asciidoctor+core@3.0.4/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js"></script>` in `<head>` in my `index.html`
3. within my `index.html`, I used `var asciidoctor = Asciidoctor()` within a script in the `body` element
4. served the page locally with `caddy file-server -l :5555 -b $PWD`

When I loaded the page, I got:
```shell
Uncaught 
ReferenceError: Asciidoctor is not defined
```

What eventually worked after some experimentation was:
```javascript
import Asciidoctor from "./node_modules/.pnpm/@asciidoctor+core@3.0.4/node_modules/@asciidoctor/core/dist/browser/asciidoctor.js";

const adoc = Asciidoctor();
```

Can please anybody explain what is going on here/what I have been doing wrong and/or update the documentation?

Thanks. 🙏🏻

**Comment by ggrossetie** [comment]
Hey!
The documentation is outdated, Asciidoctor.js is only available as an ESM module for the browser (i.e., you should use `import`). Feel free to open a pull request to fix the documentation.

**Comment by ggrossetie** [comment]
I've updated the documentation: https://docs.asciidoctor.org/asciidoctor.js/latest/setup/install/#basic-browser-setup
@slavos1 Let me know if it's clear enough.
