### ISSUE TITLE
Exact error message on @asciidoctor/core version 3.0.4

### ISSUE THREAD

**Issue by 757363985** [asciidoctor/asciidoctor.js#1737]
Cannot read properties of undefined (reading '$$is_number')

**Comment by 757363985** [comment]
when 
const Asciidoctor = asciidoctor(); 
have a error message Cannot read properties of undefined (reading '$$is_number')
![image](https://github.com/asciidoctor/asciidoctor.js/assets/53483524/9cad0f89-4097-45ed-89ab-596bdd5fb39b)

**Comment by 757363985** [comment]
![image](https://github.com/asciidoctor/asciidoctor.js/assets/53483524/ee34e5b0-6af7-4e34-8533-8e1f65dfb6b8)

**Comment by ggrossetie** [comment]
Please provide a minimal reproduction case with step by step instruction. It seems to be an integration issue.
Also it's better to copy/paste error message rather than using images.

**Comment by ggrossetie** [comment]
Please ask questions about usage in the project chat https://chat.asciidotor.org/. The issue tracker is not a support portal. You are welcome to discuss anything in the project chat.
