### ISSUE TITLE
Parsing to AST converts source text

### ISSUE THREAD

**Issue by cdaringe** [asciidoctor/asciidoctor.js#1738]
# Problem

Parsing/loading converts, against expectation.

For example:

```js
const asciidocText = `
* here's a link https://foo.com[bar]
`
const ast = asciidoctor.load(asciidocText, { safe: "safe" });
const listItemStrings = ast.findBy({ context: "list_item" }).map((node) => {
  return (node as ListItem).getText(); // string with HTML!
})
```

# Discussion

I expect `asciidoctor.convert` to _convert_ to HTML. However, it seems like _parsing_ converts, against expectation.

Possible solutions?:

- `getSource` (non-implemented) perhaps should have the correct content?
- `getText` should return the correct content

**Comment by ggrossetie** [comment]
I believe this is an upstream issue since Asciidoctor does not have an inline parser (i.e., inline elements are not part of the Document): https://github.com/asciidoctor/asciidoctor/issues/61

**Comment by cdaringe** [comment]
thx will follow there
