### ISSUE TITLE
Can I use ESM to write extenstions?

### ISSUE THREAD

**Issue by louiss0** [asciidoctor/asciidoctor.js#1739]
I want to know if  I can use ESM to write Asciidoc modules?
I'm asking this question because I feel comfortable writing ESM and it's the future.
I also wonder If there's any Typescript support?

**Comment by ggrossetie** [comment]
Hey! Node.js can synchronously require ESM module when `--experimental-require-module` is enabled

> The CommonJS module require currently only supports loading synchronous ES modules when --experimental-require-module is enabled.

https://nodejs.org/api/esm.html#interoperability-with-commonjs

Asciidoctor.js is transpiled from Ruby and cannot use `async` / `await`.

**Comment by louiss0** [comment]
> Hey! Node.js can synchronously require ESM module when `--experimental-require-module` is enabled
> 
> > The CommonJS module require currently only supports loading synchronous ES modules when --experimental-require-module is enabled.
> 
> https://nodejs.org/api/esm.html#interoperability-with-commonjs
> 
> Asciidoctor.js is transpiled from Ruby and cannot use `async` / `await`.

Why mention Async Await? Are you telling me that Asciidoctor needs to load modules using it?

**Comment by ggrossetie** [comment]
Asciidoctor.js will _require_ extensions. I assume you were talking about requiring extensions from the CLI? If you use the Asciidoctor.js API then you can `import` your extension and register it.

**Comment by louiss0** [comment]
That answered my problem
