### ISSUE TITLE
Fail to render header using node

### ISSUE THREAD

**Issue by matsev** [asciidoctor/asciidoctor.js#175]
AsciiDoctor.js fails to render title using the `=` prefix.

Example (basically the same as `sample.js` used [this blog](http://asciidoctor.org/news/2014/08/23/asciidoctor-js-1-5-0-released/), but with changed `content`:

``` javascript
var asciidoctor = require('asciidoctor.js')();
var opal = asciidoctor.Opal;

var processor = null;
var useExtensions = true;

if (useExtensions) {
    processor = asciidoctor.Asciidoctor(true);
}
else {
    processor = asciidoctor.Asciidoctor();
}

var content = "= This is a title!";
var options = opal.hash({doctype: 'inline', attributes: ['showtitle']});
var html = processor.$convert(content, options);
console.log(html);
```

---

**Expected result:**

The text `This is a title!` should be rendered in a header tag.

---

**Actual result:**

```
$ node sample.js
NilClass { '$$id': 4, apply: [Function], call: [Function] }

```

---

**Environment:**

```
$ node --version 
v5.5.0
```

```
$ npm install asciidoctor.js
packaging@0.1.0 /Users/mattias/Projects/Anima/primo-lambda/packaging
└─┬ asciidoctor.js@1.5.5-1
  ├── opal-npm-wrapper@0.9.0-beta2
  └── xmlhttprequest@1.7.0
```

```
$ npm -version
3.5.3
```

OS X El Capitan 10.11.3

**Comment by mojavelinux** [comment]
The problem seems to be here:

```
doctype: 'inline'
```

The inline doctype is for converting a single line of paragraph text. In this case, you don't have any paragraph content, hence the crash. (maybe it shouldn't hard crash, but it still won't give you any output).

You probably mean to set the doctype to `article` (which is the default).

**Comment by matsev** [comment]
Thanks for a fast and accurate response! Changing the doctype did indeed solve my problem. May I suggest that you improve the error message described above.

**Comment by mojavelinux** [comment]
If I remember correctly, we have discussed this. The return value now is nil, which in Opal just looks weird (because it's a wrapped class). But that is a valid return value. What I think we need to do is make the inline doctype use case more clear in the docs. http://asciidoctor.org/docs/user-manual/#document-types I think what that section is missing is an explanation of what happens when there isn't content to convert. It should be clear that a null value is returned.

**Comment by Mogztter** [comment]
@mojavelinux The only way for Asciidoctor.js to add an error message is to wrap the `$convert` method. Maybe a warn log in Asciidoctor core is the way to go ? I must say `inline` and `article` can be confusing for new user and a warn message could clear that up.

**Comment by mojavelinux** [comment]
If we added a warning, it would need to go into core. I think it's reasonable to issue a warning if there is a block, but it's not a candidate for inline conversion.

This is also about education. I think part of the surprise is the Opal NilClass return value. Generally, we don't return nil in Asciidoctor, but this is one case when we do. If the console.log line was changed to the following, the result would have looked less surprising.

```
console.log(String(html));
```

**Comment by Mogztter** [comment]
I think https://github.com/asciidoctor/asciidoctor.js/pull/223 partially "resolve" this issue. We could also go one step further and return `undefined` in the wrapper API #180 ?

> If we added a warning, it would need to go into core. I think it's reasonable to issue a warning if there is a block, but it's not a candidate for inline conversion.

Can I create an issue in core to track this issue ?

**Comment by mojavelinux** [comment]
> Can I create an issue in core to track this issue ?

Absolutely.

**Comment by Mogztter** [comment]
@matsev For the record, here's the code and the result with `asciidoctor.js@1.5.6-preview.3`:

```js
var asciidoctor = require('asciidoctor.js')();
var content = "= This is a title!";
var html = asciidoctor.convert(content, {doctype: 'inline', attributes: {showtitle: true}});
console.log(html);
```

```
$ node sample.js

```

I've asked @mojavelinux to add a warning message, so hopefully in a near future, you should see something like:

```
$ node sample.js
asciidoctor: WARNING: no inline candidate; use the inline doctype to convert a single paragragh, verbatim, or raw block

```

Here's the issue in core: https://github.com/asciidoctor/asciidoctor/issues/1890

**Comment by Mogztter** [comment]
I think we can close this issue, the output is now explicit.
@matsev If you disagree or if you think we can make things even better, feel free to reopen this issue :smile:
