### ISSUE TITLE
Extensions: uninitialized constant Object::Extensions

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#176]
I'm getting this exception with latest asciidoctor and asciidoctor.js code base. What can be the reason ? Thanks.

**Comment by Mogztter** [comment]
Not sure, could you please post the full stack trace ? What's your JavaScript engine ? Nashorn ?

**Comment by rahmanusta** [comment]
I've realized that you switched building Asciidoctor.js from Grunt to npm build.

Do you use `npm run-script release` command to generate dist ?

**Comment by Mogztter** [comment]
dist folder is only generated when we’re releasing a version (only
available on tags).
But you don't need dist folder, everything is available in build folder
when you build the project with npm run build :
https://github.com/asciidoctor/asciidoctor.js/blob/master/CONTRIBUTING-CODE.adoc#building-asciidoctorjs

**Comment by rahmanusta** [comment]
Yes, it is okay now :) Thanks @Mogztter

**Comment by Mogztter** [comment]
Ok cool, for my knowledge, what was the issue ?

**Comment by rahmanusta** [comment]
I was trying to build Asciidoctor.js with the old way `grunt` command
