### ISSUE TITLE
Fetch gem from RubyGems using Node.js

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#181]
To compile Asciidoctor to JavaScript in JavaScript, we need to clone asciidoctor repository.
Instead we could download gem from RubyGems:

URL structure:
```
https://rubygems.org/downloads/{{name}}-{{version}}.gem
```

Archive structure:
```
$ mkdir tmp
$ tar xf asciidoctor-1.5.4.gem -C tmp
$ cd tmp 
$ ls -1
checksums.yaml.gz
data.tar.gz
metadata.gz
$ mkdir asciidoctor
$ tar xf data.tar.gz -C asciidoctor
$ cd asciidoctor
$ ls -1
bin
CHANGELOG.adoc
CONTRIBUTING.adoc
data
features
lib
LICENSE.adoc
man
Rakefile
README.adoc
test
```

**Comment by mojavelinux** [comment]
You could also download a zip of the release from GitHub. That might be simpler as it doesn't require multiple steps to unpack.

https://github.com/asciidoctor/asciidoctor/archive/v1.5.4.zip

**Comment by Mogztter** [comment]
That's an excellent idea! :+1:

**Comment by Mogztter** [comment]
Resolved in https://github.com/asciidoctor/asciidoctor.js/commit/2f95f284ccc2f67bd43e9191a26378a3230a3eb7

We now download zip of the release from GitHub (as suggested by @mojavelinux)
