### ISSUE TITLE
Opal 0.10.0.beta3 is considerably slower than Opal 0.9.0.beta2

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#183]
Raw result: https://gist.github.com/Mogztter/b883b78a2e8764da04c855a7fc14a95e

 * Run 1 is on average 75,11% slower
 * Run 2 is on average 100,61% slower
 * Run 3 is on average 120,31% slower
 * Run 4 is on average 122,90% slower

**Comment by mojavelinux** [comment]
:crying_cat_face:

**Comment by Mogztter** [comment]
I've opened an issue in Opal and I've also created a repository to reproduce this issue: https://github.com/Mogztter/asciidoctor.js-benchmark

Could you please test on your machine to see if you get the same results ?

**Comment by Mogztter** [comment]
This is now fixed in Opal! :tada:

**Comment by mojavelinux** [comment]
I'm really impressed by your hard work on this one. Tracking down these sorts of problems is extremely tedious and you really provided some great observations and analysis to help work through it. :beers:

**Comment by Mogztter** [comment]
Thank you!!
Indeed this was not an easy task but it was fun and I learn a lot in the process 😉
