### ISSUE TITLE
Adding a block to every generated file

### ISSUE THREAD

**Issue by pbalaga** [asciidoctor/asciidoctor.js#186]
Hello,

I would like to add a constant block to every file generated with asciidoctor.js. I could do that by doing an 'include' in every file, but isn't there a simpler way not to repeat that in each file (option / attribute)? 

Since I'm rendering to HTML, I know I could use a templating engine and a layout, but letting Asciidoctor.js do all the stuff has some advantages:
- guarantee that it will have styling consistent with the rest of the content even if asciidoc settings change
- getting template engine to include .html generated by asciidoc seems more complicated

**Comment by Mogztter** [comment]
Hello @pbalaga,

If you want to add custom content to the header or footer of a document, you can use [docinfo file](http://asciidoctor.org/docs/user-manual/#docinfo-file).

If you want to add a constant block elsewhere, could you please give me an example of what you trying to achieve ?

**Comment by pbalaga** [comment]
Imagine that you want to add sort of a disclaimer to the begining of every documentation page, e.g. "alpha version - API may be changed, watch out!".

It wouldn't be bad if that message was consistent with asciidoc warning admonition and that's why I don't want to use a templating engine such as jade.

As far as the position of such a disclaimer is concerned, it's ok at the top. To put it elsewhere within the document you would need to know its internal structure, so it's a no-go.

**Comment by Mogztter** [comment]
Ok thanks for the explanation. I think docinfo will not work in your case.

You are not using a static site generator, like Awestruct, right ? You are just converting AsciiDoc files with Asciidoctor.js ? Are you using Asciidoctor.js in a Node environment or in a browser environment ?

You could use [custom templates in Asciidoctor](http://asciidoctor.org/docs/user-manual/#provide-custom-templates) but if you don't want to use templates at all, I think you will have no choice but include your disclaimer in every files using the `include` directive.
Maybe @mojavelinux has a better idea ?

**Comment by pbalaga** [comment]
I'm using Metalsmith static site generator in Node together with jade as templating engine. It's not that I don't want to use templates but I wanted to know if there is a built-in method in asciidoctor. 

I'm trying to ensure that the same styling is applied to admonitions (i.e. warnings) and the disclaimer. Jade can include other files, but has problems including html files that are the final product of metalsmith pipeline. It can be done but involves either tricky customizations or compiling docs in 2 passes. I'm not sure it's worth a shot.

**Comment by mojavelinux** [comment]
> I wanted to know if there is a built-in method in asciidoctor.

Probably what you want here is a Treeprocessor extension. That allows you to take the document structure and inject a new block somewhere in the tree. You can also use a Postprocessor to inject content into the generated HTML (before it gets passed to the metalsmith layout), but that's more of a brute force approach.

**Comment by mojavelinux** [comment]
In the next preview of Asciidoctor 1.5.6, it will be possible to write extensions directly in JavaScript. Depending on where you want to insert the content, you could use a TreeProcessor, a Postprocessor, or even a DocinfoProcessor. This is exactly the sort of thing the extensions were designed to handle.

**Comment by Mogztter** [comment]
I'm closing this issue, if you need help to write a custom extension in JavaScript, please ask on Gitter: http://gitter.im/asciidoctor/asciidoctor.js
