### ISSUE TITLE
Creating inline image in a InlineMacroExtension

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#188]
Hello,

I'm doing this to create image block;
```javascript
self.$create_image_block(parent, Opal.hash(attributes));
```

But, I'm not able to create inline image in similar way like below;

```javascript
self.$create_inline(parent, "image");
```

How can I create inline image like block image in Asciidoctor or Asciidoctor.js ? @Mogztter @mojavelinux 

Thanks.

**Comment by mojavelinux** [comment]
I be honest, I've never tried. But my recommended approach is to create a simple extension in Ruby, transpile it to JavaScript, then study what it made. That's the quickest way I think to getting in the right ballpark.

**Comment by rahmanusta** [comment]
Actually I was doing this, for example I edited the emoji plugin, but I'm not able to create inline image in this way.

ERROR => {"name":"include?","message":"undefined method `include?' for nil","args":[".svg"],"line":4545,"column":28,"sourceURL":"http://localhost:50293/afx/resource/js/asciidoctor-all.js"}

```ruby
class EmojiInlineMacro < Extensions::InlineMacroProcessor
  use_dsl

  named :emoji
  name_positional_attributes 'content', 'file'

  def process parent, target, attributes

    # this works
    # %(<img src='' alt='this works'></img) 

    # this works
    # create_image_block parent, attrs

    # doesn't work
    create_inline parent, :image , nil, attrs

    # doesn't work
    # Inline.new(parent, :image, nil, :type => "image", :target => target, :attributes => attributes).convert
  end
end

```

**Comment by Mogztter** [comment]
@rahmanusta Do you have the full stack trace ? I want to know on what object `include?` method is called.

**Comment by rahmanusta** [comment]
I'm fortunately getting this in webworker, but I found the reason :) It is because I'm not sending any `target` attribute and the target is being nil and it breaks when trying to access include method of nil.

https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L540

My target just was to see whether it generates an inline image, so then the following function generates inline-image normally,

self.$create_inline(parent, "image", nil, Opal.hash({target: "deneme.png"})).$convert();
