### ISSUE TITLE
Asciidoctor-latex

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor.js#192]
Implement the asciidoctor-latex extension in asciidoctor.js.  I've implemented an alternative to using Ruby's prepend, so this should now be possible.  See [L571](https://github.com/asciidoctor/asciidoctor-latex/blob/master/lib/asciidoctor/latex/converter.rb#L571) of the converter code.  Code quality of `asciidoctor-latex` may need to be improved for this.

Reason: I would like be able to render asciidoc-latex documents in the client so as to avoid hitting the server so often for [scripta.io](http:www.scripta.io) and  [shoobox.io](http:www.shoobox.io). This will also set the stage for a better editor on these sites with a javascript frontend.

**Comment by Mogztter** [comment]
Hi @jxxcarlson ,
I'm going to try to compile Asciidoctor Latex to JavaScript. Could you please create a release of asciidoctor-latex on GitHub (so I can easily download a version of asciidoctor-latex ?)

**Comment by jxxcarlson** [comment]
Thank you very much Guillaume.  I just made a first release at

	https://github.com/asciidoctor/asciidoctor-latex/releases/tag/0.1 <https://github.com/asciidoctor/asciidoctor-latex/releases/tag/0.1>

Jim (@jxxcarlson)
