### ISSUE TITLE
attrs.map lookup is undefined.

### ISSUE THREAD

**Issue by MikeBull94** [asciidoctor/asciidoctor.js#193]
Hi,

I am trying to add the Chrome Inline Macro extension as shown in [this post](https://github.com/asciidoctor/asciidoctor.js/issues/76#issuecomment-65512581), but am encountering the following build error:

```
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'text' of undefined
```

On the following line:

```javascript
var text = attrs.map['text'];
```

where the value of `attrs` is:

```
{"text"=>"Extensions"}
```

---

Am I missing something? I'm not sure what this `map` function is meant to do but it is returning undefined, thus forcing the array lookup immediately after it to throw this error.

Thanks.

**Comment by Mogztter** [comment]
Hello @MikeBull94 , this post is outdated with the latest version of Opal.
`attrs` is an Hash object and `map` method has been renamed in recent Opal version: https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.3

You should replace `map` with `$fetch` to retrieve the `text` attribute.
Let me know if this is working.

**Comment by MikeBull94** [comment]
Using `attrs.$fetch('text')` worked, thanks very much.
