### ISSUE TITLE
Doesn't render include::file.adoc[]

### ISSUE THREAD

**Issue by bguiz** [asciidoctor/asciidoctor.js#197]
The ruby version renders included files, however this JS version doesn't, it fails silently and simply outputs an empty string.

```asciidoc
include::foo.adoc[]

include::bar.adoc[]
```

**Comment by Mogztter** [comment]
Hello @bguiz 

Could you please post the code you're using to render this document and describe the environment where you code is running (Browser, Node...) ?

We do have a test on this feature, see https://github.com/asciidoctor/asciidoctor.js/blob/master/spec/share/common-specs.js#L148-L153

Hope this helps :smile:

**Comment by bguiz** [comment]
Using NodeJs 4.4.7, where `foo.adoc` and `bar.adoc` are in the same folder as this script, and the current working directory.

```
'use strict';

const fs = require('fs');
const path = require('path');

const asciidoctor = require('asciidoctor.js')();
const opal = asciidoctor.Opal;

const useExtensions = true;
const processor = asciidoctor.Asciidoctor(useExtensions);

let content = `= Woo

Woo

include::foo.adoc[]

include::bar.adoc[]

`;

const options = opal.hash({
  doctype: 'inline',
  attributes: ['showtitle'],
});
var html = processor.$convert(content, options);
console.log(html);

```

foo.adoc is:

```
== Foo

foo

```

and bar.adoc is similar

**Comment by bguiz** [comment]
... looking at the test case you pointed to, I think the options are probably the cause:

```
{base_dir: testOptions.baseDir, 'safe': 'safe'}
```

**Comment by Mogztter** [comment]
> ... looking at the test case you pointed to, I think the options are probably the cause:

Indeed, the include directive is disabled when Asciidoctor is run in secure mode. To learn more about secure mode, refer to the section [Running Asciidoctor Securely](http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely).

Also I don't know if the include directive is working with `inline` document type.
If this is not working with the option `{'safe': 'safe' }`, could you try without `doctype: inline` or `doctype: article` ?
http://asciidoctor.org/docs/user-manual/#document-types

**Comment by bguiz** [comment]
Yeah, I wasn't sure about these options, just got them from the main README for this repo.

Perhaps highlight all of the options required in the JS version that aren't necessary when running the ruby version?

**Comment by Mogztter** [comment]
The `inline` document type is the "Hello world" of Asciidoctor. Basically you just want to render a single paragraph. When working on a real document that's almost never the case. You are right, I think I should highlight this in the README.

Is this working now ? Do you had to change the document type from `inline` to `article` (or remove the document type since `article` is the default)

**Comment by mojavelinux** [comment]
> I don't know if the include directive is working with inline document type.

It is. Of course, the effective content still has to be a single paragraph as required by the inline doctype.

**Comment by bguiz** [comment]
Thanks for the suggestions. I have got it working now with my trivial example.

**Comment by bguiz** [comment]
My more complex things does not work though, see https://github.com/asciidoctor/asciidoctor.js/issues/198

**Comment by Mogztter** [comment]
Cool :+1: 
I replied to your second issue :)
