### ISSUE TITLE
Provide a simple extension point to compile custom extensions/libraries

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#200]
The idea is to provide an easy way for the users to compile custom Asciidoctor extensions/librairies written in Ruby to JavaScript.

This should be as simple as:

 1.Clone the asciidoctor.js repository
 2.Copy your extension/library into the `custom-extensions` directory
 3.Add this line to `custom-build.js`

``` javascript
opalCompiler.compile('custom-extensions/my-extension', 'build/awesome-inline-macro.js', 'awesome-inline-macro');
```

 4.Run `npm run build`

We could maybe go a step further and use a `json` configuration file.
.custom-build-configuration.json

``` json
{
  "custom-extensions": [{
    "directory": "my-extension",
    "name": "awesome-inline-macro"
  }]
}
```

We could also provide a npm task to build only the custom extensions:

```
npm run custom-build 
```

This should work fine when the library does not have runtime dependency. If the library do have runtime dependencies we currently need to download them from GitHub.

**Comment by mojavelinux** [comment]
I really like this idea!

**Comment by Mogztter** [comment]
I'm closing this issue, the focus is now on writing extension in JavaScript.
