### ISSUE TITLE
Output file is ".html"

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor.js#212]
When we use as input a directory path to call the function `processor.$convert('./examples"', options);`, then the html file generated within the output directory is named `.html` file without any prefix.

Of course, if the source directory contains several adoc files, then the result are always inserted within the file `.html`

**Comment by mojavelinux** [comment]
There are two things to point out here. First, the convert method is only for converting a string that contains AsciiDoc. You need to use the convert_file method any time you are converting a file. That brings me to my second point. The processor only accepts a single file as input. It does not support a glob expression. You need to wrap the call in a loop that finds the files and passes them each to  convert_file in turn.

You need something like the following:

```js
var glob = require("glob")

var options = ...;

glob("examples/*.adoc", function (err, files) {
  files.each(function(file) {
    processor.$convert(file, options);
  });
})
```
