### ISSUE TITLE
Karma & jasmine are very difficult to debug

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/asciidoctor.js#222]
Why don't we use nodejs tape as Testing framework instead of Karma/Jasmine. That should simplify how we debug the tests case as configuring  Karma/Jasmine is not so easy ?

**Comment by Mogztter** [comment]
I do not have a strong opinion on Node.js testing framework so I'm willing to switch from Karma/Jasmine to Tape.

Could you please provide a sample or create a pull request to show how this will improve/simplify tests in practice ?
Please note that we need to test on different environments: browser (Phantom.js), Node.js, Nashorn, CommonJS...

**Comment by cmoulliard** [comment]
Here is a tape example : https://github.com/bucharest-gold/litoria/blob/master/test/asciidoctor-test.js#L93-L113

Tape is a node module, so you can of course test the nodejs code. But it can be extended using tape-run to browserify the tests (https://github.com/juliangruber/tape-run).
There is also a test runner client called prova that we could use to test our tape code running at the client side - https://www.npmjs.com/package/prova (Safari, Chrome, Phantomjs)

**Comment by Mogztter** [comment]
I'm trying Mocha, I will also try Tape :wink:

**Comment by Mogztter** [comment]
Puppeteer makes it very easy to run tests in a browser, so I'm willing to drop Karma and just use Puppeteer. When [Slimer.js](https://slimerjs.org/) will be a bit more stable we could also run the tests suite against Firefox headless.

https://medium.com/@ankit_m/ui-testing-with-puppeteer-and-mocha-part-1-getting-started-b141b2f9e21

@oncletom Do you have an opinion ?

**Comment by oncletom** [comment]
I have not used Jasmine for a while for the same reasons.
mocha is easy to use — jest does not create global variables.

I guess the smallest step would be to [plug headless chrome with karma](https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai).

The plain mocha and puppeteer looks elegant though—async/await seems to have been designed for this kind of use case.

**Comment by Mogztter** [comment]
> I guess the smallest step would be to plug headless chrome with karma.

Yep that's what we have now :wink: 
While it's working, Karma is a "full blown solution" and I don't think we need it anymore. As you said the plain Mocha + Puppeteer looks elegant and in my opinion it will also be way easier to debug.

**Comment by Mogztter** [comment]
We should probably do the following:

* Unit tests
   * Node.js : mocha + chai (Node.js specific tests + shared tests)
   * Browser : mocha + chai + puppeteer (Browser specific tests + shared tests)
   * Nashorn : java + jjs (Nashorn specific tests)

* Integration tests (browser)
  * AMD (System.js, RequireJS, etc)
  * Browserify
  * Webpack

Currently we are mixing both because we are using Browserify or Webpack to create a test distribution.
