### ISSUE TITLE
Extensions module should be included in asciidoctor-core.js

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#226]
Docbook5, Docbook45 and Extensions are included by default in Asciidoctor Ruby. I think we should follow the same rule.

I believe those modules are relatively small compared to the rest of the code and will not affect performance.
- `asciidoctor-core.js` should include core (with extensions API)
- `asciidoctor.js` should include core + Opal
- Docbook5 and Docbook45 converters should be moved to a separated module/repository.

This could make Asciidoctor.js easier to use, see https://github.com/asciidoctor/asciidoctor.js/issues/225

**Comment by Mogztter** [comment]
@mojavelinux I agree! I will create an "asciidoctor-docbook" repository to move DocBook converters to a separate module. 

How do you want to handle the different versions of DocBook ? Two separate modules ?

```
npm install asciidoctor-docbook5
npm install asciidoctor-docbook45
```

**Comment by mojavelinux** [comment]
You went a bit further than I was thinking by proposing another repository, but if that makes it easier to consume as a UMD module, then I say :+1: 

If you decide to take the separate repository route, one repository will do as the two converters are basically just different variants.

**Comment by Mogztter** [comment]
> If you decide to take the separate repository route, one repository will do as the two converters are basically just different variants.

If we do that, that mean we will consume the converters as follows:

```javascript
var docbook5 = require('asciidoctor-docbook/5');
var docbook45 = require('asciidoctor-docbook/45');
```

or:

```javascript
var docbook5 = require('asciidoctor-docbook').5;
var docbook45 = require('asciidoctor-docbook').45;
```

because one repository means one module and only one name `asciidoctor-docbook` (as far as I know).

**Comment by mojavelinux** [comment]
To be honest, I think we should just drop DocBook 4.5. The only reason that even exists in core is because we needed it to prove compatibility. But no one uses DocBook 4.5 anymore. (And DocBook 5 is the default).

Granted, we might have a need for versions in the future, so I'm not saying we should drop the idea of versions. But the way I would do it is to mirror the backend names:

```js
var docbook5 = require('asciidoctor-docbook5');
```

we should also alias as just "docbook"

```js
var docbook = require('asciidoctor-docbook');
```

**Comment by Mogztter** [comment]
DocBook is now available as a dedicated Node module: https://github.com/mogztter/asciidoctor-docbook.js and extensions module is now part of "asciidoctor-core.js".

I'm closing this issue 😊
