### ISSUE TITLE
Extract reusable build modules to their own repository

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#229]
* [ ] Download dependencies, files...
* [x] Opal compiler
* [x] Log
* [x] Uglify (based on Google Closure Compiler)
* [x] FS (concat, mkdirs, untar, recursive delete...)
* [x] JDK download

This should significantly reduce the size of `builder.js`.

**Comment by mojavelinux** [comment]
I like it!

I'm curious, what's the origin of the word bestikk?

**Comment by Mogztter** [comment]
Bestikk is Norwegian for Cutlery.
I kinda like the idea of a set of "simple" tools and Bestikk sounds great :wink:

**Comment by mojavelinux** [comment]
I love it!
