### ISSUE TITLE
Problem with Russian Win7

### ISSUE THREAD

**Issue by Johnsik** [asciidoctor/asciidoctor.js#23]
When I try to open any AsciiDoc in Chrome I see:

```
Error:

TypeError : Cannot call method 'join' of null
```

The problem is in file opal.js:9392 and asciidoctor.js:2740  - the regular expression doesn`t include cyrillic symbols.

The line crush when try parse time zone written in Russian.

I think issue https://github.com/asciidoctor/asciidoctor-chrome-editor/issues/1 caused by the same way.

**Comment by mojavelinux** [comment]
For the record, here's an example:

```
Чт июл  7 08:06:41 МСК 2016
```

In order to reproduce, the JavaScript implementation has to produce this result when calling `new Date().toString()` since the conversion happens in the internals of the Time class.

**Comment by mojavelinux** [comment]
Opal should probably use `toLocaleDateString()` instead of `toString()` so that it gets a consistent result to parse. After all, this is all internal state.

**Comment by mojavelinux** [comment]
Actually, that turns out to be not all that reliable. Whatever the solution, I think Opal should not be assuming that toString() is going to be in the en-US locale.
