### ISSUE TITLE
Improvements about nil for Asciidoctor.js

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#234]
When we convert Ruby code to JS code, nil is represented as an object that constructed from `$NilClass`.

We can check whether an object is **nil** like `object["$nil?"]`. Can we create an alias to comply with the following usage: `object.isNil()` or `object.$isNil()` ? I think using dot notation is clear than the bracket notation, but **?** is not an allowed character for JS names.

Also, if an object is `nil`, calling its `toString` function produces "$$id class apply" like text. You can see it at Jade templates in asciidoctor-reveal.js package.

For example;

Converting this `"== Hello _Rahman_"` produces the following HTML output:

```
<section>
  <section id="_hello_em_class_id_apply_call_rahman_em" data-transition="" data-transition-speed="" data-background="" data-background-size="" data-background-repeat="" data-background-transition="">
    <h2>Hello <em class="$$id apply call">Rahman</em></h2>
  </section>
</section>
```

If we override nil's `toString` to return just `null`, I think it will be better for Asciidoctor.js.

What do you think for these suggestions?

Thanks.

**Comment by mojavelinux** [comment]
I agree a nicer API is needed. I don't think toString() should return null though because then it wouldn't be a string. I think it should return either empty string (as it is in Ruby, preferred) or the string null (as it is in Java).

**Comment by rahmanusta** [comment]
I agree with empty string, it will be good at least for jade templates

**Comment by Mogztter** [comment]
Hi @rahmanusta 

You could use `Opal.nil`, see https://github.com/asciidoctor/asciidoctor.js/blob/76964f479996b740c37e09e0f4b655dce0a927d0/src/asciidoctor-core-api.js#L76

As you can see I return `undefined` here and there but I could return an empty string if you think this is more appropriate.

I will try to override the `toString` function on `Opal.nil`.

**Comment by Mogztter** [comment]
One idea is to assign `Opal.nil` to empty string: 
```javascript
Opal.nil = '';
```
Unfortunately this is not working because in Ruby you can call methods on nil class (for instance `empty?`):

```
    empty?: undefined method `empty?' for nil
        at Opal.defs.TMP_1 [as $new] (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:4853:15)
        at NilClass_alloc.ːmethod_missing (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:3410:54)
        at NilClass_alloc.method_missing_stub [as $empty?] (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:1006:35)
        at $DocBook45Converter.ːdocument_ns_attributes (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:34868:35)
        at $DocBook45Converter.ːdocument (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:34942:53)
        at $DocBook45Converter.ː__send__ (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:3228:21)
        at $DocBook45Converter.ːconvert (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:20546:24)
        at $Document.ːconvert (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:26762:35)
        at module_constructor.ːconvert (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:32086:22)
        at module_constructor.Opal.Asciidoctor.$$class.$$proto.convert (/home/guillaume/workspace/opensource/asciidoctor.js/build/bower.spec.all.js:33361:15)
```

Another idea is to use the wrapper API in the Jade templates. In your example, we could return an empty string if the `role` method returns `Opal.nil`: https://github.com/asciidoctor/asciidoctor.js/blob/76964f479996b740c37e09e0f4b655dce0a927d0/src/asciidoctor-core-api.js#L110

**Comment by mojavelinux** [comment]
I think the right thing to do is add this as a feature of our wrapper API, but keep in mind that there are many such cases. This would allow the template not to have to worry about the details. If the value is a nil object, it should become null.

```jade
div.paragraph(id=node.getId(), class=node.getRole())
```

It seems reasonable to me that we can write the template that way.

**Comment by rahmanusta** [comment]
@mojavelinux @Mogztter It is quite good. I think as a first step we can write an extension file which manipulates some existing functions with their prototypes.

**Comment by mojavelinux** [comment]
@rahmanusta In fact, we've already done that. That's what https://github.com/asciidoctor/asciidoctor.js/pull/180 is all about.

**Comment by rahmanusta** [comment]
@mojavelinux  Yes, it is what I have thought! What is the state of this work @Mogztter ?

**Comment by Mogztter** [comment]
@rahmanusta The first version of the API is merged on master. I didn't spend too much time on improving the return value (when the value is "nil" object) but feel free to do so.
All the code is here: https://github.com/asciidoctor/asciidoctor.js/blob/master/src/asciidoctor-core-api.js

You can find an example here: https://github.com/asciidoctor/asciidoctor.js/blob/master/src/asciidoctor-core-api.js#L76-L78
If the return value is `Opal.nil`, I return "undefined".

**Comment by rahmanusta** [comment]
@Mogztter It is awesome! I would love to test use this wrapper api. So, what do you think amending Asciidoctor Jade templates with the wrapper functions ?

**Comment by mojavelinux** [comment]
Once a release is out, definitely.

**Comment by rahmanusta** [comment]
:+1:

**Comment by Mogztter** [comment]
I've released a pre-version `1.5.5-3`, if you want to do some testing.
@rahmanusta Feel free to open a pull request to improve the wrapper API in order to return "blank" value when it makes sense.

**Comment by rahmanusta** [comment]
Thank you dear @Mogztter

**Comment by Mogztter** [comment]
I did my best to remove Opal.nil from the public API of Asciidoctor.js.
I'm closing this issue but please open a new issue if Opal.nil is still present on the public API.

**Comment by mojavelinux** [comment]
Nice work!
