### ISSUE TITLE
Switch to the latest LTS for Node.js

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#254]
As of 2016-10-18, the latest LTS is v6.
I think we should at least move from 0.12 to v4.

**Comment by mojavelinux** [comment]
Time to move to Yarn too? :trollface:

**Comment by Mogztter** [comment]
I didn't give it a try yet but this should be compatible :pray:

**Comment by mojavelinux** [comment]
I was just trolling ;) It's basically a drop-in replacement. I do recommend using it for development because it's a lot faster.

**Comment by Mogztter** [comment]
We are now building Asciidoctor.js in Travis with Node.js latest 4.x release, latest 6.x release and latest stable release.
