### ISSUE TITLE
Cross reference links anchor confusion

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#278]
Let's say I am currently on a document named `chapter-04/index.adoc#_generated_title_anchor`.

I wrote a cross reference link like this:

```
<<../chapter-02/index.adoc#bar,cross reference label>>
```

The problem is the `href` value is `../chapter-02/index.adoc#_generated_title_anchor#bar`. Double anchor issue 😄 

PS: I noticed this problem from within the Asciidoctor Chrome Extension.

**Comment by Mogztter** [comment]
It's a bug in Asciidoctor Chrome Extension.

**Comment by Mogztter** [comment]
Moved to https://github.com/asciidoctor/asciidoctor-chrome-extension/issues/146
