### ISSUE TITLE
Public API: Adds getRevisionRemark and getRevisionNumber methods

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#298]
* `attributes['revremark']`
 * `attributes['revnumber']`

https://github.com/asciidoctor/asciidoctor/blob/4dbbedea3fb2c4682afac0495a2384c68b5d2507/lib/asciidoctor/parser.rb#L1794-L1811

**Comment by mojavelinux** [comment]
I think we should follow what AsciidoctorJ does and return a RevisionInfo object. See http://static.javadoc.io/org.asciidoctor/asciidoctorj/1.6.0-alpha.3/org/asciidoctor/ast/RevisionInfo.html

**Comment by Mogztter** [comment]
Indeed that's nice... Also we really need to publish a JavaScript API. I'm considering using https://github.com/jsdoc3/jsdoc or https://github.com/documentationjs/documentation

**Comment by mojavelinux** [comment]
I quite like what I see with documentationjs.
