### ISSUE TITLE
Map public APIs needed to write an include processor extension

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#302]
Map the public APIs that are needed to write an include processor extension (similar to what was done for a custom inline macro).

It should be possible to write the following (pseudo-code):

```js
Opal.Asciidoctor.$$scope.Extensions.register(function() {
  var self = this;
  this.includeProcessor(function() {
    self.handles(function(target) {
      return target.endsWith('.adoc');
    });
    self.process(function(doc, reader, targets, attrs) {
      var content = ['line 1', 'line 2'];
      reader.pushInclude(content, target, target, 1, attrs);
      return reader;
    });
  });
});
```

The tricky part is going to be "handles?" since I don't think it's mapped as a method. We might need some sort of wrapper there (or patch core).

**Comment by Mogztter** [comment]
@mojavelinux I think we need to patch core to do the same as `process`: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/extensions.rb#L498 no ?

**Comment by mojavelinux** [comment]
...yes, except I'd rather just fix core ;)

https://github.com/asciidoctor/asciidoctor/pull/2120

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor.js/pull/303

**Comment by hsablonniere** [comment]
I just used it on a project and it works great.

Question, is it bad not to use handle? Is there any perf difference?

**Comment by mojavelinux** [comment]
If you don't use handle, your extension gets every include. If that's what
you intend, then you don't need it. If you only want to handle certain
includes, then you need it.
