### ISSUE TITLE
How to get original source of the block

### ISSUE THREAD

**Issue by podviaznikov** [asciidoctor/asciidoctor.js#307]
Hi,

Just starting using asciidoctor.js.
I found methods to get rendered content and source for the whole document:
`doc.getContent()`, `doc.getSource()`.
However, when I called those methods on the block. I've got an error saying that `.getSource` is not a function. I also tried calling `$source()` but it returned empty string.
Any help?

**Comment by podviaznikov** [comment]
Found the problem myself. I needed to find nested block and ask it for the source.

**Comment by Mogztter** [comment]
Hello @podviaznikov !

> Just starting using asciidoctor.js.

Nice :+1: 
The "wrapper" API is pretty new, so I would be very interested to receive your feedback :wink: 

> Found the problem myself. I needed to find nested block and ask it for the source.

Thanks for sharing the solution.
