### ISSUE TITLE
setAttribute on a block doesn't work for some reason

### ISSUE THREAD

**Issue by podviaznikov** [asciidoctor/asciidoctor.js#308]
When I call `setAttribute('id', 'some-in')` on a block I'm getting and error
```
set_attribute: undefined method `set_attribute' for #<Asciidoctor::Block@596 {context: "quote", content_model: "compound", style: "quote", blocks: 1}>
```

It seems that such method should exist, not exactly sure why I'm getting such an error.

**Comment by mojavelinux** [comment]
The set_attribute method is only defined on Document. It's a special method for setting document-related attributes. The underlying method should be set_attr (which is different, despite the similarity of the name).

**Comment by mojavelinux** [comment]
(In other words, it is mapped incorrectly).

Really set_attribute is an internal method used by the parser and I may change it so that is more clear.

**Comment by podviaznikov** [comment]
Thank you for the explanation and the fix!
