### ISSUE TITLE
Map the API needed to write a tree processor extension

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#319]
Map the APIs needed to write a tree processor extension.

It should be possible to write the following (pseudo-code):

```javascript
Opal.Asciidoctor.$$scope.Extensions.register(function() {
  var self = this;
  this.treeProcessor(function() {
    self.process(function(doc) {
      return doc;
    });
  });
});
```

A treeprocessor can return a replacement document or null to continue using the same document.

**Comment by Mogztter** [comment]
Thanks for tracking the remaining API :wink:

**Comment by Mogztter** [comment]
While working on it, I found a small difference on naming:

```ruby
def treeprocessor # tree_processor ?
def preprocessor # pre_processor ?
def postprocessor # post_processor ?
def include_processor
def docinfo_processor 
def inline_macro # no processor suffix ?
```

Is that intended ?

**Comment by mojavelinux** [comment]
These differences are intentional. When the segment before "processor" is a noun, we use an underscore. For instance, "include" or "docinfo" refer to things. "pre" and "post", on the other hand, are prepositions (and we're sort of treating "tree" as one too*), so no underscore. In other words, you can't process a "pre".

We don't use the "processor" suffix for syntax processors like inline_macro since it's understood that they are introducing syntax and thus responsible for processing it.

\* A case could be made that treeprocessor should be "tree_processor", since "tree" is a noun. I'll probably alias it in core, so let's expose it as "treeProcessor".

**Comment by mojavelinux** [comment]
When I read my own logic, I realize that treeprocessor should clearly be tree_processor. We process the tree just as we process an include.

**Comment by Mogztter** [comment]
It makes sense! Thanks for the clarification :+1:

**Comment by mojavelinux** [comment]
Though, to be honest, you could probably convince yourself either way ;)

**Comment by Mogztter** [comment]
Yes but at the same time, we are processing the "tree" (the AST)
