### ISSUE TITLE
Map the API needed to write a preprocessor extension

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#323]
Map the APIs needed to write a preprocessor extension.

It should be possible to write the following (pseudo-code):
```javascript
asciidoctor.Extensions.register(function() {
  var self = this;
  this.preprocessor(function() {
    self.process(function(doc, reader) {
      var lines = reader.getLines();
      lines.append("IMPORTANT: This is a draft");
      return reader;
    });
  });
});
```

**Comment by Mogztter** [comment]
@mojavelinux I think the documentation is wrong on `preprocessor`: https://github.com/asciidoctor/asciidoctor/blob/48120dc8d56028268515882e84ac6ca165f76e7e/lib/asciidoctor/extensions.rb#L656

I think the method arguments are `document` and `reader` (not `reader` and `lines) ?

**Comment by mojavelinux** [comment]
Yes, you are correct! That was changed at some point but the documentation is lagging behind.
