### ISSUE TITLE
Map the API needed to write a docinfo processor extension

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#331]
Map the APIs needed to write a docinfo processor extension.

It should be possible to write the following (pseudo-code):

```js
asciidoctor.Extensions.register(function() {
  var self = this;
  this.docinfoProcessor(function() {
    self.atLocation('footer');
    self.process(function(doc) {
      return 'moar footer';
    });
  });
});
```

**Comment by Mogztter** [comment]
The main documentation doesn't mention the Docinfo processor: https://github.com/asciidoctor/asciidoctor/blob/17539b2cdc9b9197648abd0204485d65dc63f266/lib/asciidoctor/extensions.rb#L3-L22

I think we should add a paragraph on Docinfo processor.

**Comment by mojavelinux** [comment]
:+1:

The docinfo processor wasn't in the first wave, and that documentation hasn't been updated since then.
