### ISSUE TITLE
How to create a native extension?

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#337]
Hello there :-)

I am trying to implement asciidoctor/asciidoctor-extensions-lab#77 directly in JavaScript.
I have had a look at #322 but with no much luck.

So far I even struggled to access the Extensions API (which I have spotted via #243 but I struggle to understand how to use it, even by looking at the tests — I always seem to have a slightly different context.

For the record, I have been trying something like this.

```js
const Asciidoctor = require('asciidoctor.js')();

Asciidoctor.$$scope.Extensions.register(...);
```

Otherwise I don't have the `Extensions` member:

```
console.log(Asciidoctor);

[ '$$id',
  '$$proto',
  'constructor',
  '$$is_module',
  '$$class',
  '$$super',
  '$$parent',
  '$$inc',
  '$$dep',
  '$$name',
  '$$scope',
  '$$base_module',
  '$$orig_scope',
  '$$meta',
  'Timings',
  'AbstractNode',
  'AbstractBlock',
  'AttributeList',
  'Block',
  'Callouts',
  'Document',
  'Inline',
  'List',
  'ListItem',
  'Parser',
  'PathResolver',
  'Reader',
  'PreprocessorReader',
  'Section',
  'Stylesheets',
  'Table' ]
```

Any pointer to do so?

**Comment by oncletom** [comment]
For the record, I get this error when I try to register an extension:

```
/Users/oncletom/workspace/nodebook/node_modules/opal-runtime/src/opal.js:1418
    var func = recv['$' + mid];
                   ^

TypeError: Cannot read property '$register' of undefined
    at TopScope.Opal.block_send (/Users/oncletom/workspace/nodebook/node_modules/opal-runtime/src/opal.js:1418:20)
    at module_constructor.Extensions.register (/Users/oncletom/workspace/nodebook/node_modules/asciidoctor.js/dist/asciidoctor.js:33856:8)
    at Object.<anonymous> (/Users/oncletom/workspace/nodebook/bin/build.js:21:37)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

**Comment by Mogztter** [comment]
Hello!

Are you using the latest released version or master ?

**Comment by oncletom** [comment]
I tried only with npm releases `1.5.5-5` and `1.5.6-preview.1`. Shall I try with master instead?

**Comment by Mogztter** [comment]
No I was just asking because Opal made some changes.
If you are using master you should use: `var Extensions = Opal.const_get_qualified(Opal.Asciidoctor, 'Extensions');` (see [asciidoctor-extensions-api.js#L49](https://github.com/asciidoctor/asciidoctor.js/blob/99fb3716be91d85f21e6acdd91f1c00d6ee8aec2/src/asciidoctor-extensions-api.js#L49))

I will try to reproduce this issue with `1.5.6-preview.1`.

**Comment by Mogztter** [comment]
```
$ node -v
v6.10.1

$ npm -v
node -3.10.10
```

```
$ npm init -y
$ npm install asciidoctor.js@1.5.6-preview.1 --save
```

.test.js
```javascript
const Asciidoctor = require('asciidoctor.js')();

const registry = Asciidoctor.$$scope.Extensions.$build_registry();
const opts = {'extensions_registry': registry};
registry.block(function () {
  var self = this;
  self.named('shout');
  self.onContext('paragraph');
  self.process(function (parent, reader) {
    var lines = reader.$lines().map(function (l) { return l.toUpperCase(); });
    return self.createBlock(parent, 'paragraph', lines);
  });
});


const text = `[shout]\
\nSay it loud.\
\nSay it proud.`;

const html = Asciidoctor.convert(text, opts);
console.log(html);
```

```
$ node test.js
<div class="paragraph">
<p>SAY IT LOUD.
SAY IT PROUD.</p>
</div>
```

In the next preview version, the syntax will be a bit better:

```javascript
// const registry = Asciidoctor.$$scope.Extensions.$build_registry();
const registry = Asciidoctor.Extensions.create();
```

**Comment by oncletom** [comment]
Ah, I needed to create a registry!

I guess it is mandatory to it prior to register any extension. Is there any reason not to create it by default on asciidoctor.js side?

**Comment by Mogztter** [comment]
> Ah, I needed to create a registry! Thank you so much for coining this :)
I guess it is mandatory to it prior to register any extension.

It's not mandatory to create a registry, you can register an extension (globally) as follows:

```js
const Asciidoctor = require('asciidoctor.js')();
Asciidoctor.$$scope.Extensions.register(function () {
  this.block(function () {
    var self = this;
    self.named('shout');
    self.onContext('paragraph');
    self.process(function (parent, reader) {
      var lines = reader.$lines().map(function (l) { return l.toUpperCase(); });
      return self.createBlock(parent, 'paragraph', lines);
    });
  });
});


const text = `[shout]\
\nSay it loud.\
\nSay it proud.`;

const html = Asciidoctor.convert(text);
console.log(html);
```

>  Is there any reason not to create it by default on asciidoctor.js side?

Because you can create multiple registries. For instance:

```js
const Asciidoctor = require('asciidoctor.js')();

const registryA = Asciidoctor.$$scope.Extensions.$build_registry();
const registryB = Asciidoctor.$$scope.Extensions.$build_registry();

registryA.block(function () {
  var self = this;
  self.named('shout');
  self.onContext('paragraph');
  self.process(function (parent, reader) {
    var lines = reader.$lines().map(function (l) { return l.toUpperCase(); });
    return self.createBlock(parent, 'paragraph', lines);
  });
});

registryB.block(function () {
  var self = this;
  self.named('shout');
  self.onContext('paragraph');
  self.process(function (parent, reader) {
    var lines = reader.$lines().map(function (l) { return l.replace(/\.$/g, ' !!!'); });
    return self.createBlock(parent, 'paragraph', lines);
  });
});

const text = `[shout]\
\nSay it loud.\
\nSay it proud.`;

console.log(Asciidoctor.convert(text, {'extensions_registry': registryA}));
console.log('');
console.log(Asciidoctor.convert(text, {'extensions_registry': registryB}));
```

In the example above, you have two registries:
 * `registryA`
 * `registryB`

Both registry have a block extension registered.
The first block extension is registered in the `registryA` and will transform the text to uppercase.. The other one is registered in the `registryB` and will replace `.` by ` !!!` .

```
$ node test.js
<div class="paragraph">
<p>SAY IT LOUD.
SAY IT PROUD.</p>
</div>

<div class="paragraph">
<p>Say it loud !!!
Say it proud !!!</p>
</div>
````

**Comment by mojavelinux** [comment]
Great explanation! I think you could definitely migrate this straight to the Asciidoctor.js manual.

**Comment by mojavelinux** [comment]
> extensions_registry

Keep in mind that in 1.5.6, this option name is changing to extension_registry.

**Comment by Mogztter** [comment]
Thanks!
I was thinking the same, my lack of documentation is disturbing... 😱

We also need to map the `reader.$lines()` function to remove the last $ function in this example.

**Comment by Mogztter** [comment]
@oncletom Let me know if you need help to write this extension. If you want I can publish another preview version so you can benefit from the latest improvement on the API ?

**Comment by oncletom** [comment]
@Mogztter I am happy to try. I am doing stuff a bit blindly at the moment because I don't know much about Opal conversion, and how to read which methods are available to transform data.

**Comment by mojavelinux** [comment]
>  I am doing stuff a bit blindly at the moment because I don't know much about Opal conversion, and how to read which methods are available to transform data.

That's basically the goal of the current API mapping effort. We're identifying and documenting the API that you can use to write extensions directly in JavaScript.

You should definitely keep this tab open: http://asciidoctor.github.io/asciidoctor.js/master/

**Comment by oncletom** [comment]
Thanks, very helpful!

Working on something here: https://github.com/oncletom/asciidoctor-extension-interactive-runner
