### ISSUE TITLE
Cannot install from github:asciidoctor/asciidoctor.js#master

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#338]
I have an issue when I install the module with a dependency like this:

```js
{
  "devDependencies": {
    "asciidoctor.js": "asciidoctor/asciidoctor.js#master"
  }
}
```

The follow error happens:

```
$ npm install
npm ERR! code 128
npm ERR! Command failed: /usr/local/bin/git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'extensions-lab' in .gitmodules
```

**Comment by Mogztter** [comment]
The git submodule was removed by this commit: https://github.com/asciidoctor/asciidoctor.js/commit/99fb3716be91d85f21e6acdd91f1c00d6ee8aec2

I'm not sure why `npm install` is executing `/usr/local/bin/git submodule update -q --init --recursive`. Could you please run the command in verbose mode ?

**Comment by oncletom** [comment]
@Mogztter yes, that's what I originally thought. It happens I can reproduce this issue manually:

```bash
$ git clone git@github.com:asciidoctor/asciidoctor.js.git
cd asciidoctor.js
git submodule update -q --init --recursive
```

Maybe the folder should be removed with `git rm -f extensions-lab`?
GitHub interface also reports the folder as a submodule.

<img width="473" alt="screen shot 2017-06-12 at 23 20 44" src="https://user-images.githubusercontent.com/138627/27055764-c8e06ac0-4fc5-11e7-9faf-fbb4a3209e35.png">
