### ISSUE TITLE
How to detect external links in Asciidoc

### ISSUE THREAD

**Issue by salfuve** [asciidoctor/asciidoctor.js#347]
Hi everyone, is it possible to get all the links contained inside of an asciidoc?I don't want to converse an asciidoc into HTML file, i want to iterate above the AST and get all the external links.¿Is this possible?
Thank you all in advance :)

**Comment by mojavelinux** [comment]
If you enable the `catalog_assets` option, then convert the document, the collection of links will be available via the `:links` key of the catalog.

Here's how it's done in Ruby (as of Asciidoctor 1.5.6).

```ruby
doc = Asciidoctor.load_file 'sample.adoc', safe: :safe, catalog_assets: true
doc.convert
puts doc.catalog[:links]
```

This is not a particularly sophisticated mechanism. But that's where we are today.

**Comment by Mogztter** [comment]
In JavaScript (with this pull request #349)

```js
var doc = asciidoctor.load('link:index.html[Docs]', {'safe': 'safe', 'catalog_assets': true});
doc.convert();
var links = doc.getCatalog().links; // [ 'index.html' ]
```

**Comment by gaurav-nelson** [comment]
On a similar note, how to extract all internal references ? both xrefs to same document and xrefs to other documents in directory?

**Comment by mojavelinux** [comment]
References to other documents are not currently cataloged.

**Comment by gaurav-nelson** [comment]
Thanks for the clarification @mojavelinux

**Comment by gaurav-nelson** [comment]
Thanks @mojavelinux What about xref's to the same document?

**Comment by mojavelinux** [comment]
Those are available via document.catalog.xrefs.

**Comment by mojavelinux** [comment]
Correction. document.catalog.refs.

We're also proposing to expose this as an API method like document.getRefs() or something equivalent.

**Comment by Mogztter** [comment]
@gaurav-nelson @salfuve Just so you know a new API is coming in Asciidoctor.js 1.5.8:

It should look like:

```js
const doc = asciidoctor.load(input, {'safe': 'safe', 'catalog_assets': true})
doc.convert()

const links = doc.getLinks()
const ids = doc.getIds()
const refs = doc.getRefs()
const images = doc.getImages()
const footnotes = doc.getFootnotes()
const indexTerms = doc.getIndexTerms()
````

**Comment by gaurav-nelson** [comment]
Thanks @Mogztter This will surely make link extraction easy.

**Comment by Mogztter** [comment]
The API is now available in Asciidoctor.js 1.5.9! Enjoy :stuck_out_tongue_winking_eye:

**Comment by gaurav-nelson** [comment]
@Mogztter 

I'm wondering if with the latest API updates `2.2.0` can we extract `xrefs`? 
>[how to extract all internal references ? both xrefs to same document and xrefs to other documents in directory?](https://github.com/asciidoctor/asciidoctor.js/issues/347#issuecomment-417303499)
