### ISSUE TITLE
Is it possible to add numbered ids to each paragraph

### ISSUE THREAD

**Issue by podviaznikov** [asciidoctor/asciidoctor.js#348]
I have id for each section. But paragraphs have only class=`paragraph`.
Can I have autoincremented ids for paragraphs too?

**Comment by Mogztter** [comment]
Hello @podviaznikov, I'm pretty sure you could do it with an extension but I don't know if there's a built-in feature... @mojavelinux must know ?

Could you please give me more context, what are you trying to achieve ? Maybe there's another way to solve your issue 😊

**Comment by podviaznikov** [comment]
@Mogztter good point about context. I was just thinking that it's nice to have anchor tags for headers of sections. E.x. on github you can link to the section of readme files.
I was thinking about having something similar on my blog but not only for sections but for the whole paragraphs. So I can send a link to specific paragraph in a blog.

**Comment by mojavelinux** [comment]
Although an often requested feature, this is not currently something core supports out of the box. You can assign IDs to paragraphs using a Treeprocessor. If there's a specific paragraph you want to link to, you can add an anchor to the paragraph:

```
[#p1]
This paragraph will be addressable via the URL fragment p1.
```

or at the start of the text.

```
[[p1]]This paragraph will be addressable via the URL fragment p1.
```

You can also make this dynamic using:

```
[#p{counter:p}]
This paragraph will be addressable via the URL fragment p1.

[#p{counter:p}]
This paragraph will be addressable via the URL fragment p2.
```

or

```
[[p{counter:p}]]This paragraph will be addressable via the URL fragment p1.

[[p{counter:p}]]This paragraph will be addressable via the URL fragment p2.
```

For details about counters, see http://asciidoctor.org/docs/user-manual/#counters.

**Comment by podviaznikov** [comment]
@mojavelinux thanks for the detailed response.

Is there a documentation/example on how to make custom Treeprocessor?
I only found https://github.com/asciidoctor/asciidoctor.js/blob/2257d2e5abe8d2fcab784f7986c2f2dc4893bc6c/spec/share/extensions/love-tree-processor.js so far.

I'd like to see bigger example on how to include this custom processort with asciidotor.js code

**Comment by mojavelinux** [comment]
Here's what we have so far:

https://github.com/asciidoctor/asciidoctor.js/blob/master/manual.adoc#how-to-register-an-extension-

There's also an open issue about writing extensions in general: https://github.com/asciidoctor/asciidoctor.org/issues/347

The extensions in Asciidoctor.js are very new, so we're actually still in the process of getting them all working.

**Comment by podviaznikov** [comment]
@mojavelinux have another question. Somehow I can't call `$register` function from your example in the code that runs in the browser.
```
var ad = new Asciidoctor()
ad.$register(function () {
  this.block(function () {
    var self = this;
    self.named('shout');
    self.onContext('paragraph');
    self.process(function (parent, reader) {
      var lines = reader.getLines().map(function (l) { return l.toUpperCase(); });
      return self.createBlock(parent, 'paragraph', lines);
    });
  });
});```
And I'm getting
```
bundle.js:23102 Uncaught 
$NoMethodError {name: "register", message: "undefined method `register' for Asciidoctor", args: Array(1), stack: "register: undefined method `register' for Asciidoctor"}```

I think I'm running the latest version, so not really sure how to call `register`

**Comment by Mogztter** [comment]
@podviaznikov `register` function is defined on `Asciidoctor.Extensions` object.
The following should work with the latest version:

```js
var ad = new Asciidoctor();
ad.Extensions.register(function () {
  this.block(function () {
    var self = this;
    self.named('shout');
    self.onContext('paragraph');
    self.process(function (parent, reader) {
      var lines = reader.getLines().map(function (l) { return l.toUpperCase(); });
      return self.createBlock(parent, 'paragraph', lines);
    });
  });
});
```

And I think you can also call `register` on the global object rather than on the instance:
```js
Asciidoctor.Extensions.register(function () {
  // ...
});
```
I've updated the [user manual](https://github.com/asciidoctor/asciidoctor.js/blob/master/manual.adoc#how-to-register-an-extension-).

 * Source: [asciidoctor-extensions-api.js](https://github.com/asciidoctor/asciidoctor.js/blob/8cb2a75a0426dd7f4509d6e812d849ba528f3784/src/asciidoctor-extensions-api.js#L52)
* API: http://asciidoctor.github.io/asciidoctor.js/master/#extensions

**Comment by Mogztter** [comment]
@podviaznikov Did you get this working ? I would be happy to receive feedback on how to improve the API and/or the documentation ;)

**Comment by podviaznikov** [comment]
@Mogztter no, I wasn't able to make it work after spending some time.

Here is what I've got:

```
      var asciidoctor = Asciidoctor()
      asciidoctor.Extensions.register(function () {
        this.treeProcessor(function () {
          var self = this
          self.process(function (doc) {
            var blocks = doc.getBlocks()
            for(var i=0;i<blocks.length;i++){
              blocks[i].setAttribute('id', 'p'+i)
            }
            return doc
          })
        })
      })
```
I don't think I was able to set id for each paragraph. I've abandoned this task 1 week ago, but looking at it again.

**Comment by Mogztter** [comment]
Your code should run fine but I think you need to set the node id (not an attribute named "id").
In other you should update the following line.

Before:
```js
blocks[i].setAttribute('id', 'p'+i)
```

After:
```js
blocks[i].id = 'p'+i
```

Though we should probably add a setter for the node id on the API.

**Comment by Mogztter** [comment]
Let me know if it's working :wink:

**Comment by podviaznikov** [comment]
@Mogztter yeah, that worked. Thank you! I knew it was something simple like that. I think it was the second time I was confused with setting attributes API.
