### ISSUE TITLE
Drop PhantomJS support and add support for Headless Chrome 

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#350]

**Comment by oncletom** [comment]
You mean, for the testing/development stack?

**Comment by Mogztter** [comment]
Yes but since Opal is also dropping the support for PhantomJS, we should also drop the support for the runtime.
To be honest I don't think anyone is using Asciidoctor.js in PhantomJS ?

**Comment by oncletom** [comment]
It's a weird use case but I guess it's safe to use the excuse of following Opal move and to advertise it.

**Comment by mojavelinux** [comment]
We used PhantomJS because we needed some way to check whether this was going to work in a browser without having to do manual testing (or launching a browser). Now that we have headless Chrome, we can be absolutely sure. Thus, there's no reason to keep PhantomJS around anymore. PhantomJS was a means to an end.

**Comment by mojavelinux** [comment]
And to clarify, there is no one true JavaScript, so we needed to try it in as many places as possible. PhantomJS helped us uncover those inconsistencies...but I think headless Chrome will go even further. (Headless Firefox would also be great to explore).

**Comment by Mogztter** [comment]
I'm now using Chrome Headless in the testing/development stack: https://github.com/asciidoctor/asciidoctor.js/commit/cf945a1f52dd185fce7bb6a1d9e810ab50e05cc3

I still need to refactor the benchmark script to run against Chrome Headless (with Puppetter).

Currently I'm having some issues with the include macro. In the benchmark script, we are using the following include macro `include::build/benchmark/userguide.adoc[]` but since Chrome Headless is secured and sandboxed we may need to add `--disable-web-security` and `--no-sandbox` options (see https://github.com/opal/opal/commit/4a46cfe858ccb687731b86515021a69e6a7e226b).

Though I don't think it's a good idea and we might instead read the content of the `userguide.adoc` before running the benchmark.

@mojavelinux What do you think ?

**Comment by mojavelinux** [comment]
Honestly, I don't mind either option. I don't really see a risk of disabling security/sandbox for a benchmark. But I also don't see why we have to use include for the benchmark, so if we can get rid of it, why not.

**Comment by Mogztter** [comment]
And done!

**Comment by mojavelinux** [comment]
:beers:
