### ISSUE TITLE
Update Asciidoctor DocBook.js dependency

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#351]
EOL has been renamed to LF in Asciidoctor core master (1.5.6): https://github.com/asciidoctor/asciidoctor/pull/2289

```
EOL: uninitialized constant Asciidoctor::Converter::DocBook5Converter::EOL
```

Repository: https://github.com/mogztter/asciidoctor-docbook.js

**Comment by mojavelinux** [comment]
Shoot. I didn't think about this dependency. I thought all uses were internal. Should I restore an alias for backward compatibility?

**Comment by mojavelinux** [comment]
Also, do you want to move that repo to the asciidoctor org?

**Comment by Mogztter** [comment]
I thought about it and I think we should add an alias if we want to able to compile both master and 1.5.5 with the same dependency on Asciidoctor DocBook.js.

But it raises one question, since docbook converter and template converter are tightly coupled with asciidoctor, maybe it's not a good idea to have them in a separated repository ?
Having said that, I do like the fact that these modules are not bundled in Asciidoctor.js...

**Comment by mojavelinux** [comment]
I think it's good that you've separated out the DocBook converters. I'll reintroduce the constant as an alias for the DocBook converter so you can build it again either version of core.

There is some amount of coupling between the converters and the rest of core, but I'm trying to keep them as isolated as I can.

**Comment by mojavelinux** [comment]
Restored.

**Comment by Mogztter** [comment]
Perfect, thanks

**Comment by Mogztter** [comment]
Do you think it's possible to trigger a build on asciidoctor.js each time a commit lands on the master branch of asciidoctor ?

**Comment by mojavelinux** [comment]
We could sent a webhook. It seems we have to use this:

https://docs.travis-ci.com/user/triggering-builds

The question is whether auth is required. And whether we have to do it from a script or whether there's a way to configure it in the GitHub repo settings.

If we figure this out, it will be very useful for other projects in the org too.

**Comment by Mogztter** [comment]
Using a webhook seems the way to go: https://hiddentao.com/archives/2016/08/29/triggering-travis-ci-build-from-another-projects-build/

You will need to define the Asciidoctor.js token `TRAVIS_ASCIIDOCTOR_JS_API_TOKEN` on the Asciidoctor build:

```js
got.post(`https://api.travis-ci.org/repo/asciidoctor%2Fasciidoctor.js/requests`, {
  headers: {
    "Content-Type": "application/json",
    "Accept": "application/json",
    "Travis-API-Version": "3",
    "Authorization": `token ${process.env.TRAVIS_ASCIIDOCTOR_JS_API_TOKEN}`,
  },
  body: JSON.stringify({
    request: {
      message: `Trigger build at asciidoctor/asciidoctor.js by asciidoctor commit: ${gitCommitHash}`,
      branch: 'source',
    },    
  }),
})
.then(() => {
  console.log("Triggered build of asciidoctor/asciidoctor.js");
})
.catch((err) => {
  console.error(err);
  process.exit(-1);
});
```

We just need to write the same thing in a Rake task: https://github.com/asciidoctor/asciidoctor/blob/master/Rakefile

**Comment by mojavelinux** [comment]
And it's in place! Thanks for making this happen!

**Comment by Mogztter** [comment]
> Also, do you want to move that repo to the asciidoctor org?

@mojavelinux Sure 😄

**Comment by Mogztter** [comment]
Done: https://github.com/mogztter/asciidoctor-docbook.js

```
npm i asciidoctor.js asciidoctor-docbook.js@1.5.6-rc1
```
