### ISSUE TITLE
Don't modify Object.prototype and other built-ins!

### ISSUE THREAD

**Issue by jods4** [asciidoctor/asciidoctor.js#352]
Asciidoctor.js does modify some built-in objects.
For example it adds `$require` on `Object.prototype`.

That's a terrible idea that breaks all kind of things.
For example, it's impossible to load `nodegit` after Asciidoctor.
(Because `nodegit` uses `promisify-node`, which iterates exports to promisify everything, which finds `$require`, which then goes down the rabbit hole and eventually crashes on some objects).

Admittedly, `promisify-node` could be better and probably ignore non-own properties. 
But modifying `Object` is still a terrible idea and guaranteed to run into trouble with one library or another.

You should avoid it.
Installing your properties as non-enumerable would be a first layer of safety that hides them from `for..in`, which would at least avoid some crashes (including the one with `promisify-node`).

**Comment by Mogztter** [comment]
Hello @jods4,

Asciidoctor.js is produced by Opal, a Ruby to JavaScript source-to-source compiler. There must be a good reason why Opal is forced to modify `Object.prototype` (or not :wink: ).

You should definitely open an issue on the [Opal repository](https://github.com/opal/opal).

**Comment by jods4** [comment]
Thanks for the answer!
I opened opal/opal#1684 if you want to follow.
