### ISSUE TITLE
Publish a 1.5.6-preview.3 because of v prefix on 1.5.6-preview.2

### ISSUE THREAD

**Issue by jkschneider** [asciidoctor/asciidoctor.js#355]
The current latest package in NPM breaks yarn installs. The mistake has already been fixed with 93651255c3e9858a5e8679f12f5a2743d71cfa0d, but perhaps we could do a preview.3 release so this stops being an issue?

**Comment by mojavelinux** [comment]
Just FYI, I'll be releasing 1.5.6.1 of core this evening most likely. You could wait for that, though since the version number got messed up, doing another preview might be a good idea just to test that everything is working correctly so the Asciidoctor.js 1.5.6 release is clean.

**Comment by jkschneider** [comment]
Even better!

**Comment by Mogztter** [comment]
@jkschneider Just a quick follow up, I'm currently working on making the release process less error prone. Once this task is done, I will do a `1.5.6-preview.3` (based on Asciidoctor core 1.5.6) to ensure that everything is working fine, then a `1.5.6.1` (based on Asciidoctor core 1.5.6.1)

**Comment by mojavelinux** [comment]
I would like to see Asciidoctor.js 1.5.6 based on 1.5.6.1 core. It would be strange to have 1.5.6.1 and not 1.5.6 (and I would discourage having an Asciidoctor.js 1.5.6 release based on 1.5.6 core).

Aside from that, :+1:. I'm about to cut the 1.5.6.1 release. All the scripts are ready.

**Comment by Mogztter** [comment]
Agreed 😉

**Comment by jkschneider** [comment]
@Mogztter Don't feel rushed. I'd rather vendor the package for now and have it done when you're comfortable :)

**Comment by Mogztter** [comment]
Version [1.5.6.preview-3](https://github.com/asciidoctor/asciidoctor.js/releases/tag/v1.5.6-preview.3) published!

@jkschneider  Let me know if this release is OK.

**Comment by jkschneider** [comment]
Looks good to me!

![image](https://user-images.githubusercontent.com/1697736/28529885-64c94f9a-7057-11e7-8683-15d64e1ba3e9.png)

**Comment by Mogztter** [comment]
Perfect, thanks for your report :wink:
