### ISSUE TITLE
Travis published the release after building Asciidoctor.js against 1.5.5

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#361]
Log: https://travis-ci.org/asciidoctor/asciidoctor.js/jobs/256901706

In other words, Travis is only building Asciidoctor.js against the first environment variable defined in `.travis.yml`:

```yml
env:
- ASCIIDOCTOR_CORE_VERSION=v1.5.5
- ASCIIDOCTOR_CORE_VERSION=v1.5.6.1
- ASCIIDOCTOR_CORE_VERSION=master
```

If an error occurred when `ASCIIDOCTOR_CORE_VERSION=v1.5.6.1` or when `ASCIIDOCTOR_CORE_VERSION=master`, the release will still be published.

**Comment by mojavelinux** [comment]
I have a somewhat similar problem in core. When I push the tag at the same time as the commit in master that the tag was based on, Travis runs two builds, one of which fails. It still successfully pushes out the release to RubyGems, but the project gets marked as failing.

How do you get Travis to skip the build for the commit in master that corresponds to the tag?

* https://travis-ci.org/asciidoctor/asciidoctor/builds/256710351
* https://travis-ci.org/asciidoctor/asciidoctor/builds/256710329

This seems like a problem Travis should have solved.

**Comment by mojavelinux** [comment]
Aha, I think I know the problem. I'm cloning with a depth of 1. But Travis goes a git checkout using a specific commit. If two refs get pushed at the same time, that leads to one of the builds not being able to find its refs. I can solve this by upping the depth to 2. That at least explains the failure.

I still don't know how to avoid the double build.

**Comment by Mogztter** [comment]
I think we should check that `${ASCIIDOCTOR_CORE_VERSION} == ${ASCIIDOCTOR_CORE_VERSION_PUBLISH}` to trigger the release:

https://github.com/asciidoctor/asciidoctor.js/blob/d669c1d4c795cdf0a19b27b7bba58983f006b7cb/.travis.yml#L35

Arguably we could also build master first so a release only happens if the build against master is green and the build against the targeted version is also green.
