### ISSUE TITLE
Only build against upstream when build is triggered

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#363]
I think it makes sense for the build triggered by a change to core to only run against upstream. There's really no reason to run the entries in the matrix against a released version of Asciidoctor since they shouldn't change (a nightly build would catch problems there).

The reason I bring this up is because we are now hitting limits of number of builds that can run simultaneously in an org, and it's causing things to get backed up. If the build could run quicker, it would not spend as much time blocking other builds in the queue.

The challenge is how to pass this information. I think we can inject an extra environment variable into the build using https://docs.travis-ci.com/user/triggering-builds/#Customizing-the-build-configuration, which would then allow us to put conditions on the builds in the matrix. But that's as far as I've gotten in thinking about it.

**Comment by mojavelinux** [comment]
The same thing goes for AsciidoctorJ and Asciidoctor Diagram. cc: @robertpanzer @pepijnve

**Comment by mojavelinux** [comment]
This was implemented by PR #366 and merged as 531a0b92f8d62eb13000908581708ec3958e5acb.

**Comment by mojavelinux** [comment]
The configuration is defined in the file .travis-upstream-only.yml.

**Comment by mojavelinux** [comment]
If you'd like, we could rename to .travis-upstream-trigger.yml. Just let me know so I can update core accordingly.

**Comment by Mogztter** [comment]
This is nice, well done!
At first I didn't quite understand how the `.travis-upstream-only.yml` was used but I just had a look at the Rakefile: https://github.com/asciidoctor/asciidoctor/blob/53ae3927c5c36209f9dc34154c9c465b8cd85c30/Rakefile#L161

**Comment by mojavelinux** [comment]
Yep, it's the whole config value in the payload.
