### ISSUE TITLE
Map Processor.create_image_block method in the API

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#364]
https://github.com/asciidoctor/asciidoctor/blob/fba0af1262269a133579fe9ef1b04fb87c76c477/lib/asciidoctor/extensions.rb#L150-L152

**Comment by mojavelinux** [comment]
As you can see, we are still missing a few of these helper methods in core too. We should probably just take this one method at a time, as you've done here.

**Comment by Mogztter** [comment]
See #442
