### ISSUE TITLE
Processor fails to convert document containing a certain sequence of characters

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#367]
Asciidoctor.js 1.5.6-preview.3 fails to convert the following document:

```
const asciidoctor = require('asciidoctor')()
asciidoctor.convert('* a\n* \u2028b')
```

The line separator character (`\u2028`) is causing Asciidoctor.js to go into an infinite loop. Asciidoctor Ruby converts this document without issue.

**Comment by mojavelinux** [comment]
Curiously, it works if you take away the first list item. So it only happens if it's not the first list item.

**Comment by mojavelinux** [comment]
This may have something to do with the fact that \s in JavaScript matches more whitespace characters than Ruby. One of those is `\u2028`. Another is `\u2029`.

**Comment by mojavelinux** [comment]
Oddly enough, this was not a problem with 1.5.6-preview.2.

**Comment by mojavelinux** [comment]
I've discovered the problem. It's a bad interaction between the block type detection and the actual matcher. The problem is that in JavaScript regexp, `.` does not match `\u2028` or `\u2029`. So the parser see that the line starts with a `*` and therefore must be a list item. But when it goes to match it with the regexp, it fails. So it tries again, and again, and again, and again...

Replacing `.` with `[\s\S]` in the regular expressions for list items would solve this problem.

The block type detection was added after 1.5.6-preview.2. But the regular expression never matched, so it used to fail silently and now it just goes into an infinite loop.

To avoid having to release another version of course, we could just patch the regular expression on the JavaScript side.

**Comment by mojavelinux** [comment]
Asciidoctor.js 1.5.6-preview.2 was dropping the line containing the line separator char.

**Comment by mojavelinux** [comment]
@Mogztter I'd like to make a decision on this and then do a preview.4 release since technically preview.3 runs the risk of an infinite loop.

I do think we should try to identify all the scenarios that were causing an infinite loop so that we can be sure we don't have a regression.

**Comment by mojavelinux** [comment]
Here's the logic. Any line that AnyListRx matches has to be parsed as a list item or else it goes into an infinite loop. The solution is to either fix the regular expression for list items to match all characters (after the marker) or to add the check back in that advances the reader when this mismatch happens.

**Comment by Mogztter** [comment]
>The problem is that in JavaScript regexp, . does not match \u2028 or \u2029. 

Are you sure about that ?
I'm trying to reproduce this issue in Opal:

```ruby
SampleRx = /^-.*/

if SampleRx.match? '- <U+2028><U+2028>Hello world'
  p 'SampleRx match'
end
```

I get the same result in MRI and Opal:

```
$ ruby sample.rb
"SampleRx match"
```
```
$ bundle exec opal -- sample.rb
"SampleRx match"
```

**Comment by mojavelinux** [comment]
Here's the test case of the difference between Ruby and JavaScript.

Ruby:

```
p /./.match? "\u2028"
true
```

JavaScript:

```
console.log(/./.test("\u2028"))
false
```

That's the low-level of course. It's possible that Opal is processing that regular expression to make them match. And it's possible that for some reason that patch is not working in Asciidoctor.js. That's what I need to look at next.

**Comment by mojavelinux** [comment]
Here's the result I get with opal-repl 0.11.0.rc1:

```
p /./ =~ "\u2028"
nil
```

(I tried match? but the method is missing).

I'm not convinced, though, that Opal should mess with the regular expression. I think we have to write the regular expressions specifically for each engine because the intent is not always clear. For example, changing `.` to `[\S\s]` actually changes the behavior (it implicitly enables a multi-line match).

**Comment by mojavelinux** [comment]
What version of Opal are you using?

**Comment by Mogztter** [comment]
I'm using Opal master branch. I will try with the integration branch.

> I'm not convinced, though, that Opal should mess with the regular expression.

In my opinion, Opal should ensure that a given Ruby code will produce identical result when run against MRI (Ruby) or Opal (JavaScript). Otherwise a promise is broken 😔

Having said that, I agree that regular expressions are not an easy task 🤔

**Comment by iliabylich** [comment]
@Mogztter It's not that easy without self-written regex parser. Regular expressions in Ruby and JS are similar, but they also have so many differences. Opal supports only the "intersection" of Ruby and JS regex features. For example, we don't support named captures, extended regex mode, positive- and negative- lookahead and -behind. 

Blind replacing of `.` to something covering all unicode characters doesn't look like a generic solution.

As I know, MRI starting from 2.4.0 (or 2.3.0, not 100% sure) uses [oniguruma](https://github.com/kkos/oniguruma) as a regex engine. Probably it's possible to build something similar in Opal (or even compile it with emscripten, who knows 😄 ). But building own regex parser means a huge performance degradation.

If your regexes are something completely different from JS regexes then probably the best solution would be something like a custom AST rewriter. (I think you already have something similar in this repo, I've seen some functions that "replace" the code compiled by Opal.)

**Comment by Mogztter** [comment]
@iliabylich Thanks for the explanation. I wonder if one day we will all use the same regular expression engine 🤔 

> Blind replacing of . to something covering all unicode characters doesn't look like a generic solution.

Could you please elaborate this point ?  

> If your regexes are something completely different from JS regexes then probably the best solution would be something like a custom AST rewriter. (I think you already have something similar in this repo, I've seen some functions that "replace" the code compiled by Opal.)

While I agree, `.` is a pretty common symbol in regex and it's a pity that the following Ruby code will produce different result:

```ruby
p /./ =~ "\u2028"
```

> As I know, MRI starting from 2.4.0 (or 2.3.0, not 100% sure) uses oniguruma as a regex engine. Probably it's possible to build something similar in Opal (or even compile it with emscripten, who knows 😄 ). But building own regex parser means a huge performance degradation.

What about [XRegExp](http://xregexp.com/engine) ? Do you know if the implementation is closer to the Ruby's regex engine ?

**Comment by iliabylich** [comment]
@Mogztter XRegexp seems to support this case - http://jsfiddle.net/1onwot7L/. 

> Could you please elaborate this point ?

I mean, it's not as simple as a single `replace` function, since we need to take care about stuff like escaping. Named captures also support `.` character inside:
``` ruby
2.3.1 :008 > /\$(?<dol.lars>\d+)\.(?<cents>\d+)/.match("$3.67")[:"dol.lars"]
 => "3"
```

Minified version of XRegexp is ~80kb, while Opal 0.11 is ~400kb.

I remember some old conversations about integration XRegexp into Opal:
a. Adding XRegexp as a default regex engine means increasing size of the source code. 20% is a lot.
b. Adding XRegexp as a "secondary" optional regex engine means having two implementations in Opal's corelib (one for native regexes and one for XRegexp), two test suites (for all runners) and two sets of filters for them (I'm sure XRegexp can pass much more examples from rubyspec test suite that Opal's implementation).

Both solutions are definitely doable, but both of them are going to hurt Opal. So we have to choose between the size of the source code and development process (XRegexp is fast enough, it compiles regexes to native, so there's a difference only in regex parsing/compilation process). And I think that's a decision that we don't want to make 😄 .

Btw, there are 7 issues/PRs in Opal repo mentioning XRegexp 😄 . You can find the latest conversation in https://github.com/opal/opal/pull/591.

**Comment by Mogztter** [comment]
> I mean, it's not as simple as a single replace function, since we need to take care about stuff like escaping. Named captures also support . character inside:

As you said, Opal does not support named captures, so we "only" have to take care of escaping ?

> Both solutions are definitely doable, but both of them are going to hurt Opal.

Indeed, not an easy choice 🤔 
Maybe using XRegexp as a regex engine is not an ideal solution, but instead will you be open to integrate some features of XRegexp ? For instance we could support a [Unicode regex](https://github.com/slevithan/xregexp/blob/a661cd3ebbaf9950f947c5b92039d7c565ce8a5b/src/addons/unicode-properties.js#L91) ?

In the meantime, I think @mojavelinux's solution to write specific regular expression for each regex engine is a good idea 😉

**Comment by Mogztter** [comment]
@mojavelinux How to you want to proceed on this issue. I wanted to release a 1.5.6 "final" version but I think we need to take care of this issue first. Do you want to fix the RegExp in core and then release a 1.5.6.2 or do you want to 🐒 patch the RegExp in the Asciidoctor.js build ?
If I read you correctly, we need to replace `.` by `[\S \t\u2028\u2029]` in the `AnyListRx` ?

https://github.com/asciidoctor/asciidoctor/blob/d71378ca5bb72d92e9beb2512ee7e2a4b8abe8a1/lib/asciidoctor.rb#L672

**Comment by mojavelinux** [comment]
I plan to get back to this issue this week.

**Comment by Mogztter** [comment]
Awesome, it's one of the last standing issue before 1.5.6 "final" ✨✨✨

**Comment by mojavelinux** [comment]
I did some more thinking on this. What I realized is that all instances of `.*` and `.+` are problematic. (There are other permutations, but we mostly have these two).

According the JavaScript spec, `.` is supposed to match all characters except new lines. However, what we've found is that `.` misses line and paragraph separators. But we can write the expression in another way that would match the definition.

If we replace `.` with `[^\n]`, then we fit the definition of `.` while at the same time including the two characters it currently misses. We know that the only new lines in the source are line feed characters since the processor always cleans the source first.

I've updated the PR to replace `.*` and `.+` with `[^\n]*` and `[^\n]+` in all single-line regex constants, respectively. I also added tests for all scenarios that involve lists which this change affects. I also added a test for a line separator in the block title. That should be enough to notify us if an assumption were to change.

(While this change could be done in core, I'd really prefer not to make that change atm. If I do, it will be something like `C_ALL_LINE`. If I do decide to make that change, this patch would simply get ignored.)

**Comment by mojavelinux** [comment]
Technically, we could use `[\S\s]` instead of `[^\n]` since we know these are single-line expressions. But I can't think of any cases where we aren't able to assume that the newline is a line feed. (In fact, we already use `\n` in some instances in core to match the newline.

**Comment by Mogztter** [comment]
> Technically, we could use [\S\s] instead of [^\n] since we know these are single-line expressions. But I can't think of any cases where we aren't able to assume that the newline is a line feed. (In fact, we already use \n in some instances in core to match the newline.

Maybe it's just me but I prefer `[\S\s]` over `[^\n]`. I don't like the negation and I think `\S\s` is easier to understand (ie. the purpose is clear) but you are the expert of the Regex!
In my opinion we should go with the "safest" choice even if it's a bit harder to understand at first :wink:
