### ISSUE TITLE
Non-Latin internal cross references doesn't work 

### ISSUE THREAD

**Issue by RazrFalcon** [asciidoctor/asciidoctor.js#378]
This is the same issue as in https://github.com/asciidoctor/asciidoctor-pdf/issues/833

I can reproduce the bug using:
- `asciidoc-preview` 2.10.2 in Atom editor
- Asciidoctor.js Live Preview 1.5.5.100 in Chromium

**Comment by mojavelinux** [comment]
This problem is resolved by Asciidoctor.js 1.5.6 (final still pending). Once that's in place, all the tools based on it should work correctly.

**Comment by mojavelinux** [comment]
I don't think this issue should remain open in this repository as this is not a problem with Asciidoctor.js anymore.

**Comment by RazrFalcon** [comment]
I confirm. This is works fine in Asciidoctor 1.5.6.1 with ruby 2.5.0p0 and in Asciidoctor PDF 1.5.0.alpha.16.

**Comment by mojavelinux** [comment]
\o/

**Comment by Mogztter** [comment]
Perfect, then we should close this issue ? @RazrFalcon Is that your final answer ? :dollar:

**Comment by RazrFalcon** [comment]
Yes.

**Comment by Mogztter** [comment]
:beers:
