### ISSUE TITLE
xmlhttprequest should be a dev dependency

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#386]
To be honest I don't remember why we have this dependency as "runtime".
Since we are using this library only in tests, I think we could safely remove this "runtime" dependency (and add it as a "dev" dependency)

@anthonny Do you remember the context in which this library was/is used ? 🤔

**Comment by mojavelinux** [comment]
This was needed before we introduced the cross platform IO module. It's definitely not needed at runtime anymore as Node now uses direct file access for reading files such as includes.

**Comment by Mogztter** [comment]
@mojavelinux Thanks for the context :wink: 

I want to open a pull request on https://github.com/yarnpkg/website to render README in AsciiDoc format.
Currently they are using `marked` to do client-side rendering of README written in Markdown. This library does not have any dependency and that's why I want to reduce the number of dependencies of Asciidoctor.js to the bare minimum (ie. just `opal-runtime`).

The main issue is that the readme format is not indexed, so we need to somehow detect the format before choosing the `Markdown` React component or the `AsciiDoc` React component.

In order to get this pull request approved and merged I think we will need to make our case! I'm trying to gather numbers about the popularity of the AsciiDoc format: https://bigquery.cloud.google.com/results/dev-order-135720:bquijob_365ec21_15efba8644f

What do you think ?

**Comment by Mogztter** [comment]
**Before**
![readme-md](https://user-images.githubusercontent.com/333276/31316240-01e8018c-ac2a-11e7-9e60-7a24b6385988.png)

**After**
![readme-ad](https://user-images.githubusercontent.com/333276/31316241-030aa128-ac2a-11e7-9c2f-a73f3976cd95.png)
