### ISSUE TITLE
Try to read file with 'file://' protocol if it fails in the first place

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#389]
The idea is to get a consistent behavior between Chrome and Firefox when using the live preview extension. Currently Chrome will resolve the following local path:

* `include::/path/to/file.adoc[]`
* `include::file.adoc[]`
* `include::file:///path/to/file.adoc[]`

**Note:** In this examples, the `base_dir` is `file://path/to`

On the other hand, Firefox will only resolve the following local path: `include::file:///path/to/file.adoc[]`

To avoid side effect, we should only try to read file with `file://` protocol if the following are true:

* include didn't work in the first place
* we are running in a browser environment (Firefox): `JAVASCRIPT_PLATFORM  === 'browser'`
* we are using XMLHttpRequest: `JAVASCRIPT_IO_MODULE === 'xmlhttprequest'`
* protocol is not defined in the include URI
* the document `base_dir` used the `file://` protocol

https://github.com/asciidoctor/asciidoctor-chrome-extension/pull/151#issue-243463061

**Comment by mojavelinux** [comment]
I think we should just fix it in the first place. See https://github.com/asciidoctor/asciidoctor/issues/2602.

**Comment by Mogztter** [comment]
Resolved by https://github.com/asciidoctor/asciidoctor.js/pull/441
