### ISSUE TITLE
ReferenceError: "plaform" is not defined with Nashorn

### ISSUE THREAD

**Issue by jmini** [asciidoctor/asciidoctor.js#390]
I have read on twitter that asciidoctor.js should run on Nashorn (the JVM javascript engine).

I have downloaded the ` asciidoctor.js.dist.zip` from GitHub and I have created a simple `main.js` with this content:

```
load('asciidoctor.js');
var asciidoctor = Asciidoctor();
var content = "http://asciidoctor.org[*Asciidoctor*] " +
    "running on http://opalrb.org[_Opal_] " +
    "brings AsciiDoc to Node.js!";
var html = asciidoctor.convert(content);
print(html);
```

When I run 
```
jjs main.js
```

I get this error:
```
asciidoctor.js:21955 ReferenceError: "plaform" is not defined
```

When I use `load(asciidoctor.min.js)` produces the error:
```
asciidoctor.min.js:634 ReferenceError: "plaform" is not defined
```

The fix is simple, because of the typo:

```
/* Generated by Opal 0.11.0.rc1 */
Opal.modules["asciidoctor/js/opal_ext"] = function(Opal) {
  //...
    else if (isNashorn) {
      platform = plaform || 'java';
      engine = engine || 'nashorn';
    }
  //…
}
```

Should be:

```
/* Generated by Opal 0.11.0.rc1 */
Opal.modules["asciidoctor/js/opal_ext"] = function(Opal) {
  //...
    else if (isNashorn) {
      platform = platform || 'java';
      engine = engine || 'nashorn';
    }
  //…
}
```

This is a small typo: `plaform` instead of `platform`.

Any idea where this error should be reported and fixed? I guess this is in the Opal project.

I checked and it is wrong with asciidoctor.js `v1.5.5` and in `v1.5.6-preview.4`

**Comment by Mogztter** [comment]
Yes Asciidoctor.js should work on Nashorn. Actually we do have tests but obviously they are not automated enough.

Thanks for the detailed report, if you want you can fix this issue here: 

https://github.com/asciidoctor/asciidoctor.js/blob/d88a54fe1399e8dcb4670a67052816c042b59ef9/lib/asciidoctor/js/opal_ext.rb#L37

**Comment by jmini** [comment]
I will propose a simple pull request.

**Comment by jmini** [comment]
Pull request: https://github.com/asciidoctor/asciidoctor.js/pull/391

**Comment by Mogztter** [comment]
Awesome, thanks @jmini :ok_hand: 
Next step is to run the Nashorn tests suite on Travis: #392 

Apart from this bug, is the Nashorn integration working for you ?
