### ISSUE TITLE
Include content from a URI is not working on Node.js

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#394]
To be able to include content from a URI we need to provide an implementation of the `open` method (see https://ruby-doc.org/stdlib-2.1.2/libdoc/open-uri/rdoc/OpenURI.html).

This implementation should be synchronous so unfortunately we cannot use Node's `http` or `https` modules.

As an alternative we could use the [`xmlhttprequest` library](https://yarnpkg.com/en/package/xmlhttprequest).
To be able to do a synchronous request, this library spawns another Node process and write the result of the request into a temporary file: https://github.com/driverdan/node-XMLHttpRequest/blob/86ff70effb6dd529b34650242b9e3b1f0b8b6e86/lib/XMLHttpRequest.js#L473-L521
Note that this library does not have any dependency. 

Another alternative could be to use the [`sync-request` library](https://yarnpkg.com/en/package/sync-request).
This library tries to use the netcat command `nc`. If the command does not exist, it spawns another Node process but does not write the result into a temporary file, instead the result of the request is sent to `stdout`.
While I think this approach is slightly better, this library does have 5 dependencies: https://github.com/ForbesLindesay/sync-request/blob/208a7db39a96efb1f54cff5ac8b683021ea1fe76/package.json#L16-L20

I'm open to suggestions! :wink: 

//cc @hsablonniere @oncletom @anthonny

**Comment by mojavelinux** [comment]
See upstream issue: https://github.com/opal/opal/issues/1721

**Comment by mojavelinux** [comment]
> This implementation should be synchronous so unfortunately we cannot use Node's http or https modules.

We could if we require the user to be running Asciidoctor.js in an async context and we use the await keyword. Perhaps we can have multiple implementations from which the user can choose. But we can start with just using XMLHttpRequest to get something working, then graduate.

**Comment by mojavelinux** [comment]
> This library tries to use the netcat command nc. If the command does not exist, it spawns another Node process but does not write the result into a temporary file, instead the result of the request is sent to stdout.

I don't really like the sound of a separate process.

**Comment by mojavelinux** [comment]
Let's move forward with xmlhttprequest. But I think if we add a runtime dependency, then we really need to avoid bundling (#396).

**Comment by oncletom** [comment]
> This implementation should be synchronous

Is there any reason for that? Could it return a Promise and be consumed as is by other modules depending on Ruby `URI` module?

**Comment by Mogztter** [comment]
> I don't really like the sound of a separate process.

To be honest, `xmlhttprequest` does spawn another Node process. I think there's no way around 😐

> We could if we require the user to be running Asciidoctor.js in an async context and we use the await keyword. Perhaps we can have multiple implementations from which the user can choose. But we can start with just using XMLHttpRequest to get something working, then graduate.

Yes that's a good idea!

**Comment by Mogztter** [comment]
Resolved by https://github.com/asciidoctor/asciidoctor.js/pull/384 and https://github.com/opal/opal/pull/1735

**Comment by mojavelinux** [comment]
Oh, wow! I wasn't expecting this one. Bonus!

**Comment by mojavelinux** [comment]
I still think the right way to handle remote includes over a large number of documents in the node way (using a custom include processor) is to fetch the content first, put it into an in-memory cache, then invoke Asciidoctor in the async callback. The custom include processor then retrieves the contents of a remote include synchronously from the in-memory cache. But that obviously requires a controlled environment. Thus, the approach implemented here is the right way to go for the built-in include processor.

**Comment by Mogztter** [comment]
>  still think the right way to handle remote includes over a large number of documents in the Node way (using a custom include processor) is to fetch the content first, put it into an in-memory cache, then invoke Asciidoctor in an async callback. The custom include processor then retrieves the contents of a remote include synchronously from the in-memory cache (so Asciidoctor.js doesn't have to be async). 

Indeed, it will be way more efficient.

> Thus, the approach implemented here is the right way to go for the built-in include processor.

Yep! :smiley:

**Comment by mojavelinux** [comment]
I discovered that the remote include works fine on Node (assuming the allow-uri-read attribute is set) if the include does not use lines or tags. If the include uses either lines or tags, it still attempts to read the URI as a local file. This is caused by the fact that we use the Kernel.open method to read a URI when there are lines and tags (so we can go line-by-line) rather than IO.read. I think we should open a separate issue for this because it's more specific than this one.
