### ISSUE TITLE
WARNING: dropping line containing reference to missing attribute

### ISSUE THREAD

**Issue by dominic-simplan** [asciidoctor/asciidoctor.js#397]
Hi,
I am using asciidoctor-cli.js in order to convert an asciidoc file to an html.
The conversion is working fine with the ruby asciidoctor version.
However, with asciidoctor-cli.js, it doesn't seem to process my attribute:

```
$ asciidoctorjs -b html5 -a data-uri -D dist/docs src/main/resources/docs/help_de.adoc
asciidoctor: WARNING: dropping line containing reference to missing attribute: language
asciidoctor: WARNING: dropping line containing reference to missing attribute: language
...
```

Ant these are the first few lines of my asciidoc document:
```
= Bedienungsanleitung
:imagesdir: images
:nofooter:
:figure-caption!:
:toc: left
:toclevels: 3
:toc-title: Inhaltsverzeichnis
:toc-placement!:
:sectanchors:
:numbered:
:language: de

toc::[]

== Startbildschirm
image::{language}/startView.png[Startansicht,700]
== Übersicht
image::{language}/projectView.png[]
```

Any idea why the attribute is ignored when using asciidoctor-cli.js?

**Comment by Mogztter** [comment]
Hello @dominic-simplan 

Thanks for the detailed report, I will try to reproduce the issue as soon as possible.
What version of `asciidoctor-cli.js` are you using ?

**Comment by dominic-simplan** [comment]
Hi,
I am using the latest version of asciidoctor-cli.js (v1.5.5-beta.3) and also the latest version of asciidoctor.js (1.5.5).

**Comment by mojavelinux** [comment]
This works fine for me using those same versions.

It's important to note, however, that `language` is a reserved built-in attribute. You should use `lang` instead.

**Comment by mojavelinux** [comment]
I did have to set `-B` so the images were resolved relative to the document. That's a difference from asciidoctor. I don't think the docdir is being set correctly or something.

**Comment by dominic-simplan** [comment]
@mojavelinux 

1. If I have the document title above the attributes, I am getting the warnings above. 
2. If I have the document title above the attributes and add an empty line between the title and the attributes, I am not getting warnings, but the document title is not formatted in the resulting document
3. If I move the document title below the attributes, the warnings disappears and the output is correct. 

So it is not allowed to put the document title above the attributes? All three cases are working for me with the ruby version of asciidoctor, though...

Also thank you for the hint with the `-B` parameter, using this and the third option above, I am able to create the html file!

**Comment by mojavelinux** [comment]
> So it is not allowed to put the document title above the attributes?

That should not be the case.

It seems to me like something is different about your environment. Are you able to test with a fresh install or a different computer? Can you provide a project that demonstrates this problem?

**Comment by dominic-simplan** [comment]
Hi,
I've tested it on another computer and indeed the issue didn't occur. I was also able to identify the problem: On the second PC the adoc file was encoded in UTF-8, while on the first PC it was encoded as UTF-8 with BOM. Changing the encoding on the first PC to UTF-8 solves the above mentioned issue.

**Comment by mojavelinux** [comment]
@Mogztter do we have a test in Asciidoctor.js that tests a file with a BOM? You can find reference tests in the Asciidoctor core test suite.

**Comment by Mogztter** [comment]
@mojavelinux Nope we do not, I will check Asciidoctor core test suite

**Comment by mojavelinux** [comment]
Just the first line. A BOM is a sequence of invisible characters at the very start of a file. It could be that the function we're using to detect it is not working as expected in Opal.

See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/helpers.rb#L67-L78

**Comment by Mogztter** [comment]
I believe this issue is now resolved (or my test case is wrong): https://github.com/asciidoctor/asciidoctor.js/pull/505
Ilya did some work on `pack` and `unpack` so maybe that's why this issue is now resolved.

@dominic-simplan could you please try to convert your document using Asciidoctor.js 1.5.6 (and the latest version of Asciidoctor.js CLI) ?
