### ISSUE TITLE
Allow class and class instance to be registered as extensions

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#399]
Currently, the extension registry makes an assumption that all extensions are defined using the block / proc form. However, all the extension registration methods also accept a class and class instance. The argument should only be wrapped in toBlock if it is in fact a block. Otherwise, it should be passed through as is.

Here's an example:

```js
const Asciidoctor = require('asciidoctor.js')()
const Opal = global.Opal

const IncludeProcessor = (() => {
  const superclass = Asciidoctor.$$const.Extensions.$$const.IncludeProcessor
  const scope = Opal.klass(Opal.Object, superclass, 'MyIncludeProcessor', function () {})

  Opal.defn(scope, '$initialize', function initialize () {
    Opal.send(this, Opal.find_super_dispatcher(this, 'initialize', initialize))
  })

  Opal.defn(scope, '$process', function (doc, reader, target, attrs) {
    reader.pushInclude(['included content'], target, target, 1, attrs)
  })

  return scope
})()

const registry = Asciidoctor.Extensions.create()
registry.$include_processor(IncludeProcessor.$new())

Asciidoctor.convert('include::whatever.adoc[]', {
  safe: 'safe',
  extension_registry: registry
})
```

**Comment by mojavelinux** [comment]
The benefit of defining a formal class is that it avoids the overhead of creating a block for call to Asciidoctor.

**Comment by Mogztter** [comment]
I think we need to work on the API to define a formal class because the code is way more complicated.
Apart from that 👍
