### ISSUE TITLE
Map AbstractBlock.remove_sub in the API

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#426]
Ref: https://github.com/asciidoctor/asciidoctor.js/issues/413

Asciidoctor (Ruby) method: https://github.com/asciidoctor/asciidoctor/blob/d91a822fa1589f0d000491a0373efb7b50146755/lib/asciidoctor/abstract_block.rb#L330-L333

**Comment by mojavelinux** [comment]
We might as well do this one for 1.5.6.

**Comment by mojavelinux** [comment]
I mapped all three methods:

* removeSubstitution
* hasSubstitution
* getSubstitutions
