### ISSUE TITLE
Opal.load("nodejs") overrides our custom File constructor

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#436]
We have a custom File constructor (i.e., initialize method) defined lib/asciidoctor/js/opal_ext/file.rb. However, this is being overridden by the call to `Opal.load("nodejs")`. As a result, Opal is now complaining if the binary flag ("b") is passed to File.open (as Asciidoctor core master now does).

There are a few things we need to do here.

(1) Get rid of the warning about the "b" flag. We don't want it. In fact, I don't even think Opal should be warning about the binary flag since openSync reads in binary (as defined by Ruby) by default anyway. It should just remove it so that Node doesn't choke.

(2) Get rid of the custom override code in lib/asciidoctor/js/opal_ext/file.rb as it's not used anyway...at least the node-specific part.

(3) Get rid of asciidoctor/js/opal_ext/node/file.rb since the File.readable? method now seems to be provided by the nodejs module.

**Comment by mojavelinux** [comment]
I submitted a change upstream that takes care of the warning. See https://github.com/opal/opal/pull/1781

**Comment by mojavelinux** [comment]
This problem has been resolved upstream. That means to fix this, all we need to do is a) upgrade to a new integration of opal, b) remove the exception for node in lib/asciidoctor/js/opal_ext/file.rb (since it won't be used) and c) remove asciidoctor/js/opal_ext/node/file.rb.

**Comment by mojavelinux** [comment]
We can start by removing the dead code since technically it's not being used anyway.

**Comment by mojavelinux** [comment]
I think this is resolved now, right?

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor.js/commit/493891dfe1c5b60ad38f0a2165af8eaffe136927
