### ISSUE TITLE
Changes with ``setAttribute`` aren't reflected in output

### ISSUE THREAD

**Issue by danShumway** [asciidoctor/asciidoctor.js#456]
Changes made via ``setAttribute`` don't reflect on the rendered document. As far as I can tell, either the document conversion happens on ``asciidoctor.load``, or calling ``convert`` overrides the new attributes with the values from the content.

I've played around with the internals and it seems to be getting set, it's just that ``$attributes`` doesn't seem to matter when the document is actually rendered. Is this expected behavior?

**Environment:** Node v8.4.0
**AsciiDoctor Version**: 1.5.6-preview.5

**Example Code:** (copy paste into node process to run)
```js
var assert = require('assert');
var asciidoctor = require('asciidoctor.js')();

var content = `
= Example
:idprefix: foo

== header
`;

var doc = asciidoctor.load(content);

doc.setAttribute('idprefix', 'bar');
assert.strictEqual(doc.getAttribute('idprefix'), 'bar'); //Passes

var expected = `<div class="sect1">
<h2 id="barheader">header</h2>
<div class="sectionbody">

</div>
</div>`;

assert.strictEqual(doc.convert(), expected); //Fails, id prefix is still foo
```

**Comment by danShumway** [comment]
Semi-related, I am (separately) working on getting custom template support working for my own website, and when I run that test, it passes.

**Example Code:** (not copy-paste-able)
```js
 suite.test('Passing in *set* attributes', function () {
    var content = '= Title';

    var doc = asciidoctor.load(content, {
        header_footer : true,
        templates : {
            document : function (ctx) {
                return ctx.node.attributes.mycustomattr;
            }
        }
    });

    doc.setAttribute('mycustomattr', 'foo');
    var output = doc.convert();

    assert.strictEqual(output, 'foo', 'Attributes can be set after document has loaded');
});
```

So I was wrong before, it's not that the document is getting pre-rendered, and the attributes *are* getting passed into the templates. But attributes like ``idprefix`` are just ignored for some reason?

**Comment by mojavelinux** [comment]
This is behaving as designed. By the time you load the document, the section IDs have already been computed and thus the `idprefix` already applied. You have to set this attribute before you parse. Otherwise, the assignment has no impact.

```js
var doc = asciidoctor.load(content, { attributes: { idprefix:  'bar' } });
```

**Comment by mojavelinux** [comment]
> Semi-related, I am (separately) working on patching custom template support in for my own website

Would you be willing to join the effort by @Mogztter and @s-leroux, who are already hard at work on first-class template support for Asciidoctor.js?

https://github.com/s-leroux/asciidoctor.js-pug/issues/1

**Comment by mojavelinux** [comment]
You also need to be aware that attributes defined in the header get restored at the start of each phase. This can sometimes produce surprising results if you've changed an attribute via the API. It doesn't apply in this case, but something to be aware of.

See https://github.com/asciidoctor/asciidoctor/blob/bd1c5288dcb6ed2bea61ddbdd3142e470b77fec6/lib/asciidoctor/document.rb#L871-L875

**Comment by danShumway** [comment]
> You have to set this attribute before you parse.

Thanks, I didn't realize that I could pass attributes into ``load``. That'll help a lot with removing boilerplate from my source.

> You also need to be aware that attributes defined in the header get restored at the start of each phase.

Hrm, I'll need to look more into the code to make sure I understand what's happening. My instinct would be that if header attributes get restored it would happen universally; seeing the above code it's not immediately clear to me now why ``idprefix`` _isn't_ getting reverted.

I guess it's probably better practice for me to pass in attribute overrides or additions during ``load`` exclusively. If I need to make attribute changes after I've loaded something, I can always throw the existing doc away and re-load a new one - it seems to be a pretty inexpensive operation.

> Would you be willing to join the effort by @Mogztter and @s-leroux

Eyup, my current implementation is already heavily based off of @s-leroux's code with just a few differences around attachment and API. I plan to get in touch with them and at the very least link the source/tests so they can decide if there's anything of value to take - probably later this week.

**Comment by mojavelinux** [comment]
> I didn't realize that I could pass attributes into load.

I strongly recommend consulting the API docs to learn what other options you can pass.

* https://asciidoctor.org/docs/user-manual/#ruby-api-options

> seeing the above code it's not immediately clear to me now why idprefix isn't getting reverted.

I forgot this was changed. It used to be that the attributes were restored prior to convert. Now they are restored after parse. That was done to allow the attributes to be changed by extension code.

Note: It's possible to defer parsing of the document by passing the `parse` option to the load API.

> my current implementation is already heavily based off of @s-leroux's code with just a few differences around attachment and API.

For open source to succeed, it's really very important that we work together. It's why there aren't a dozen implementations of Asciidoctor to weed through. If we decide we want to go in different directions, fine, then separate projects make sense. But we should at least give working together a chance before that happens. All that to say, we welcome your participation.

**Comment by danShumway** [comment]
Sounds good to me :)

I think this issue can be closed now - I've updated my code locally and re-run tests, and everything's getting set correctly. Thanks for the help!

**Comment by mojavelinux** [comment]
Thanks for following up. Glad to hear it!
