### ISSUE TITLE
Attribute {docname} doesn't work

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor.js#480]
Hello!

My `test.adoc`:

```
= {docname}
:nofooter:
:imagesdir: {docname}_media

image::preview.jpg[]
```

Attribute `{docname}` doesn't work in asciidoctor.js, but works fine in ruby version of asciidoctor.

Please fix this.

Best regards,
Andrey.

**Comment by Mogztter** [comment]
See: https://github.com/asciidoctor/asciidoctor-browser-extension/issues/254
