### ISSUE TITLE
Add position option to extension DSL

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#481]
Each extension can specify a position option, which determines whether the extension is added to the beginning or end of the list for that extension type. The DSL should support this option.

Current:

```js
asciidoctor.Extensions.register(function () {
  this.includeProcessor(function () {
    this.$option('position', '>>')
    this.handles((target) => target.startsWith('https://'))
    this.process((doc, reader, target, attrs) => {
      ...
    })
  })
})
```

Proposed:

```js
asciidoctor.Extensions.register(function () {
  this.includeProcessor(function () {
    this.position('>>')
    this.handles((target) => target.startsWith('https://'))
    this.process((doc, reader, target, attrs) => {
      ...
    })
  })
})
```

The `>>` refers to unshift. I'm open to introducing an alternate keyword here.

**Comment by Mogztter** [comment]
> The >> refers to unshift. I'm open to introducing an alternate keyword here.

Indeed, in my opinion `>>` is not clear in a JavaScript environment.
Alternate keywords:

* `tail` / `head` (Linux)
* `push` / `unshift` (Array JavaScript)
* `end` / `beginning` (`start`, `begin`)
* `before` / `after`

I think `beginning` and `end` are the easiest to understand. As a matter of fact, that's how you first describe this feature:

> which determines whether the extension is added to the beginning or end of the list for that extension type

In the implementation, if I'm reading the code correctly, I can see that the extension position is added to the end of the list on any other values than `>>`:

https://github.com/asciidoctor/asciidoctor/blob/67ae2ca5984dcd5f44a061cf9c63e2ec2450b482/lib/asciidoctor/extensions.rb#L1301-L1305

So `this.position('foo')` is "valid" and will add the extension to the end of the list ?

**Comment by mojavelinux** [comment]
I don't think `>>` makes much sense in the Ruby environment either. I picked it because I was emulating another extension system I had come across.

Of the options you presented, I think I like "head" best. Although it's subtle, beginning has a different meaning to me that implies something to do with time. This is more about list placement. And we often speak of the top of the list as the "head" of the list.

Another option would be a dedicated method name, `this.prepend()`. I'd be okay with that too. (append being the default).

(Since the Ruby side doesn't check, anything that isn't this special value is interpreted as the tail position).

**Comment by Mogztter** [comment]
I like your last proposal. A dedicated method makes sense because we have a default behavior (and we don't really need a  parameter).
You either tell Asciidoctor to pretend your extension or you don't and in this case Asciidoctor will apply the default behavior.

**Comment by mojavelinux** [comment]
Let's do it!

**Comment by mojavelinux** [comment]
In core, I've decided to name this method `prefer` instead of `prepend`. `prepend` is a reserved keyword in Ruby, so we can't use it. But I also think that `prefer` communicates the intent in a less techy way.

See https://github.com/asciidoctor/asciidoctor/issues/2848
