### ISSUE TITLE
Escaping pipe does not seem to work

### ISSUE THREAD

**Issue by mlind** [asciidoctor/asciidoctor.js#482]
Having an example table with escaped pipe ...
```
|===
|`-a\|-b`|Options cannot be used together
|===
```
I get the following picture in the browser:

![asciidoctor-firefox](https://user-images.githubusercontent.com/3583451/39661665-5b9b9e2e-504d-11e8-821c-33e99ede5131.png)

With `asciidoctor-pdf` it works just fine:
[with-asciidoctor.pdf](https://github.com/asciidoctor/asciidoctor.js/files/1976491/with-asciidoctor.pdf)

Firefox version: 59.0.2 (64 bit) - for Ubuntu Canonical
Asciidoctor.js Live Preview version: 1.5.6.100

**Comment by mojavelinux** [comment]
Yep, this is definitely a bug with Asciidoctor.js. Something is getting lost in translation when compiled from Asciidoctor Ruby. I have a feeling it has to do with the regexp pre_match and post_match information in the MatchData.

@Mogztter Let's start with a test and try to figure out where the information is getting dropped.

**Comment by Mogztter** [comment]
I can reproduce this issue with a test:

```js
var html = asciidoctor.convert('|===\n|`-a\\|-b`|Options cannot be used together\n|===');
var columns = (html.match(/<td/g) || []).length;
expect(columns).toBe(2);
```

**Comment by Mogztter** [comment]
Yep I believe it's a bug in Opal :bug:

**Comment by iliabylich** [comment]
`redo` compiles to `.$redo()` in Opal, we don't support it yet.

**Comment by Mogztter** [comment]
@iliabylich `redo` seems to be working fine in a for loop but not in an "unterminated" while loop, see https://github.com/opal/opal/issues/1816. So it seems that Opal has a basic support ?

**Comment by mojavelinux** [comment]
@Mogztter is this something you think we can work around in Asciidoctor.js / Opal, or will I need to use alternate logic in core?

**Comment by Mogztter** [comment]
I might be wrong but I don't think it's gonna be a quick fix in Opal and fixing the issue in Asciidoctor.js won't be easier (quite the opposite).

I think it's better to use an alternative logic in core.

**Comment by mojavelinux** [comment]
The workaround for this is either to use the attribute reference for vbar (e.g., `{vbar}`) or an alternate separator such as a broken vbar.

**Comment by mojavelinux** [comment]
Actually, I think this can be solved rather easily with a patch. In this case, we can simply replace "redo" with "next" and it works in Opal. I can then make that change to core if we decide to keep it that way, but it won't require a new release.

**Comment by fritz-hh** [comment]
Thank you for your work on asciidoctor and antora.
As of today, antora (1.0.1) still relies on the version of asciidoctor.js that has this issue with the "|" character in tables.
Unfortunatelly, I have various tables facing this issue.
Therefore wonder if there is a workaround that would install antora with the fixed version of asciidoctor.js (1.5.7-rc.1)? 
Thank you for your help.

**Comment by mojavelinux** [comment]
I'm feeling this same pain. The upgrade to Asciidoctor.js 1.5.7 will happen in the 1.1.0 release, which I'm aiming to have released this month.

**Comment by fritz-hh** [comment]
Cool, thanks a lot!

**Comment by mojavelinux** [comment]
Just to give an update, the 1.5.7 release missed the Antora 1.1.0 window, but is now scheduled for Antora 1.2.0.
