### ISSUE TITLE
Use Standard JavaScript style

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#493]
https://github.com/standard/standard

**Comment by oncletom** [comment]
Have you considered [prettier](https://prettier.io/)?

One thing I like the most is:

> No need to discuss style in code review

**Comment by Mogztter** [comment]
I heard about it but never used it.
Why not, the style is really close to Standard if we use the following options:
* `--no-semi`
* `--single-quote` 

And a screen width of 120 (or more ?)

@mojavelinux @hsablonniere thoughts ?

**Comment by oncletom** [comment]
Yes totally :-)

The good news is it will _reformat_ the code following these rules instead of just complaining about it.

It is straightforward to use a [pre-commit hook](https://prettier.io/docs/en/precommit.html) to apply it to every project contributor without demanding any IDE setup on any side.

On a side note, I quite see how an [Asciidoc formatter](https://prettier.io/docs/en/plugins.html) would help—well, at least for Asciidoc line length.

**Comment by mojavelinux** [comment]
You can use prettier to enforce standard rules. We do this in Antora.

**Comment by Mogztter** [comment]
@mojavelinux You are using https://github.com/prettier/prettier-eslint right ?

**Comment by mojavelinux** [comment]
> You are using prettier/prettier-eslint right 

Correct. Though I think the set up in the Antora default UI is the better one. See:

* https://gitlab.com/antora/antora-ui-default/blob/master/tasks/format.js
* https://gitlab.com/antora/antora-ui-default/blob/master/tasks/lib/gulp-prettier-eslint.js

I'm still not 100% convinced about it yet. You really lose at lot of control over the formatting, and it doesn't always do the most sensible thing. I love eslint, but I'd rather fix the violations myself. Then you actually learn the rules and start to make them part of your habit. (eslint does have an autofix mode which is less invasive than prettier).

**Comment by mojavelinux** [comment]
I would recommend just applying eslint to the set of files that are the custom code in this project. Anything generated or system-managed should just be left along, probably.

...one place where prettier might fit is to run it on the generated opal code. it could make it easier to read. just a thought.

**Comment by HillLiu** [comment]
It's possible to improve code conflict. https://github.com/asciidoctor/asciidoctor.js/issues/510

**Comment by Mogztter** [comment]
@HillLiu I don't get it, what do you mean by "it's possible to improve code conflict" ?

**Comment by mojavelinux** [comment]
Yesssssssssssssss!

**Comment by Mogztter** [comment]
To be honest, I was getting tired of semicolons :stuck_out_tongue_winking_eye:

**Comment by Mogztter** [comment]
> ...one place where prettier might fit is to run it on the generated opal code. it could make it easier to read. just a thought.

I gave it a try and the result is quite good. I mean it's still a bit hard to read but it's definitively better.
Though we should be careful as the size of the file (number of lines) is more than double because Prettier is using a 80 line length by default. 

Maybe we should add two following issues:

* Automatically reformat the code (using Prettier) using Standard.js rules
* Use Prettier on the generated code to make it easier to read

**Comment by mojavelinux** [comment]
> because Prettier is using a 80 line length by default.

I think it should be changed to 120. 80 is super aggressive for code.
