### ISSUE TITLE
Remove yarn.lock ?

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#494]
The primary reason of using Yarn was speed but the latest version of npm are fast enough.
Synchronizing `yarn.lock` and `package-lock.json` is tedious so I propose to remove yarn.lock and switch back to npm.

What do you think ?

**Comment by mojavelinux** [comment]
I'm not married to Yarn. If npm works fine for you, I'm all in. I do think you should only use one or the other, not both.

**Comment by Mogztter** [comment]
Yes I'm in the exact same spot as https://stackoverflow.com/a/44904494

And we are not alone: https://github.com/yarnpkg/yarn/issues/5654

Using both is a bad idea and we will eventually be out of sync.
npm is distributed by default so I think we should use it and commit the `package-lock.json` file.

Using `yarn` will still be possible but we should ignore the `yarn.lock` file. So you can install the dependencies and build Asciidoctor.js with `yarn` but without the guarantee of a reproducible build.
