### ISSUE TITLE
File include seems to struggle with utf-8 encoding

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#501]
I have bumped a local project to use `asciidoctor.js@1.5.7-beta.1`.
I noticed a weird display of accented characters in code includes — maybe it happened in a previous release though.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/138627/39924513-6dbce498-5528-11e8-9f08-7db0189ca301.png">

----

It does the same with a regular `.adoc` include:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/138627/39925155-d8594272-552a-11e8-9fc2-713fb44ac84a.png">

No problem with the main `.adoc` file though:

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/138627/39925169-e69a8850-552a-11e8-8345-327d450ff714.png">

**Comment by Mogztter** [comment]
Are you using a special runtime configuration ? https://github.com/asciidoctor/asciidoctor.js/blob/master/docs/manual.adoc#how-to-configure-the-runtime-environment

I will try to create a test case to reproduce this issue. So basically what I need to do is:

**root.adoc**
```
À propos des majuscules accentuées

include::french[]
```
**french.adoc**
```
Le français c'est pas compliqué :)
```

**Comment by oncletom** [comment]
When I switch back to `asciidoctor.js@1.5.6` the problem vanishes.


This is the conversion command I use:
```js
asciidoctor.convertFile('root.adoc', {
  'to_file':  'root.html',
  mkdirs: true,
  safe: 'unsafe',
  doctype: 'book',
  backend: 'html5',
  attributes: {
  'toc=left',
  'toclevels=4',
  'caution-caption=⚠️',
  'important-caption=‼️',
  'webfonts!',
  'note-caption=💬',
  'tip-caption=💡',
  'warning-caption=🚨',
  'linkattrs',
  'lang=fr',
  'env=ci',
  'hide-uri-scheme',
  'experimental',
  'idprefix',
  'source-highlighter=highlightjs',
  'toc-title=Table des matières',
  'appendix-caption=Annexe',
  'last-update-label=Dernière mise à jour'
  }
});
```

**Comment by Mogztter** [comment]
I think the root cause is: https://github.com/asciidoctor/asciidoctor/commit/a6b80d5fb64baec2db5e46b644b2c5858d7aa9f2
We are using now `binread` when reading include files and in Node.js we are using the following implementation:

```js
fs.readFileSync(path).toString('binary')
```

I don't know (yet) what is the correct implementation but for now we get different result between MRI and Node:

```
ruby -e "p ::IO.binread 'french.adoc'"
"Le fran\xC3\xA7ais c'est pas compliqu\xC3\xA9 :)\n"
```

```
node -e "console.log(require('fs').readFileSync('french.adoc').toString('binary'))"
Le franÃ§ais c'est pas compliquÃ© :)

```

@mojavelinux Ping :wink:

**Comment by oncletom** [comment]
> 'binary' - Alias for 'latin1'.

Ah interesting, I did not know 🙃 

It's surprising to see Ruby is defaulting to `ASCII-8BIT`.

I agree string conversion should happen in utf-8.
Is it something that should be reflected back to upstream asciidoctor?

**Comment by mojavelinux** [comment]
Ruby and JavaScript have a different idea of how to read files. In Ruby, if
you don't read the file in binary, it messes with endlines. So we read in
binary, then force encode to UTF-8. It seems that JavaScript is not getting
the memo to switch the encoding (or it just doesn't work the same).

**Comment by Mogztter** [comment]
Urgh! I tried to switch to `utf-8` but now reading images does not work anymore because in some cases we are using Base64 and the implementation does not handle characters outside latin1.
