### ISSUE TITLE
Conflict with google recaptcha

### ISSUE THREAD

**Issue by HillLiu** [asciidoctor/asciidoctor.js#510]
//cdn.jsdelivr.net/npm/asciidoctor.js@1.5.7-beta.1/dist/browser/asciidoctor.js
```
recaptcha__en.js:225 Uncaught RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at hn (recaptcha__en.js:225)
    at hn (recaptcha__en.js:225)
    at hn (recaptcha__en.js:225)
    at hn (recaptcha__en.js:225)
    at hn (recaptcha__en.js:225)
    at hn (recaptcha__en.js:225)
    at hn (recaptcha__en.js:225)
```

## Reproduce
1. use script tag //cdn.jsdelivr.net/npm/asciidoctor.js@1.5.7-beta.1/dist/browser/asciidoctor.js

2. install google reCAPTCHA

3. click on reCAPTCHA checkbox, it will always keep in loading status. and check the browser console will see above error.

4. after remove asciidoctor.js, reCAPTCHA will back to normal.

**Comment by Mogztter** [comment]
Hello @HillLiu, it may be related to https://github.com/asciidoctor/asciidoctor.js/issues/299
As mentioned in this issue, the next version of Opal will (hopefully) fix this issue: opal/opal#1821

**Comment by Mogztter** [comment]
@HillLiu It should be resolved in Asciidoctor.js 1.5.7-rc.1. Could you please give it a try ?

**Comment by Mogztter** [comment]
@HillLiu Did you have a chance to look at it ?

**Comment by HillLiu** [comment]
Sure, I'll take time to verify it on this weekend.

**Comment by Mogztter** [comment]
Ok thanks @HillLiu 
I tried to reproduce this issue but it's working with both Asciidoctor.js 1.5.7-beta.1 and 1.5.7-rc.1. Here's my HTML document:

```html
<html>
<head>
</head>
<body>
  <div class="g-recaptcha" data-sitekey="xyz"></div> <!-- replace with your key -->
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <script src='https://cdn.jsdelivr.net/npm/asciidoctor.js@1.5.7-beta.1/dist/browser/asciidoctor.js'></script>
  <script>
    var asciidoctor = Asciidoctor();
    console.log(asciidoctor.convert('Hello *world*'));
  </script>
</body>
</html>
```

**Comment by HillLiu** [comment]
@Mogztter  I found google recaptcha also make some changes on their side. 

When I check https://www.gstatic.com/recaptcha/api2/v1531759913576/recaptcha__en.js
line 225, I already can not find any related code.

So this issue should not reproducible even I try with old version Asciidoctor.js.

Also let you know, I create a react iframe component that wrap Asciidoctor.js  in a iframe, so this is why I consider how to verify it.

* GIT
   * https://github.com/react-atomic/react-atomic-organism/tree/master/packages/organism-react-asciidoc
* Codesandbox
   * https://codesandbox.io/embed/jjq8ko2krv?module=%2Fsrc%2Fasciidoc.js&moduleview=1

When this issue was gone, we could close it, now.

**Comment by Mogztter** [comment]
> When this issue was gone, we could close it, now.

@HillLiu I'm not sure I understand what you mean 🤔 
Is this issue effectively gone (and thus we can close this issue) ? or do we need to do more tests to make sure that this issue is resolved ?

**Comment by Mogztter** [comment]
> Also let you know, I create a react iframe component that wrap Asciidoctor.js in a iframe

I'm not familiar with the Atomic design but the Asciidoctor component looks great! 👍 

```js
<Asciidoc options={{ doctype: "book" }}>{adoc}</Asciidoc>;
```

**Comment by Mogztter** [comment]
Ok, I just got the confirmation that #299 is resolved.

I will close this issue but if you found another issue or a related issue, please feel free to create a new issue or to reopen this one.

Thanks for your report 😊
