### ISSUE TITLE
How to include latex equations?

### ISSUE THREAD

**Issue by stefaneidelloth** [asciidoctor/asciidoctor.js#524]
I have a asciidoc document that contains some latex equation:

```
:stem: latexmath

[latexmath]
++++        

\alpha + \beta

++++
```

I am able to correctly render this with the preview extension for Chrome. However, I did not manage to render it with asciidoctor.js in a browser environment. 

I guess that I somehow need to reference this javascript file:

https://github.com/asciidoctor/asciidoctor-latex/blob/master/dist/main.js

I tried to include it with a script tag:

```
<html>
  <head>
    <script src="./node_modules/asciidoctor.js/dist/browser/asciidoctor.js"></script>
	<script src="http://**myserver**/main.js">
</script>
  </head>
        
  <body>
       <div id="target"></div>
    <script>
      var asciidoctor = Asciidoctor();
	  const content = "include::raw.asciidoc[]"
	  const html = asciidoctor.convert(content,{safe: 'safe'});      
      document.getElementById('target').innerHTML = html;
    </script>
  </body>
</html>
```
The shown output is

\[\alpha + \beta\]

and I get following error:

```
asciidoctor.js:145 Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at $defineProperty (asciidoctor.js:145)
    at Object.Opal.allocate_module (asciidoctor.js:549)
    at Opal.module (asciidoctor.js:596)
    at asciidoctor-latex.js:16515
    at Opal.modules.asciidoctor/latex (asciidoctor-latex.js:16526)
    at Object.Opal.load (asciidoctor.js:2293)
    at $Object.Opal.require (asciidoctor.js:2321)
    at asciidoctor-latex.js:16536
    at asciidoctor-latex.js:16537
$defineProperty @ asciidoctor.js:145
Opal.allocate_module @ asciidoctor.js:549
Opal.module @ asciidoctor.js:596
(anonymous) @ asciidoctor-latex.js:16515
Opal.modules.asciidoctor/latex @ asciidoctor-latex.js:16526
Opal.load @ asciidoctor.js:2293
Opal.require @ asciidoctor.js:2321
(anonymous) @ asciidoctor-latex.js:16536
(anonymous) @ asciidoctor-latex.js:16537
asciidoctor.js:22327 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.



```

=> How do I need to modify my html file to be able to render the latex equation?

**Comment by Mogztter** [comment]
If the LaTex equations are rendered in the browser extension, it's because we are using MathJax: https://github.com/asciidoctor/asciidoctor-browser-extension/blob/8e1deaff9ddc5427eed5886bf43929675a2f9f46/app/js/renderer.js#L95-L102

When converting a string, the header and footer are excluded by default. In other words Asciidoctor generates an embeddable document without the `<head>`section. As a consequence the MathJax script is absent.

You should add and load MathJax to renderer the equations.

**Comment by Mogztter** [comment]
@stefaneidelloth Please keep me posted and don't hesitate to ask questions if it's not clear 😊

This should be documented in the user manual (that's why I added the "Documentation" tag) so your feedback is really important.

Maybe I should add a dedicated section in the user manual to describe how to enable the built-in features of Asciidoctor when the document is rendered as an embeddable HTML page:

* MathJax
* FontAwesome
* Syntax highlighting
* ... ?

**Comment by stefaneidelloth** [comment]
>Maybe I should add a dedicated section in the user manual to describe how to enable
Maybe you want to address two different kinds of users:

a) users who wants to incorporate asciidoctor.js in their own library
=>might want to use minimalistic, modular version of asciidoctor.js and tweak
its configuration in detail to meet a distinct need
They might want to use 
npm install asciidoctor-base.js
to get a corresponding distribution. 

b) users that want to have a "one click solution" with all(most?) available extensions enabled to be able to focus on the content of the asciidoc documents instead of the building infrastructure. 
They might want to use
npm install asciidoctor.js   or
npm install asciidoctor-complete.js
to get a corresponding distribution. 

For me it's b). 

In order to illustrate that a bit more... My current situation is that my team has decided to use a Confluence wiki for documentation a few months ago. "Ok, we take the commercial profession solution. We pay some money and then everything will work nicely." ;) It turned out that Cunfluence sucks when it comes to some "more advanced content" like tables and equations. 

That's why I am currently looking for alternatives. The less configuration effort such an alternative would require, the easier it would be for me to convince my team to go for it. 

I did not want to extra install Ruby on our build server and hoped that asciidoctor.js might be an alternative with less dependencies to produce a preview of our inhouse documentation. 

I also put some effort in finding out how asciidoc could be incorporated in confluence. You can get an impression of the current state of asciidoc support of Confluence if you read the (comments of) following issue tickets:
https://jira.atlassian.com/browse/CONFSERVER-38863
https://github.com/norganna/adoc-usermacro/issues/5

Maybe someone of you is motivated enough to provide a asciidoctor extension on the confluence marketplace that would allow a broader audience to use it: 
https://marketplace.atlassian.com/addons/app/confluence

Currently it feels like I am doing things wrong, because I already put lots of effort in this strategy without getting it to work properly. ... Even if I would solve the mathjax issue... I dont't know which issue might pop up next. Even if I like to support open source projects, I am on a higher abstraction level and do not really want to fiddle about the details on how to include MathJax ect. 

Nevertheless I am very thankful for all the work you already put in this project. If I find time to include MathJax I'll keep you updated on my progress.

**Comment by Mogztter** [comment]
There's a lot to process in your comment :smile: 
I think it will be easier to guide you though if we can chat on https://gitter.im/asciidoctor/asciidoctor.js

If you want the full-blown solution, you need to render a full HTML5 page:

```js
asciidoctor.convert('your document content', {header_footer: true})
```

Anyway feel free to ping me on Gitter so we can talk about what you need to get started.

**Comment by stefaneidelloth** [comment]
A. This example shows how to render mathjax equations:

```
<html>
  <head>
	<!-- include asciidcotor.js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/asciidoctor.js/1.5.6/asciidoctor.min.js"></script>
		
	<!-- include mathjax.js-->
	<script type="text/x-mathjax-config">
	  MathJax.Hub.Config({
		extensions: ["tex2jax.js"],
		jax: ["input/TeX", "output/HTML-CSS"],
		tex2jax: {
		  inlineMath: [ ['$','$'], ["\\(","\\)"] ],
		  displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
		  processEscapes: true
		},
		"HTML-CSS": { fonts: ["TeX"] }
	  });
	</script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js' async></script>
</script>
  </head>
        
  <body>
       <div id="target"></div>
    <script>
      var asciidoctor = Asciidoctor();
	  const content = "include::raw.asciidoc[]"
	  const html = asciidoctor.convert(content,{safe: 'safe'});      
      document.getElementById('target').innerHTML = html;
    </script>
  </body>
</html>
```

B. When I tried to use the option `header_footer: true` I got following error:

```
asciidoctor.js:22336 GET http://localhost:8080/css/asciidoctor.css 404 (Not Found)
...
```

I would expect that the asciidotor.css file would be included from the node_modules folder or 
from a remote location. However, adding a reference to that file did not help:
<link type="text/css" rel="stylesheet" href="./node_modules/asciidoctor.js/dist/css/asciidoctor.css" media="all">

=> I had to create a folder "css" in my project and copy the asciidoctor.css file to that folder.  

Using that setup,  the option `header_footer: true` works now. 

To be clear: the option `header_footer: true` does not replace the import of mathjax.js.
 
Instead, it enables additional features. The documentation of the original ruby option can be found here:
https://asciidoctor.org/docs/user-manual/#ruby-api-options

> If true, add the document header and footer (i.e., framing) around the body content in the output. NOTE: The default value for this option is opposite of the default value for the CLI.

(I did not really understand that without building an example. Unfortunately I can not easily add screenshots here but you can see the effects using the asciidoc example content given below.)

The option does not only change the rendering of the header but the **rendering of the full document** (because the css file is now applied)! 

Example asciidoc content
```
= Hello, AsciiDoc!
= Hello, AsciiDoc!
Doc Writer <doc@example.com>

An introduction to http://asciidoc.org[AsciiDoc].

== Header 2

Content content.

* List item 1
* List item 2

:stem: latexmath
:icons: font
:source-highlighter: highlightjs

[latexmath]
++++        

\alpha + 3 = g

++++

icon:comment[] This is a comment icon


[source,ruby]
----
require 'asciidoctor'

puts Asciidoctor.convert_file 'mysample.adoc', to_file: false
----
```


The current state of my main.html file is:

```
<html>
  <head>
	<!-- include asciidcotor.js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/asciidoctor.js/1.5.6/asciidoctor.min.js"></script>
	<!-- In order to include asciidoctor.css you have to copy it to a folder "./css" of your project -->
	
	<!-- include mathjax.js-->
	<script type="text/x-mathjax-config">
	  MathJax.Hub.Config({
		extensions: ["tex2jax.js"],
		jax: ["input/TeX", "output/HTML-CSS"],
		tex2jax: {
		  inlineMath: [ ['$','$'], ["\\(","\\)"] ],
		  displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
		  processEscapes: true
		},
		"HTML-CSS": { fonts: ["TeX"] }
	  });
	</script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js' async></script>
	
	<!-- include font awesome -->
	<link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" media="all">
	
	<!-- include highlightjs -->
	<script src='https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js' async></script>
	<link type="text/css" rel="stylesheet" href="https://raw.githubusercontent.com/highlightjs/highlight.js/master/src/styles/default.css" media="all">
	
</script>
  </head>
        
  <body>
       <div id="target"></div>
    <script>
      var asciidoctor = Asciidoctor();
	  const content = "include::raw.asciidoc[]"
	  const html = asciidoctor.convert(content,{safe: 'safe', header_footer: true});      
      document.getElementById('target').innerHTML = html;
    </script>
  </body>
</html>
```
