### ISSUE TITLE
toc disabled

### ISSUE THREAD

**Issue by asdfg0280** [asciidoctor/asciidoctor.js#525]
I contribute HackAdoc.
It is real time compilation AsciiDoc.

But, writing `toc::[]` shows `<!-- toc disabled -->` .

**Comment by Mogztter** [comment]
Hello,

If you are using the TOC macro, you define to define the attribute `:toc: macro`: https://asciidoctor.org/docs/user-manual/#manual-placement

> If toc is not set to macro, any toc macro in the document will be silently ignored.

**Comment by asdfg0280** [comment]
![image](https://user-images.githubusercontent.com/31565162/43346754-67d942d2-922d-11e8-916a-9cfeeee15eb9.png)
Of cource, I try it.But , it does not behave correctly.Like this.

**Comment by Mogztter** [comment]
I think the reason is that you don't have sections so the Table Of Contents is not shown because there is nothing to display: https://github.com/asciidoctor/asciidoctor/blob/2398cc1c51f1f040400e8c98f7d9b41621748717/lib/asciidoctor/converter/html5.rb#L858

**Comment by asdfg0280** [comment]
![image](https://user-images.githubusercontent.com/31565162/43348239-0b4402c6-9234-11e8-8045-0bafda537731.png)
I try it.It disappear `<!-- toc disabled-->`.But, this does not correctly render.

**Comment by Mogztter** [comment]
That's weird, are you using any options/attributes ? 
The following code is working:
```js
var asciidoctor = require('asciidoctor.js')()
var html = asciidoctor.convert('= Title\n:toc: macro\n\ntoc::[]\n== Section1\n\n== Section 2', {header_footer: true, attributes: ['icons=font@', 'showtitle=true']})
console.log(html);
```

**Comment by asdfg0280** [comment]
I use same code.

**Comment by Mogztter** [comment]
Could you please try to reproduce this issue with a simple test case and/or in an isolated context (ie. outside HackAdoc) ?

I've noticed that HackAdoc is using Asciidoctor 1.5.7-beta.1, could you upgrade to 1.5.7-rc.1 and test again ?

**Comment by asdfg0280** [comment]
![image](https://user-images.githubusercontent.com/31565162/43354901-972f21bc-928e-11e8-94aa-ff5c5618808d.png)
oh,I try upgrade asciidoctor,js , but it does not behave correctly.

**Comment by Mogztter** [comment]
🤔 Did you try to add a preamble (ie. add some text before the first section) ? Do you reproduce this issue outside HackAdoc in a simple webpage ?

**Comment by asdfg0280** [comment]
Ahhh,HackAdoc was folked by HackMD. So, that is not a simple webpage.

**Comment by Mogztter** [comment]
Yes I know but the bug might be in HackAdoc. The "Table Of Contents" might be output by the `convert`.

Could you add a `console.log` to print the output ?

**Comment by mojavelinux** [comment]
I don't think adding a preamble would change this. Following this thread, I'm convinced a DOM function is removing the toc, or when the DOM nodes are copied into the document, the toc is getting dropped. I can't see any reason why Asciidoctor would not be adding the toc in this case. I would advise printing exactly what Asciidoctor produces to the console so you can see what it contains before adding it to the DOM.

**Comment by Mogztter** [comment]
@asdfg0280 Did you have a chance to debug a bit further ? Did you found the root cause ?

**Comment by asdfg0280** [comment]
I resolve this issue.Sry my bad

**Comment by Mogztter** [comment]
No worries 👍
