### ISSUE TITLE
H1 is not working in browser 

### ISSUE THREAD

**Issue by MrIndiaDev** [asciidoctor/asciidoctor.js#526]
Sample code

```js
asciidoctor.convert("= Maven")
```
returns blank where

```js
asciidoctor.convert("== Maven")
```

returns

```html
div class="sect1">
<h2 id="_maven">Maven</h2>
<div class="sectionbody">

</div>
</div>
```

**Comment by Mogztter** [comment]
Hello @MrIndiaDev,

When converting a string, the header and footer are excluded by default to make Asciidoctor consistent with other lightweight markup engines like Markdown.

When converted to an embeddable document, the document title is not shown by default. If you want the title to be shown, set the `showtitle` attribute in the document header or via the CLI or API. The author and revision information is not shown below the document title in the embeddable version of the document like it is in the standalone document, even when the `showtitle` attribute is set.

https://asciidoctor.org/docs/user-manual/#document-title-visibility

```js
var content = '= Document title';
var html = asciidoctor.convert(content, {attributes: {showtitle: true}});
console.log(html);
// <h1>Document title</h1>
```
