### ISSUE TITLE
Processor hangs when parsing overlapping passthrough in monospaced text

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#535]
The processor in 1.5.7-rc.1 hangs processing the following document:

```
Link the system library `+libconfig++.so.9+` located at `+/usr/lib64/libconfig++.so.9+`.
```

Technically, that passthrough syntax doesn't produce the desired result. But it shouldn't cause Asciidoctor.js to hang.

Note that Asciidoctor Ruby 1.5.7 processes the same syntax without hanging. Somewhere, the cursor is not advancing in Asciidoctor.js.

**Comment by Mogztter** [comment]
The processor is looping on `restore_passthroughs`

**Comment by Mogztter** [comment]
I can reproduce the issue: https://github.com/opal/opal/issues/1878

**Comment by mojavelinux** [comment]
:tada:
