### ISSUE TITLE
How to extract all anchors ?

### ISSUE THREAD

**Issue by gaurav-nelson** [asciidoctor/asciidoctor.js#540]
Bu running:
```javascript
var stuff = asciidoctor.loadFile("test.adoc",{'safe': 'safe', 'catalog_assets': true});
stuff.convert();
console.log(util.inspect(stuff.getReferences()['ids']))
```
I am getting the following output:
```bash
$Hash {
  '$$smap':
   { 'devel-intro-about': 'About This Guide',
     'devel-intro-design': 'Design Overview',
     'devel-intro-workflow': 'Workflow',
     'devel-intro-prep': 'Preparation',
     'devel-intro-init': 'Initialization',
     'directory-structure': 'Directory Structure',
     'devel-intro-spec-file': 'APB Spec File',
     'devel-intro-actions': 'Actions',
     'devel-intro-build': 'Build',
     'devel-intro-deploy': 'Deploy' },
  '$$map': {},
  '$$keys':
   [ 'devel-intro-about',
     'devel-intro-design',
     'devel-intro-workflow',
     'devel-intro-prep',
     'devel-intro-init',
     'directory-structure',
     'devel-intro-spec-file',
     'devel-intro-actions',
     'devel-intro-build',
     'devel-intro-deploy' ] }
``` 

How can I extract just these keys? Or if there is a direct API call to get all anchors from an asciidoc file?

**Comment by mojavelinux** [comment]
This is where we would map a getReferenceIds() method in the API.

Though it's better to use the refs table since the ids table is deprecated. The refs table gives you access to the referenced node.

**Comment by Mogztter** [comment]
Hello @gaurav-nelson, you can use the function above to convert an Opal (Ruby) Hash to a JSON object:

https://github.com/asciidoctor/asciidoctor.js/blob/a86ed3cbe2937d8bfa53210302a2ce811ac429f9/src/asciidoctor-core-api.js#L13-L20

This is an internal function and I think `getReferences()` should return an JSON object instead of an Opal Hash.

@mojavelinux What do you think ?

**Comment by mojavelinux** [comment]
I'd rather have specific methods than wrap all of getReferences() (which should be renamed to getCatalog() btw). This couples us less with the implementation details, which could be subject to change.

**Comment by Mogztter** [comment]
Ok so:

```js
getCatalogRefs() // returns a Hash ?
getCatalogFootnotes() // returns an Array ? (no conversion)
getCatalogLinks() // returns an Array ? (no conversion)
getCatalogImages() // returns an Array ? (no conversion)
getCatalogIndexterms() // returns an Array ? (no conversion)
getCatalogCallouts() // returns a Callouts object (we should probably need to map the methods of the Callout object)
getCatalogIncludes() // returns a Hash ?
```


Should we map `getCatalogIds` or not ?

**Comment by mojavelinux** [comment]
I don't think we have to use the word "category" in this case. Let's focus on what is being pulled, not from where. So I'm thinking:

```
getRefs()
getFootnotes()
```

etc.

Let's not expose callouts and includes right now since those are very much internal tables. The rest look good to me.

**Comment by gaurav-nelson** [comment]
@mojavelinux @Mogztter I'm wondering if this made to a direct function? 

I am using the following to get all anchors:
```js
console.log(doc.getReferences()['refs']['$$keys'])
```
