### ISSUE TITLE
Is it possible to get all source tokens?

### ISSUE THREAD

**Issue by 1inus** [asciidoctor/asciidoctor.js#541]
hightlight a long article takes a little longer, i want to highlight the article section one by one. 
so I need to know the token information of the whole doc.

Is there an api that can get all the asciidoc tokens ?

**Comment by Mogztter** [comment]
Hello @1linus, 

I'm not sure I quite understand what you want to do.
Could please provide an example ?

Thanks 😄

**Comment by Mogztter** [comment]
If you want to extract the inline elements (bold, emphasis...) then the answer is no.
We are working on an inline parser but for now these nodes are not available in the AST: https://github.com/asciidoctor/asciidoctor/issues/61

If you are looking for blocks and nodes (paragraph, table, section, title...) then please read the JavaScript documentation: http://asciidoctor.github.io/asciidoctor.js/master/
