### ISSUE TITLE
How to get the processing errors

### ISSUE THREAD

**Issue by darlenya** [asciidoctor/asciidoctor.js#544]
Hi, I would like to integrate the asciidoctor.js into a CI/CD pipeline. There the processor needs to convert multiple sub projects. And I would like to check if the processing was done without warnings and errors. 

The example code:
```javascript
'use strict'

const path = require('path')
const asciidoctor = require('asciidoctor.js')()
const fileName = path.join(__dirname, 'fixtures/doc1/index.adoc')

const doc = asciidoctor.loadFile(fileName, { safe: 'safe', catalog_assets: true, backend: 'xhtml' })
const html = doc.convert()
const catalog = doc.getCatalog()

// get the referenced images.
const images = catalog.images

// !!! Here I would like to get all the warnings and errors
// anything like that
const errors = doc.getErrors()
```

I searched around for a day now, but was not able to get this working.
There is a MemoryLogger but I did not found how to use it or access it.

**Comment by oncletom** [comment]
Hey @darlenya,

In a recent version of Asciidoctor (`v1.5.7`), they have introduced _loggers_. You can find a good example to use it in a comment of #187.

**Comment by Mogztter** [comment]
> There is a MemoryLogger but I did not found how to use it or access it.

As mentioned by @oncletom you can instantiate the MemoryLogger and use it to retrieve errors and warnings.

> I searched around for a day now, but was not able to get this working.

Sorry about that.
I should make it a documentation page :flushed:

**Comment by darlenya** [comment]
Hi thanks for the fast response. Thats what I am looking for. Btw. I have trouble to understand the JS API. I have the feeling that it is very powerful. But not yet documented.
But great work anyhow.

**Comment by Mogztter** [comment]
I'm reopening this issue, just to make sure that I don't forget to document the new logging mechanism.

@darlenya if you want to share your experience that would be awesome (ie. how you integrate it in your system, what drawbacks you found...)
