### ISSUE TITLE
Bug: Video autoplays when autoplay is not included in options

### ISSUE THREAD

**Issue by RichardJECooke** [asciidoctor/asciidoctor.js#550]
If you have a video with a start attribute the video autoplays incorrectly (it doesn't autoplay if there's no start attribute, which is correct).

There's no way I can see to turn off autoplay, even specifying an end attribute of 0 or 21 doesn't stop it.

```asciidoc
video::155635261[vimeo, width=700, height=400, theme=dark, start=20]
```

**Comment by Mogztter** [comment]
I do not reproduce this issue (Chrome):

![autoplay](https://user-images.githubusercontent.com/333276/46018351-f70c1300-c0d9-11e8-9970-e2f52029e225.png)

HTML code:

```html
<iframe width="700" height="400" src="https://player.vimeo.com/video/155635261#at=20" frameborder="0" allowfullscreen=""></iframe>
```

Could you please provide a reproduction case with the exact command you are using to convert your AsciiDoc document to HTML ?

**Comment by RichardJECooke** [comment]
Thanks. My output is the same as yours. And it works in Chrome for me too.

It seems Firefox starts autoplaying when the `#at=20` url parameter is included. I'll see if I can find where their issues are logged and open one connected to this. I seem to remember I couldn't register on Mozilla's forum last time I found something wrong.

**Comment by RichardJECooke** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1493972

**Comment by Mogztter** [comment]
Thanks for the follow-up with the link to the Firefox issue.
It's greatly appreciated as it will help other users :+1:
