### ISSUE TITLE
Error.call broken by asciidoctor.js

### ISSUE THREAD

**Issue by rmannibucau** [asciidoctor/asciidoctor.js#556]
As the title explains it, importing adoctor.js breaks Error API

**Comment by Mogztter** [comment]
Hello @rmannibucau
I'm not sure I understand, what is the `Error` API ? Are you talking about https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error ? Or about a Node.js API that I don't know about ?

**Comment by rmannibucau** [comment]
Yes, to this one: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call

**Comment by Mogztter** [comment]
Indeed, this is related to https://github.com/opal/opal/issues/1846
I've partially fixed this issue in https://github.com/asciidoctor/asciidoctor.js/pull/542

The next version of Asciidoctor.js should resolve this issue. 

You can take a look at https://github.com/Mogztter/opal-node-runtime/blob/master/src/index.js
The basic idea to work around this issue is to save and restore `Function` methods.

**Comment by rmannibucau** [comment]
This is what I'm heading to but with webpack builds it requires to hack the generated js to have these before/after hooks which is not as straight as previous sample for complex apps.

**Comment by Mogztter** [comment]
> This is what I'm heading to but with webpack builds it requires to hack the generated js to have these before/after hooks which is not as straight as previous sample for complex apps

Hopefully I will release a new version soon.

> edit: seems Error becomes Exception somehow and therefore this trick does not work (still investigating)

Thanks for taking the time to investigate. I want this bug to be fixed before 1.5.7 "final".
Could you please post the stack trace maybe it will ring a bell ?

**Comment by rmannibucau** [comment]
The stacktrace does not help because appears when another lib - a form validation one here - calls Error.call(this) and opal replaced the native Error by Exception class which does not have call method.

Opal catch window or global, would be gret to replace it by a local object instead.

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor.js/commit/da2c70cc977429c4e37a271cfee42b461c8cd422

**Comment by Mogztter** [comment]
Sorry @rmannibucau I think I now understand what you meant.
I've encountered this issue on `Boolean.call` so I need to preserve the `call` function on each objects that inherit from `Function` :disappointed:

**Comment by rmannibucau** [comment]
@Mogztter I was not but I think it can work - sorry can't "pop" back my branch for now, this week is a bit busy. That said if the root objects can be back the native ones it would be saner cause this code ignores other than standard methods and potential polyfills.

**Comment by Mogztter** [comment]
Fixed in 9d9c46e
