### ISSUE TITLE
Implement IO.binread (interim step)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#583]
Interim step, this code should be move upstream (Opal):

https://github.com/asciidoctor/asciidoctor/blob/9e5d9cab9f1ae8ce0399459a02f43b2c2610cac1/lib/asciidoctor/core_ext/1.8.7/io/binread.rb

**Comment by Mogztter** [comment]
Actually we don't need this method: 

```
ASCIIDOCTOR_CORE_VERSION=mogztter/asciidoctor#remove-ruby-18 npm run build
```

ping @mojavelinux

**Comment by mojavelinux** [comment]
Let's check with:

    ASCIIDOCTOR_CORE_VERSION=mojavelinux/asciidoctor#issue-2764-no-unmaintained-rubies npm run build

Perhaps Opal already supports this method?

**Comment by mojavelinux** [comment]
This method is used to get the bits when data-uri is enabled.

**Comment by Mogztter** [comment]
This method is available in a Node.js environment (defined in Opal): https://github.com/opal/opal/blob/master/stdlib/nodejs/io.rb

And I don't think we have a test case when `data-uri` is enabled on the browser... I need to check.

**Comment by Mogztter** [comment]
Should be resolved with #642 (related issue #640).

`binread` will only be used in a Node.js environment. In a Browser environment we provide our own `generate_data_uri_from_uri` implementation.

> This method is used to get the bits when data-uri is enabled.

I've added tests on this feature, see https://github.com/asciidoctor/asciidoctor.js/pull/642/files#diff-53f9e34062dad1fe672b4e89ecb0ff0aR828

**Comment by mojavelinux** [comment]
> In a Browser environment we provide our own generate_data_uri_from_uri implementation.

Do you think we should agree on a lower-level method?

**Comment by Mogztter** [comment]
@mojavelinux No I think it's fine, the method returns a single value and gives use some flexibility.

**Comment by mojavelinux** [comment]
I believe this is now obsolete. Correct?

**Comment by Mogztter** [comment]
Yes, closing :+1:
