### ISSUE TITLE
Implement IO.write (interim step)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#584]
Interim step, this code should be move upstream (Opal):

https://github.com/asciidoctor/asciidoctor/blob/9e5d9cab9f1ae8ce0399459a02f43b2c2610cac1/lib/asciidoctor/core_ext/1.8.7/io/write.rb

**Comment by Mogztter** [comment]
Actually we don't need this method: 

```
ASCIIDOCTOR_CORE_VERSION=mogztter/asciidoctor#remove-ruby-18 npm run build
```

**Comment by mojavelinux** [comment]
Can you run this instead?

ASCIIDOCTOR_CORE_VERSION=mojavelinux/asciidoctor#issue-2764-no-unmaintained-rubies npm run build

**Comment by mojavelinux** [comment]
It could be that this method got moved into Opal long ago.

**Comment by Mogztter** [comment]
Yes it's implemented in Opal (Node.js): https://github.com/opal/opal/blob/master/stdlib/nodejs/io.rb
And it does not make much sense in a browser environment.

So I think we can close this one.

**Comment by mojavelinux** [comment]
Awesome. Thanks for checking!
