### ISSUE TITLE
Create a documentation page to list all the extensions available for Asciidoctor.js

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/asciidoctor.js#606]
* Interactive code listings (JavaScript): https://github.com/oncletom/asciidoctor-extension-interactive-runner
* PlantUML: https://github.com/eshepelyuk/asciidoctor-plantuml.js
* Emoji: https://github.com/mogztter/asciidoctor-emoji
* Chart: https://github.com/asciidoctor/asciidoctor-browser-extension/blob/master/app/js/vendor/asciidoctor-chart-block-macro.js (needs to be extracted in a npm module)
* Other ?

**Comment by mojavelinux** [comment]
I like this idea. My advice is to get the page started early because otherwise this issue will just fill up with links (based on past experience).

---

Long term, we should definitely think about a plugin portal. It doesn't have to be too elaborate. Just a way to sort through the extensions and find the link to them. Something like:

* http://plugins.grails.org/
* https://plugins.gradle.org/
* https://atom.io/packages

It could be static with a JavaScript-based filter. Just an idea.

**Comment by stken2050** [comment]
> * Interactive code listings (JavaScript): https://github.com/oncletom/asciidoctor-extension-interactive-runner
> * PlantUML: https://github.com/eshepelyuk/asciidoctor-plantuml.js
> * Emoji: https://github.com/mogztter/asciidoctor-emoji
> * Chart: https://github.com/asciidoctor/asciidoctor-browser-extension/blob/master/app/js/vendor/asciidoctor-chart-block-macro.js (needs to be extracted in a npm module)
> * Other ?

@Mogztter Thanks for the list!  I like the idea, too. Here's my thought.

I agree to a long-term vision provided by @mojavelinux, but so far, adding (copy-paste;) this list to `README.adoc` of this repo would be pretty much sufficient.

I think 99.9% of users of Asciidoctor/.js are the end-users of the front-end preview/editor apps, and what they really care is how capable of each apps or which features are covered.

The 0.1 % of users are developers of the preview/editor apps like me, and the developers need this info and, are responsible to present how capable of their apps.

These have been my primary concern of the preview/editor apps:

- Table: Built-in Asciidoctor engine
- Code Syntax highlighting: Asciidoctor provides as default for highlight.js, for other highlight library, users need to configure which is hard to do.
- Stem (LaTeX mathematical expressions): Mathjax supported as default.
- Diagram/Chart: No idea how to do it under .js before knowing PlantUML: https://github.com/eshepelyuk/asciidoctor-plantuml.js

As you might know, currently I actively develop live-viewer extension(app) for VS Code:

https://github.com/stken2050/asciidoc-live-electron

https://github.com/stken2050/asciidoc-live-electron-viewer

and will publish to https://marketplace.visualstudio.com/VSCode soon.

In the readme file, I need to explain which features will work out of box with a proper Asciidoc syntax, and which features are optional as plugin(extension).

This is a planned design.
The electron viewer app will look into a specific directory for plugins.

 Every plugins are integrated via dynamic ES Module loading, so plugin should be written in ESM format(export). For npm packages, it should be easy to write a small bridge that `require` npm package internally. I plan to implement the ESM plugin that bridges for PlantUML: https://github.com/eshepelyuk/asciidoctor-plantuml.js for illustration, and perhaps include it as a default plugin of the app.

**Comment by mojavelinux** [comment]
Here's another example of a plugin portal for reference.

https://www.chaijs.com/plugins/
