### ISSUE TITLE
Require Node.js 10 after the 1th January 2019

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#609]
After this date Node.js 8 LTS will enter maintenance: https://github.com/nodejs/Release

**Comment by Mogztter** [comment]
I'm not sure about this one...
Asciidoctor.js is running faster on Node.js 10 and technically we only test it against Node.js 10+ and Node.js 11+ (current) but I don't want to block an install or "force" a migration...

@mojavelinux @oncletom do you think we should stay on Node.js >= 8 for now ?

**Comment by oncletom** [comment]
I would drop the support of Node 8 when this version is not maintained.

This survey has some info about versions adoption: https://nodejs.org/en/user-survey-report/#version. There are some [official stats](https://nodejs.org/metrics/#versions) et [unofficial stats](https://nodesource.com/node-by-numbers) too.

**Comment by Mogztter** [comment]
Thanks for sharing, that gives us a good overview :+1: 

If I'm reading the stats correctly, Node.js 8 is still widely used.
That was my gut feeling... it's probably too soon to require Node.js 10.

I will postpone until Node.js 8 is EOL (December 2019).

**Comment by mojavelinux** [comment]
I recommend following what Antora is doing, which is to align with the Node release cycle. As @oncletom mentioned, when support has officially ended, then we should drop it too.

https://nodejs.org/en/about/releases/

As for whether to mark the package.json that way or not, that's up to you. I tend to prefer communicating the minimum requirement via the docs rather than enforcing it via the build. Enforcing it in the build can break builds that use backports to achieve compliance.

**Comment by Mogztter** [comment]
All things considered, I think it's mostly a documentation issue. I don't think it's worth to update the version in the `engines` field because we don't use any feature only available in Node 10+.

So we should state in the README and/or the documentation the following:

> We recommend using the latest long term support (LTS) release of Node. While you can use other versions of Node, Asciidoctor.js is only tested against active LTS releases.

(taken from https://docs.antora.org/antora/2.2/install/linux-requirements/)

So I don't think it requires a major/breaking version. Of course, if we do update the `engines` (for instance, to use a feature that's only available in the latest LTS) then we need to publish a major/breaking version.
