### ISSUE TITLE
Do not use Time module to reduce the Opal runtime size

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#654]
https://ruby-doc.org/stdlib-2.6/libdoc/time/rdoc/Time.html

We will need to provide our own implementation of [`Asciidoctor::Timings`](https://github.com/asciidoctor/asciidoctor/blob/e6ff47641a0e4bcc5d9e5271eaaf5b6389f5cacc/lib/asciidoctor/timings.rb) and Asciidoctor core is willing to abstract the following code:

https://github.com/asciidoctor/asciidoctor/blob/e6ff47641a0e4bcc5d9e5271eaaf5b6389f5cacc/lib/asciidoctor/document.rb#L490-L506

**Comment by mojavelinux** [comment]
> We will need to provide our own implementation of Asciidoctor::Timings 

Perhaps just override the `now` method?

> Asciidoctor core is willing to abstract the following code:

Is there an upstream issue?

**Comment by Mogztter** [comment]
> Perhaps just override the now method?

Correct, and also `print_report` because `to_f` is called on `Time` object (or I could implement `Time.now` and `Time.to_f`).

> Is there an upstream issue?

Nope :sweat_smile: 
But I don't really know how to formulate this feature... "Abstract the document date resolution" ?

**Comment by mojavelinux** [comment]
> But I don't really know how to formulate this feature... "Abstract the document date resolution" ?

Yep. Or "Delegate date/time assignments to a method"

**Comment by Mogztter** [comment]
https://github.com/asciidoctor/asciidoctor/issues/3029
