### ISSUE TITLE
Remove math, complex, random and rationale modules

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#656]
The Opal runtime includes by default the following modules:

* `corelib/math`
* `corelib/complex`
* `corelib/random`
* `corelib/rationale`

But these modules are not used in Asciidoctor.js

**Comment by Mogztter** [comment]
@mojavelinux I think we should create a repository named `opal-node-runtime` inside the Asciidoctor organization to create an Opal runtime specifically designed for Asciidoctor. The package name on npmjs could be `@asciidoctor/opal-runtime` ?

The current Opal runtime at https://github.com/mogztter/opal-node-runtime is a "general purpose" Opal.

**Comment by mojavelinux** [comment]
I'm supportive of that idea.

**Comment by Mogztter** [comment]
I've created the repository: https://github.com/Mogztter/asciidoctor-opal-node-runtime
I'm using a branch named `asciidoctor` to produce a smaller Opal runtime: https://github.com/Mogztter/opal/tree/asciidoctor

With this commit https://github.com/Mogztter/opal/commit/6cb6a318cccbcbcb1c2dde15d9e769d5e7f18b42 _opal.js_ is  676 KB / 21440 lines (from 741 KB / 23281 lines)

**Comment by Mogztter** [comment]
Down to 656 KB / 20888 lines with the removal of `Kernel#sprintf` (`Kernel#format`)
