### ISSUE TITLE
how to implement asciidoctor in angular 6 project to generate documentation?

### ISSUE THREAD

**Issue by Himanshu-Singhal** [asciidoctor/asciidoctor.js#666]

**Comment by Mogztter** [comment]
Hello @Himanshu-Singhal, could you please elaborate ? 
If you want to submit an issue, it's the right place but I need more context to be able to fix it.

If you just need help, please ask here: https://gitter.im/asciidoctor/asciidoctor.js

**Comment by Mogztter** [comment]
I'm closing since it's not an issue but a question/support.
Discussion started on Gitter :wink:
