### ISSUE TITLE
Publish Asciidoctor as an ES6 module

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#686]
http://2ality.com/2014/09/es6-modules-final.html

**Comment by Mogztter** [comment]
Open question, should we keep the "constructor" to configure the Asciidoctor instance ?
```js
// module.js
export default function(options) {
  return {
    // actual module
  }
}

// main.js
import Asciidoctor from 'asciidoctor.js';
const asciidoctor = Asciidoctor(options)
```

Should we provide a default instance:

```js
export function convert(input, options) {
  // ...
}

// main.js
import { convert } from 'asciidoctor.js';
```

**Comment by Mogztter** [comment]
All things considered I think we should keep UMD (and even if we decide to remove UMD we should create a dedicated issue)

**Comment by Mogztter** [comment]
I did some tests but I think the first step is to convert Opal to an ES6 module. The main reason is that Opal uses `window` global object:

https://github.com/Mogztter/opal-node-runtime/blob/cde4c78099358ef47cc30b41f699ee56ff40d5e3/src/opal.js#L16

In the code above `this` is the `window` but in an ES6 module the top level `this` is `undefined`: http://exploringjs.com/es6/ch_modules.html#_browsers-scripts-versus-modules

**Comment by mojavelinux** [comment]
> should we keep the "constructor" to configure the Asciidoctor instance 

I never been very fond of the constructor. My instinct is to type:

```
const asciidoctor = require('asciidoctor')
```

So perhaps a default instance is in order.

**Comment by Mogztter** [comment]
> I never been very fond of the constructor. My instinct is to type

Me neither but the whole point of the constructor was to provide a way to be explicit about the runtime environment so we can load the appropriated modules.
But we should probably revisit this part of the code. I think we should drop `phantomjs` and `spidermonkey` support and just provide a dedicated version of Asciidoctor.js for the following platform:
* Node.js
* Browser
* GraalVM

Electron is just Node.js with literally 2 lines of JavaScript:
https://github.com/asciidoctor/asciidoctor.js/blob/e44a31981a00c53953c0e5b0ed73588f530c092a/lib/asciidoctor/js/opal_ext/electron/io.rb#L1-L3

We could provide a tiny package `@asciidoctor/platform-electron`:

```js
const asciidoctor = require('@asciidoctor/core')
require('@asciidoctor/platform-electron')
```

**Comment by mojavelinux** [comment]
> Me neither but the whole point of the constructor was to provide a way to be explicit about the runtime environment so we can load the appropriated modules.

I certainly get that. I just think we could do using late-binding enhancement or proxying, as you suggested at the end of your comment.

> I think we should drop phantomjs and spidermonkey support

I'm honestly not sure what the right choice is here. These do seem more like experiments for us then real target platforms. Before we had asciidoctor.js working on Node.js, these were very helpful. Perhaps now, not so much.

**Comment by sandrooco** [comment]
The fact that opal's doing some weird stuff with `this` might cause an initialisation issue for us.
@Mogztter Do you have an idea for a quick workaround?

**Comment by Mogztter** [comment]
@sandrooco Not really. Having said that, Opal is making some changes to enable [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode). So the next version should be more contained.

Could you please share the exact issue? Maybe there's a workaround for your specific issue.

**Comment by sandrooco** [comment]
@Mogztter If we use `import * as asciidoctor from 'asciidoctor';` the initialization doesn't work, even only on page load (without using it in the app code). It breaks at asciidoctor.js:1869:

> `asciidoctor.js:1869 Uncaught TypeError: Cannot assign to read only property 'length' of function 'function() {
>       var block = alias.$$p, args, i, ii;...`
That's why I think it has something to do with the `this` thing.

**Comment by Mogztter** [comment]
> asciidoctor.js:1869 Uncaught TypeError: Cannot assign to read only property 'length' of function 'function() { var block = alias.$$p, args, i, ii;...

This error is thrown because you are running in strict-mode and Opal is not yet compliant. Hopefully it will be the case soon enough.
Unfortunately I don't have a workaround in this case.
Please note that modules are automatically in strict-mode: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Strict_mode_for_modules

**Comment by sandrooco** [comment]
Does that mean we can‘t use the library in an Angular project at all? Because if I go the `require()`-way it isn‘t treated as module but still my Angular Pipe is one.
Am I missing something?

**Comment by Mogztter** [comment]
Are you using Typescript? I think it's possible to configure Angular/TypeScript to not add the `'use strict'` directive:

* `--noImplicitUseStrict`: https://www.typescriptlang.org/docs/handbook/compiler-options.html
* `"noImplicitUseStrict": true` to `"compilerOptions"`: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by sandrooco** [comment]
Yes, I am. I will try that tomorrow.
Thanks for the quick feedback!

**Comment by oncletom** [comment]
Hi!

I was about to use Asciidoctor during a workshop, and it reminded me of this "issue". What are the steps to publish `@asciidoctor/core` as an ES Module?

I see Opal does the build, but I wonder if it has ESM build options, or if another tool has to be inserted to derive an ESM build from the regular build.

Typically I would type this kind of code in a browser:

```js
import Asciidoctor from 'https://unpkg.com/@asciidoctor/core@2.0.3/dist/browser/asciidoctor.esm.js'

const asciidoc = new Asciidoctor()

document.body.innerHTML = asciidoc.convert('= Title')
```

As an "improvement", top level functions would help skip the constructor without shoving it either:

```js
import {convert} from 'https://unpkg.com/@asciidoctor/core@2.0.3/dist/browser/asciidoctor.esm.js'


document.body.innerHTML = convert('= Title')
```

**Comment by oncletom** [comment]
If I reply to myself, I guess it relies on opal/opal#1976 being merged.

**Comment by Mogztter** [comment]
Yes, ESM means strict mode and since we rely on Opal we need the Opal runtime to be strict-compliant (I believe it's the case now) then we can transpile Asciidoctor using a strict-compliant compiler and then we can create a proper ESM module :crossed_fingers: 

There's an open issue to use the latest version of Opal that includes a "strict-mode" flag to produce stri

**Comment by MartinSenne** [comment]
Hi all, hi @Mogztter ,

any update on the ES6 module?

To my current understanding, current implementation allows for inclusion of asciidoc.js via `<script>`tag only, correct?

Best and thx

Martin

**Comment by Mogztter** [comment]
Hi @MartinSenne 

I'm trying to bridge the gap between Node.js (CJS) and the browser (ESM) but it's not an easy task. We don't use many dependencies but we need to convert them to ESM.

On the browser it's relatively easy to export Asciidoctor.js as an ESM but it gets complicated quickly if we want to produce a compatible version for Node.js (CJS), Node.js (ESM), Browser (ESM), GraalVM (ESM) and Deno (ESM) from the same code base without too many hacks.

> To my current understanding, current implementation allows for inclusion of asciidoc.js via <script>tag only, correct?

Yes... but it should also work if you are using a web bundler (like Webpack, rollup...)

**Comment by Mogztter** [comment]
I just found an issue with the template converter (introduced in Asciidoctor.js 2.2.0). We are using dynamic require to load an optional helper file. If we want to replace this require with import then the function returns a Promise: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports

Unfortunately, Asciidoctor.js is transpiled from Asciidoctor Ruby and the code is not asynchronous, so we cannot use a Promise :disappointed:

**Comment by Mogztter** [comment]
For now I don't think it brings much value to convert `dist/node/asciidoctor.js` from a CommonJS module to an ECMAScript module.

The following will be possible in the next version (3.0.0) in a browser environment:

```js
import Asciidoctor from 'https://unpkg.com/@asciidoctor/core@3.0.0/dist/browser/asciidoctor.js'

const asciidoc = new Asciidoctor()

document.body.innerHTML = asciidoc.convert('= Title')
```

> As an "improvement", top level functions would help skip the constructor without shoving it either

Follow-up issue: #802

**Comment by b177y** [comment]
Is there any temporary solution to this? I am unable to use `@asciidoctor/core` with Svelte

Code:
```svelte
<script>
    export let content;
    import Asciidoctor from '@asciidoctor/core';
    const processor = Asciidoctor();
    
    let rendered;

    $: rendered = processor.convert(content)
</script>
```

Getting the following error in the console:
```
Uncaught TypeError: "length" is read-only              asciidoctor.js:1869:4
    node_modules @asciidoctor_core.js:1055
    node_modules @asciidoctor_core.js:1766
    node_modules @asciidoctor_core.js:2319
    node_modules @asciidoctor_core.js:1363
    node_modules @asciidoctor_core.js:1384
    node_modules @asciidoctor_core.js:3789
    node_modules @asciidoctor_core.js:1363
    node_modules @asciidoctor_core.js:1384
    node_modules @asciidoctor_core.js:15879
    node_modules @asciidoctor_core.js:15889
    __require2 chunk-IHTDASF6.js:17
    <anonymous> @asciidoctor_core:1
asciidoctor.js:1869:4
    alias asciidoctor.js:1869
    node_modules/@asciidoctor/core/dist/browser/asciidoctor.js/Opal.modules["corelib/module"]/< asciidoctor.js:2809
    "corelib/module" asciidoctor.js:3558
    load asciidoctor.js:2314
    require asciidoctor.js:2342
    "opal/base" asciidoctor.js:5469
    load asciidoctor.js:2314
    require asciidoctor.js:2342
    js asciidoctor.js:20069
    js asciidoctor.js:20079
    __require2 chunk-IHTDASF6.js:17
    <anonymous> @asciidoctor_core:1
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    InnerModuleEvaluation self-hosted:2381
    evaluation self-hosted:2332
```
