### ISSUE TITLE
Consider renaming the package

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#687]
The current name `asciidoctor.js` is inconsistent with others npm packages. More precisely, the `.js` suffix is redundant.

My instinct is to type:

```js
const asciidoctor = require('asciidoctor')
```

Furthermore, there's quite a few "asciidoctor" packages published on npmjs: https://www.npmjs.com/search?q=asciidoctor

To help users finding the right package, we could publish "official" package in the `@asciidoctor` organization:

* `@asciidoctor/asciidoctor`
* `@asciidoctor/cli`
* `@asciidoctor/backend-pdf`
* `@asciidoctor/backend-revealjs`
* `@asciidoctor/backend-bespoke`
* ...

And here's a few proposals, we are considering:
* `asciidoctor`
* `@asciidoctor/asciidoctor`
* `@asciidoctor/core`
* `@asciidoctor/processor`

What do you think ? should we do it for 2.0.0 ?

**Comment by oncletom** [comment]
What's the state of thinking of using the organisation name? Like `@asciidoctor/cli`, `@asciidoctor/converter`, etc.?

**Comment by Mogztter** [comment]
> What's the state of thinking of using the organisation name

Still on the table!
Though I'm not sure about `@asciidoctor/converter`.
What do you think @mojavelinux ?

**Comment by oncletom** [comment]
The 2 main projects I know of would use `core`: [`@angular/core`](https://npmjs.com/@angular/core), [`@babel/core`](https://npmjs.com/@babel/core).

Some others like [`gatsby`](https://npmjs.com/gatsby) use the non-prefixed for the main package, and the scoped packages for dependencies and other official stuff.

What I like with the gatsby approach is the CLI is bundled with the main package, so as it can be seemlessly used with `npx` to run command without installing the package.

**Comment by Mogztter** [comment]
> The 2 main projects I know of would use core: @angular/core, @babel/core.

:+1:

> Some others like gatsby use the non-prefixed for the main package, and the scoped packages for dependencies and other official stuff.

I tend to prefer the first approach.

> (This is a segway of the original topic) What I like with the gatsby approach is the CLI is bundled with the main package, so as it can be seemlessly used with npx to run command without installing the package.

I'm not familiar with `npx` but you can't do the same with Angular using `npx @angular/cli` no ? So if we publish `@asciidoctor/cli` that would work right ? Arguably it's not as simple as `npx asciidoctor` but at the same time I don't want to add CLI dependencies in the core package.

**Comment by mojavelinux** [comment]
I do think it's the right time to switch the package name / structure. Though we may want to consider publishing an update to the asciidoctor.js package that communicates this change. Otherwise, we run into the problem where people following that package don't know a newer version is available under a different name.

I'm partial to the gatsby approach (and have considered this for Antora as well). The top-level package is just a bundle of other packages...and gives us control over what packages are included. It's the coarse-grained install. But the actual packages would be under the namespace.

For the package with the main code, I'd probably go with either `@asciidoctor/core`, `@asciidoctor/processor`, or `@asciidoctor/asciidoctor`. I'm with Guillaume that I don't like "converter" since it includes a lot more than that (in fact, it provides the extension API too).

**Comment by Mogztter** [comment]
> Though we may want to consider publishing an update to the asciidoctor.js package that communicates this change

You mean with a deprecation warning? https://www.npmjs.com/package/jade (still 578 864 weekly downloads though)

**Comment by mojavelinux** [comment]
@Mogztter Another possible idea is to not rename the top-level package, but just repurpose it as a meta package. That way, the following two statements would be the same:

```js
const asciidoctor = require('asciidoctor.js')
```

```js
const asciidoctor = require('@asciidoctor/core')
```

That doesn't give us `require('asciidoctor')`, but it does provide a smooth transition to the namespaced packages.

**Comment by mojavelinux** [comment]
Btw, the converters would be named `converter-*`, not `backend-*`. :wink:

**Comment by mojavelinux** [comment]
> You mean with a deprecation warning?

I don't like nags. I meant updating the README to say that the package was moved.

**Comment by Mogztter** [comment]
>  Another possible idea is to not rename the top-level package, but just repurpose it as a meta package. That way, the following two statements would be the same:

Interesting, on Twitter @jeantil suggested the same approach.
Is [Lerna](https://github.com/lerna/lerna) the way to go if we want to publish multiple packages ? (ie. `asciidoctor.js` and `@asciidoctor/core` using the same version).
I'm a bit afraid to switch to Lerna because our release process is fully automated and there's a high chance to mess up the first release... but I guess that's what release candidates are for :wink: 

> That doesn't give us require('asciidoctor'), but it does provide a smooth transition to the namespaced packages.

I still think we should remove this `.js` suffix but we could do that later... Or since the meta package is actually backward compatible, we could do both, rename `asciidoctor.js` to `asciidoctor` and introduce `@asciidoctor/core`.

> I don't like nags. I meant updating the README to say that the package was moved.

:+1: 

> Btw, the converters would be named converter-*, not backend-*.

I wish there was only the term converter. As far as I understand "backend" is really just the output format of the converter. But it may be just me :wink:

**Comment by mojavelinux** [comment]
> As far as I understand "backend" is really just the output format of the converter.

"backend" is a keyword intent to create an output format. A converter satisfies that intent. It is an indirection, but I think a reasonable one.

**Comment by mojavelinux** [comment]
I would not recommend Lerna, esp for an existing project. It's both rigid and brittle, so you'll spend more time trying to make it work than using it. You're better off with your own scripts.

**Comment by mojavelinux** [comment]
> I still think we should remove this .js suffix but we could do that later

If we're going to do it, I think now is the time. We just have to accept that the downloads are going to be split for awhile.

**Comment by Mogztter** [comment]
> If we're going to do it, I think now is the time. We just have to accept that the downloads are going to be split for awhile.

:+1: 

> I would not recommend Lerna, esp for an existing project. It's both rigid and brittle, so you'll spend more time trying to make it work than using it. You're better off with your own scripts.

Ok thanks for sharing.

On a related topic do you think it's a good idea to split "core" in multiple packages ?
I don't want to introduce this change now but it could further reduce the size of Asciidoctor.js when you don't use all the functionalities:

- asciidoctor/loader
- asciidoctor/converter
- asciidoctor/converter-html5
- asciidoctor/converter-manpage
- asciidoctor/converter-composite
- asciidoctor/converter-template
- asciidoctor/converter-docbook5
- asciidoctor/extensions

And of course the meta package will include everything that Asciidoctor includes.
That brings another interesting question, should we include https://github.com/asciidoctor/asciidoctor-cli.js by default in the meta package ?

**Comment by mojavelinux** [comment]
If you think that would make the package easier to use and to manage its size, then I'd certainly consider it.

> asciidoctor/loader

I'd name this asciidoctor/parser.

> should we include asciidoctor/asciidoctor-cli.js by default in the meta package ?

I'd say so. It's part of Asciidoctor core, so it seems reasonable to do so.
