### ISSUE TITLE
Cite doesn't work correctly when using asciidoctor.js

### ISSUE THREAD

**Issue by sindzicat** [asciidoctor/asciidoctor.js#701]
Hello!

Minimal working example:

```
= Test document
:nofooter:
:c: 0

Some long text [<<cite-1>>]. Other text [<<cite-2>>].

++++
<style>
    body {background-color:white;color:rgba(0,0,0,0.8)}
</style>
++++

== Bibliography

. [[cite-1,{counter:c}]]
    Cite 1.

. [[cite-2,{counter:c}]]
    Cite 2.
```

When `use asciidoctor.js` is checked:

![image](https://user-images.githubusercontent.com/33900895/54803239-c0c1e180-4c7f-11e9-9c51-769d41513d47.png)

When I use Ruby version of Asciidoctor (`use asciidoctor.js` is unchecked):

![image](https://user-images.githubusercontent.com/33900895/54803302-04b4e680-4c80-11e9-9aff-422692a497e5.png)

-- Andrey.

**Comment by mojavelinux** [comment]
I think this is specifically an Atom plugin issue. We're still waiting on the upgrade to Asciidoctor.js 1.5.9, I think. Can you verify the version using the `{asciidoctor-version}` attribute reference in the document?

Here's the related issue: https://github.com/asciidoctor/atom-asciidoc-preview/pull/290

**Comment by sindzicat** [comment]
Sorry, but this is VS Code, not Atom.

> Can you verify the version using the {asciidoctor-version} attribute reference in the document?

1.5.6.2

**Comment by mojavelinux** [comment]
Oops. Correction. I meant VSCode ;)

So there's your issue. The version of Asciidoctor.js is outdated. I would
recommend opening an issue in that project.

**Comment by Mogztter** [comment]
@mojavelinux Done that, and I've submitted a pull request to upgrade to 1.5.9.
@sindzicat Hopefully it should resolve your issue.

I'm closing this issue in favor of https://github.com/asciidoctor/asciidoctor-vscode/issues/176

**Comment by mojavelinux** [comment]
:+1:

**Comment by sindzicat** [comment]
@mojavelinux, @Mogztter, many thanks! :+1:

**Comment by MatteoCampinoti94** [comment]
Thank you @mojavelinux @Mogztter !
I'll merge the change now/
