### ISSUE TITLE
SyntaxHighlighter access to document?

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#709]
Hello,

I'm trying to convert an existing syntax highlighter extension to the new `SyntaxHighlighter` introduced in `asciidoctor@2` (because the legacy syntax does not work anymore, I have to explicitly register the syntax highlighter).

How can I access, once, the document to grab one of its attributes? The constructor does not have access to it and it's not clear to me what methods I have access to (aside of the ones mentioned in the JSDoc header).

On a side note, I've tried to include docinfo stuff but having this piece of code did not suffice:

```js
module.exports = class PrismHighlighter {
  format () { /* ... */ }

  hasDocinfo () {
    return true;
  }

  docinfo (doc) {
    if (doc.backend !== 'html5') {
      return '';
    }

    // ...
  }
}
```

**Comment by mojavelinux** [comment]
The document is passed as an option to the constructor of the syntax highlighter adapter. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/document.rb#L1225-L1231

I'm not aware of how this is mapped in Asciidoctor.js.

**Comment by Mogztter** [comment]
> I'm not aware of how this is mapped in Asciidoctor.js.

I'm still trying to figure out how to wire the special `constructor` method. The issue is that Opal will instantiate the class but at the same time we need to call the `constructor` method with the existing instance (created by Opal)...

You can try the following but with no guarantee as it's very hacky at the moment so I won't be surprise if it's not working as expected:

```js
module.exports = class PrismHighlighter {
  constructor(name, backend, opts) => {
    this.backend = backend
  }

  docinfo () {
    if (this.backend !== 'html5') {
      return '';
    }
    // ...
  }
}
```

If you are interessed here's the code that does the wiring:
https://github.com/asciidoctor/asciidoctor.js/blob/8aa8a4c318073cabb44d2daf2bde8f02e953721b/packages/core/src/asciidoctor-core-api.js#L73-L80

You can also try to use the native Ruby API or declare the PrismHighlighter as follow:

```js
asciidoctor.SyntaxHighlighter.register('prism', {
  initialize: (name, backend, opts) => {
    this.backend = backend
    this.super()
  },
  docinfo () {
    if (this.backend !== 'html5') {
      return ''
    }
    // ...
  }
})
```

**Comment by oncletom** [comment]
Thank you for the pointers :-)

I tried with the `initializer()` method and with `constructor()` but none of them receive any document related information. I suspect it's too soon in the document lifecycle — unless the constructor is called when `asciidoctor.convert()` / `asciidoctor.load()` are invoked?

At the moment, `docinfo()` is not called, neither is `hasDocinfo()` 🤔

**Comment by Mogztter** [comment]
The API is experimental and for now I only have two tests to check that `format` is called.

Since you're interested in this API, feel free to provide tests cases or even fixes to the implementation. I can give you pointers 😄

**Comment by Mogztter** [comment]
@oncletom I've published a third release candidate. Could you please try again with this version ?

**Comment by oncletom** [comment]
https://github.com/oncletom/asciidoctor-prism-extension/commit/c48e689f05e50727546f2626ff974ff0fe713a5d 👌
