### ISSUE TITLE
Support for a "lang" option

### ISSUE THREAD

**Issue by gautaz** [asciidoctor/asciidoctor.js#714]
Hello,

As stated in [this Asciidoctor language support documentation](https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/language-support.adoc), there is a way to localize the document conversion.

I'm most certainly missing something but I was unable to find a way to do this through the current [`asciidoctor.js` API options](https://asciidoctor-docs.netlify.com/asciidoctor.js/processor/convert-options/), could someone point me to the right documentation in order to specify the locale?

**Comment by Mogztter** [comment]
Hello @gautaz 

Asciidoctor.js does not package locales but you can copy them from https://github.com/asciidoctor/asciidoctor/tree/master/data/locale and then add `include::locale/attributes.adoc[]` in your document.


> I'm most certainly missing something but I was unable to find a way to do this through the current asciidoctor.js API options, could someone point me to the right documentation in order to specify the locale?

When using the API you can pass the lang as an attribute:


```js
asciidoctor.convert(input, { attributes: { lang: 'de' } })
```

**Comment by gautaz** [comment]
Oh I did not realize that the `-lang` option of `asciidoctor.js` was in fact setting the `lang` attribute.

Thanks @Mogztter!

**Comment by Mogztter** [comment]
You're welcome.
At some point we might provide this feature as built-in (ie. automatically load the locale attributes file).

See https://github.com/asciidoctor/asciidoctor/issues/1129#issuecomment-432935284
