### ISSUE TITLE
SyntaxHighlighter provides an object when the source language is not specified

### ISSUE THREAD

**Issue by oncletom** [asciidoctor/asciidoctor.js#715]
With `@asciidoctor/core@2.0.0-rc.3`, a custom `SyntaxHighlighter` and this listing:

```adoc
[source]
.options/zones.txt
----
Europe/London
America/New_York
----
```

In this case, the `format (node, lang)`'s `lang` parameter is equal to `constructor { '$$id': 4, apply: [Function], call: [Function] }`.

I expected the highlighter not to be called — or a blank string at best.

**Comment by mojavelinux** [comment]
This is one of those cases where null coercion is needed.

(Opal does this because in Ruby, nil is an object, not really nil. I wish there was true nil in Ruby like in JavaScript. What we've done in Asciidoctor.js is coerce these cases to null so you get the behavior you expect).

**Comment by Mogztter** [comment]
I will define a proxy function to convert it to `undefined`. I've also added a comment in the Prism highlighter repository: https://github.com/oncletom/asciidoctor-prism-extension/commit/c48e689f05e50727546f2626ff974ff0fe713a5d#r33064983 to convert the Ruby Hash to a JS object.

The API will feel more like a pure JS API.

**Comment by Mogztter** [comment]
@mojavelinux How should we convert the "opts.callouts" argument ? https://github.com/asciidoctor/asciidoctor/blob/5c32e8826a326a3363acb91bdb72ed90d5c4fcbb/lib/asciidoctor/syntax_highlighter.rb#L54 because JSON only allows key names to be string.

Also with the following AsciiDoc content, I get the following `callouts` (converted to JSON):


```
[source,ruby]
----
puts 'Hello, World!' <1>
----
<1> Prints 'Hello, World!'
```

```js
// callouts as JSON
{
  "1": [ [ undefined, "1" ] ]
}
```

But I don't understand why it's an array of array and why there's a `Opal.nil` (undefined) value ?

**Comment by Mogztter** [comment]
After some debug here's why there's an array of array.
The following content:
```
[source,ruby]
----
puts 'Hello, World!' # <1>
<2>
puts 'Bonjour!' # <3> <4>
----
<1> Prints 'Hello, World!'
<2> ...
<3> Prints 'Bonjour!!'
<4> Bonjour means Hello in French
```

produces:

```js
// callouts as JSON
{
  "0": [ [ "# ", "1" ] ],
  "1": [ [ undefined, "2" ] ],
  "2": [ [ "# ", "3" ], [ undefined, "4" ] ]
}
```

**Comment by mojavelinux** [comment]
To be honest, the callout list is very low-level and internal. And the format could change. It's not just holding the callouts, but the offset information. Under normal circumstances, you should never even need it. It's just there if you're making a hightly specialized extension that needs this low-level info. I don't think it should be mapped right now.

**Comment by mojavelinux** [comment]
(If we did change the data format, it should happen upstream first. I don't think Asciidoctor.js should be introducing a change of its own).

**Comment by Mogztter** [comment]
Fair enough.
For now I've just converted the `Hash` to `JSON` and replaced `Opal.nil` by `undefined`.
