### ISSUE TITLE
Consolidate build scripts

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#72]
We have some (a lot of?) overlap between the grunt and rake tasks. Consolidate the build scripts so that we are doing everything in grunt except for what has to be done in rake. The rake parts should be limited to executing Opal.

Ideally, we could even eliminate rake and just use the opal command directly, but that's not a hard requirement.

**Comment by Mogztter** [comment]
> Ideally, we could even eliminate rake and just use the opal command directly, but that's not a hard requirement.

That would be great ! I've just installed a new development environment and the initial setup is way too long :smile: 
I think we need to stay with Javascript tools to build Asciidoctor.js (that make more sense). AFAIK Opal compiler can be run in Javascript but I didn't find any documentation on how to do it... anyway I will give it a try !

**Comment by mojavelinux** [comment]
Worst case scenario, we can call opal from the command line. I think that many parts of Opal use Ruby, however, so I'm not sure it can be used exclusively from JavaScript. It definitely makes more sense to drive everything through Grunt, though. Rake seems to be adding a layer of unneeded complexity now that we have Grunt doing things.

**Comment by mojavelinux** [comment]
Now that we've moved to npm scripts, we should reevaluate where we are with this request and if any more work is needed. I think that npm should be able to invoke opal from the commandline to move past the Rakefile, though we do perform some processing in that file that may still be important. At the very least we'd need to reproduce it so we get the same results.

**Comment by Mogztter** [comment]
@mojavelinux I've done some testing and I think we can achieve the same result with Opal command line. Here's the command I'm using to generate `asciidoctor_example.js`:

```javascript
child_process.execSync('opal --compile examples/asciidoctor_example.rb --dynamic-require warning --no-opal > build/asciidoctor_example.js');
```

The only difference is that `asciidoctor_example` is not in a module but loaded automatically by Opal. More specifically:

```diff
+(function(Opal) {
-Opal.modules["asciidoctor_example"] = function(Opal) {
```

Do you know if it is possible from the command line to put `asciidoctor_example` in a module ?

And here the command line to generate `asciidoctor-docbook5.js`:
```javascript
opal --compile lib/asciidoctor/opal_ext.rb -I lib -I asciidoctor -g asciidoctor -r asciidoctor/converter/docbook5 --dynamic-require ignore > asciidoctor-docbook5.js
```

To track progress, I will create an issue to rewrite Rake examples task in Node.

**Comment by mojavelinux** [comment]
Excellent!

> Do you know if it is possible from the command line to put asciidoctor_example in a module?

We could just wrap the Ruby code inside a module. Aside from that, we'd have to check with the Opal folks.

**Comment by mojavelinux** [comment]
@Mogztter The `examples` task is failing right now. It claims that the "native" import cannot be found. How do we load Opal's native library in this new build system?

```
npm run examples
```

**Comment by Mogztter** [comment]
@mojavelinux On Windows, I have another issue, could you please post the stack trace ? I think we need to add the "native" library to [the Opal node runtime](https://github.com/Mogztter/opal-node-runtime/tree/master/src).

**Comment by mojavelinux** [comment]
Indeed.

```
compile examples
 - compile examples/asciidoctor_example.rb

$ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/node_modules/opal-runtime/src/opal.js:4627
      throw exception;
      ^
MissingRequire: can't find file: "native" in ["$ASCIIDOCTOR_JS_DIR/opal", "$ASCIIDOCTOR_JS_DIR/stdlib", "$ASCIIDOCTOR_JS_DIR", "$ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/src/stdlib", "$ASCIIDOCTOR_JS_DIR/lib", "$ASCIIDOCTOR_JS_DIR/build/asciidoctor/lib"]
    at Opal.defs.TMP_1 [as $new] ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/node_modules/opal-runtime/src/opal.js:4853:15)
    at ːexception ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/node_modules/opal-runtime/src/opal.js:4871:31)
    at $Builder.ːraise ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/node_modules/opal-runtime/src/opal.js:4612:31)
    at $Builder.ːread ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/src/opal-builder.js:16298:108)
    at $ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/src/opal-builder.js:16313:23
    at $Builder.ːprocess_require ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/src/opal-builder.js:16314:26)
    at $a.$$p.TMP_5 ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/src/opal-builder.js:16186:23)
    at Opal.yield1 ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/node_modules/opal-runtime/src/opal.js:1198:14)
    at Array.ːcollect ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/node_modules/opal-runtime/src/opal.js:10944:26)
    at $Builder.ːbuild_str ($ASCIIDOCTOR_JS_DIR/node_modules/opal-compiler/src/opal-builder.js:16186:103)
```

Keep in mind that only the examples uses the native library, so this is specific to the examples.

**Comment by mojavelinux** [comment]
I think you've got the right idea. I'm curious, though, how does opal.js get into the opal-node-runtime project? Are you adding that manually?

**Comment by Mogztter** [comment]
> I think you've got the right idea. I'm curious, though, how does opal.js get into the opal-node-runtime project? Are you adding that manually?

Yes, I'm building Opal from a tag to produce opal.js.
I also need to copy/paste required Ruby classes in `stdlib` otherwise the Opal compiler is unable to find them.

**Comment by Mogztter** [comment]
I've just added the `native` library and published version of `opal-node-compiler@0.10.1-integration2`: https://github.com/Mogztter/opal-node-compiler/commit/37fef57eebda24beb0bf9f10344e298da9fdf14a

This is now resolved in https://github.com/asciidoctor/asciidoctor.js/commit/072c487d33a83a2ae2e39902521812f15f82dd43

Maybe we should run this npm task on Travis ?

**Comment by mojavelinux** [comment]
> Yes, I'm building Opal from a tag to produce opal.js.

Thanks for clarifying. The reason I ask is because I think this should be automated, which effectively documents the steps that need to be taken.

> Maybe we should run this npm task on Travis ?

Definitely. (We could even push the examples to the gh-pages branch so it's possible to try the examples without having to run the build).

**Comment by Mogztter** [comment]
Take and Grunt are gone, let's close this issue 😎

**Comment by mojavelinux** [comment]
:+1:
