### ISSUE TITLE
Create a binary in the asciidoctor package

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#726]
It could be useful to create a binary in the `asciidoctor` package:

```js
#!/usr/bin/env node

'use strict'

process.title = 'asciidoctor'
const cli = require('@asciidoctor/cli')
cli.run(process.argv)
```

To make it work, we will probably need to update the `main` field in the package.json of the `@asciidoctor/cli` package to `"lib/cli.js"`: https://github.com/asciidoctor/asciidoctor-cli.js/blob/ddf2793d211586b493c424c403679f375bfabaf8/package.json#L5

If we do that a user could convert a document using Asciidoctor.js with a single command line:

```
npx asciidoctor doc.adoc
```

Please note that if the command `asciidoctor` is already in the PATH then it will use the command found. If you want to make sure that you are using Asciidoctor.js then you will have to use:

```
npx --ignore-existing asciidoctor doc.adoc
```

I'm not really familiar with `npx`, what do you think @oncletom ?

**Comment by oncletom** [comment]
I didn't know about `--ignore-existing`!

I feel it's a good thing to proxy the CLI via the `asciidoctor`. `npx` is handy to demonstrate things. And it's works the same if you have `asciidoctor` as a project dependency, it makes the CLI easy to call within `npm scripts`.
