### ISSUE TITLE
Inline macro extension is not activated

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#729]
Hi,

I have been preparing the new  AsciidocFX's extensions, and it looks inline macro extension is not activated when I write the extension like the following:

```js
asciidoctor.Extensions.register(function () {
    this.inlineMacro("extname", function () {
        let self = this;
        self.process(function (parent, target, attrs) {
            console.log("i'm here") // 
            return ...
        });
    });
});
```

`extname:[hello]` with this usage, I expect that the process method must be called, but it doesn't. (might be same also for block macro) What can be wrong here ? Thanks.

**Comment by Mogztter** [comment]
The code looks fine and we have a similar extension in the tests suite: https://github.com/asciidoctor/asciidoctor.js/blob/master/packages/core/spec/share/extensions/smiley-inline-macro.js

I'll add a test with an inline macro without target. Does it work  with `extname:something[hello]` ?

Could you please add a simple reproduction case ? (ie. a standalone Node.js script so I can reproduce and quickly fix this issue). 

Thanks 👍

**Comment by rahmanusta** [comment]
It looks it works with a target, how can I configure it to work with no-target? Thanks 

```
const asciidoctor = require('asciidoctor')()

asciidoctor.Extensions.register(function () {
    this.inlineMacro("extname",function () {
        let self = this;
        self.process(function (parent, target, attrs) {
            console.log("i'm here");
            return null;
        });
    });
});

const content = '==Extension test \n Extension: extname:something[hello] ';

const html = asciidoctor.convert(content);

console.log(html);
```

**Comment by Mogztter** [comment]
I think you need to use `$match_format('short')`: 

https://github.com/asciidoctor/asciidoctor/blob/e94858e840b9ff9358a3227761bd1dee5a312143/test/extensions_test.rb#L1169-L1187

This method is not mapped in Asciidoctor.js so you will have to use `$match_format`.

(not tested)
```js
const asciidoctor = require('asciidoctor')()

asciidoctor.Extensions.register(function () {
    this.inlineMacro("extname",function () {
        let self = this;
        self.$match_format('short')
        self.process(function (parent, target, attrs) {
            console.log("i'm here");
            return null;
        });
    });
});

const content = '==Extension test \n Extension: extname:[hello] ';
const html = asciidoctor.convert(content);
console.log(html);
```

Could you please confirm that the above code is working. If this is the case, I will add a test case and map the method to remove the `$` prefix and use camelCase.

**Comment by rahmanusta** [comment]
Thanks @Mogztter , above code is working with $match_format=short.

It is not directly related to my question but, I'm getting an error when I return an inline image from  the extension below:

```
const asciidoctor = require('asciidoctor')()

asciidoctor.Extensions.register(function () {
    this.inlineMacro("extname", function () {
        let self = this;
        self.$match_format('short')
        self.process(function (parent, target, attrs) {
            console.log("i'm here");
            return self.createInline(parent, "image", "", {target: "http://"}).convert();
        });
    });
});

const content = '==Extension test \n Extension: extname:[hello] ';

const html = asciidoctor.convert(content);

console.log(html);
```

It throws `include?: undefined method `include?' for nil`  error. What is wrong here ?

**Comment by mojavelinux** [comment]
As of Asciidoctor.js 2, you should not call convert directly on the return value. Instead, just return the newly created node.

```
return self.createInline(parent, "image", "", {target: "http://"});
```

**Comment by mojavelinux** [comment]
When you create an image, you must provide a non-nil alt attribute.

**Comment by Mogztter** [comment]
@rahmanusta Do you have the full stacktrace ? 

> When you create an image, you must provide a non-nil alt attribute.

In Asciidoctor Ruby I found the following code:

https://github.com/asciidoctor/asciidoctor/blob/cfe1c7c586e7845a018433fab1b31994350e4af6/lib/asciidoctor/extensions.rb#L195

If `alt` is not defined then `target` will be used.

**Comment by mojavelinux** [comment]
Yes, but only if you are using the image helper specifically. (Currently, there is no helper for an inline image).

I went ahead and updated core so the alt isn't required. It will just output an empty attribute in this case...but at least it won't fail. See https://github.com/asciidoctor/asciidoctor/commit/cfe1c7c586e7845a018433fab1b31994350e4af6

**Comment by Mogztter** [comment]
Perfect thanks 👍

**Comment by Mogztter** [comment]
@rahmanusta I've mapped the function `matchFormat`, so in the next version, you will be able to use it.

**Comment by rahmanusta** [comment]
> @rahmanusta I've mapped the function `matchFormat`, so in the next version you will be able to use it.

Thanks @Mogztter, for the new naming for matchFormat.

**Comment by rahmanusta** [comment]
> Yes, but only if you are using the image helper specifically. (Currently, there is no helper for an inline image).
> 
> I went ahead and updated core so the alt isn't required. It will just output an empty attribute in this case...but at least it won't fail. See [asciidoctor/asciidoctor@cfe1c7c](https://github.com/asciidoctor/asciidoctor/commit/cfe1c7c586e7845a018433fab1b31994350e4af6)

Thanks @mojavelinux for this change.

**Comment by rahmanusta** [comment]
It was really helpful for me to complete changes on Asciidoctor.js plugins in AsciidocFX. Thanks for your all support @mojavelinux @Mogztter.

New version of AsciidocFX is almost ready, with OpenJDK/OpenkJFX 12, and Asciidoctor.js 2x !

**Comment by Mogztter** [comment]
Awesome, looking forward to give it a try 👍
