### ISSUE TITLE
loadFile does not close open file descriptors

### ISSUE THREAD

**Issue by joaompinto** [asciidoctor/asciidoctor.js#732]
This issue was reported on https://github.com/asciidoctor/asciidoctor-vscode/issues/203 .

The behavior for loadFile() regarding open files is not documented, but from the "load" in the method it is reasonable to assume that it should take care of opening/reading/closing files.

The issue can be validated with the following code:
```js
/*
echo "include::file2.adoc[]"  > file1.adoc
echo "ok" > file2.adoc
*/
const asciidoctor = require('asciidoctor.js')()
const sleep = (waitTimeInMs) => new Promise(resolve => setTimeout(resolve, waitTimeInMs));

const options = { safe: 'unsafe', base_dir: "." }
let ascii_doc = asciidoctor.loadFile('file1.adoc', options);
let resultHTML = ascii_doc.convert(options);

console.log("RESULT HTML is" + resultHTML)

// Sleep to be able to check open handles 
sleep(90000).then(() => { });

/* loadFile left the included file handler open
lsof file2.adoc
*/
```

**Comment by joaompinto** [comment]
The issue seems to be specific to the JS port, Ruby Asciidoctor does not have the same behavior:
```ruby
require 'asciidoctor'

document = Asciidoctor.load_file 'file1.adoc',  safe: :safe
html = document.convert
print html
sleep(60)
```
The include file descriptor is not open.

**Comment by mojavelinux** [comment]
You are correct. The load_file method should open and close the file since the file handle is not otherwise accessible. In contrast, the load method does not manage the file handle.

**Comment by Mogztter** [comment]
The code used to read an included document is `reader.call(inc_path, read_mode) {|f| f.read }` (where `reader` is equal to `::File.method :open` and `read_mode` is equal to `FILE_READ_MODE`)

And here's the code used to read the main document `::File.open(filename, FILE_READ_MODE) {|file| load file, options }`

We are using the following implementation for `File.open`: 

https://github.com/opal/opal/blob/de58f538c412ff13c71f8cf303bd16e6ce474e5d/stdlib/nodejs/file.rb#L215-L226

As you can see we ensure that `file.close`. So I don't really know why the included file is not closed...
I will debug the code to understand why.

**Comment by jvalkeal** [comment]
In a [asciidoctor-vscode](https://github.com/asciidoctor/asciidoctor-vscode) I also found similar issue [gh100](https://github.com/asciidoctor/asciidoctor-vscode/issues/100) for windows users where this kind of behaviour is causing more trouble as win fs can lock opened files.

Not sure if it's possible with a transpiled js code to do things differently per OS type but in win it'd be nice to open files with `non-exclusively` mode which would prevent OS to lock those files. This is probably nice-to-have-feature as if file descriptors are closed immediately then you probably would not see further issues even in win.

**Comment by Mogztter** [comment]
@joaompinto I can't reproduce this issue:


```console
$ echo "include::file2.adoc[]"  > file1.adoc       
$ echo "ok" > file2.adoc
$ echo "ko" > file3.adoc
```

**test.js**
```js
const fs = require('fs')
const asciidoctor = require('./asciidoctor-node.js')()

const sleep = (waitTimeInMs) => new Promise(resolve => setTimeout(resolve, waitTimeInMs));

const options = { safe: 'unsafe', base_dir: '.' }
const doc = asciidoctor.loadFile('file1.adoc', options);
const html = doc.convert(options);

console.log("result: " + html)

const fd = fs.openSync(`${__dirname}/file3.adoc`, 'r')
console.log(fd)

// Sleep to be able to check open handles 
sleep(90000).then(() => { 
  fs.closeSync(fd)
});
```

```console
$ node -v 
v10.15.1

$ node test.js
result: <div class="paragraph">
<p>ok</p>
</div>
21
```

While the process is running, I'm using another shell:

```console
$ sudo lsof | grep file1.adoc

$ sudo lsof | grep file2.adoc

$ sudo lsof | grep file3.adoc
node      13312                 guillaume   21r      REG              253,1         6    5930522 /home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/packages/core/build/file3.adoc
node      13312 13313           guillaume   21r      REG              253,1         6    5930522 /home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/packages/core/build/file3.adoc
node      13312 13314           guillaume   21r      REG              253,1         6    5930522 /home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/packages/core/build/file3.adoc
node      13312 13315           guillaume   21r      REG              253,1         6    5930522 /home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/packages/core/build/file3.adoc
node      13312 13316           guillaume   21r      REG              253,1         6    5930522 /home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/packages/core/build/file3.adoc
node      13312 13317           guillaume   21r      REG              253,1         6    5930522 /home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/packages/core/build/file3.adoc
node      13312 13318           guillaume   21r      REG              253,1         6    5930522 /home/guillaume/workspace/opensource/asciidoctor/asciidoctor.js/packages/core/build/file3.adoc
```

As you can see `file1.adoc` and `file2.adoc` are closed. I'm using `file3.adoc` to make sure that `lsof` is working.

**Comment by joaompinto** [comment]
@Mogztter where can I get the asciidoctor-node.js that you are using ? (My test uses the require('asciidoctor.js')(), installed via npm).

**Comment by Mogztter** [comment]
I'm just using the latest version on master but I will try with the released version.

**Comment by Mogztter** [comment]
OH I've just noticed that you are not using Asciidoctor.js 2+
So it's probably a bug in Asciidoctor.js 1.5, could you please try with Asciidoctor.js 2+ ?

**Comment by Mogztter** [comment]
Yep I can confirm that the included file is left open with Asciidoctor.js 1.5 but this issue is resolved in Asciidoctor.js 2+

```console
$ npm i @asciidoctor/core
+ @asciidoctor/core@2.0.3
added 5 packages from 2 contributors and audited 34 packages in 3.645s
found 0 vulnerabilities

```

```diff
-const asciidoctor = require('asciidoctor.js')()
+const asciidoctor = require('@asciidoctor/core')()
```

**Comment by joaompinto** [comment]
I confirm that it fixes the problem, I will update the dependencies on the extension. 
Thanks a lot for the help.
