### ISSUE TITLE
Create a block macro not in a paragraph

### ISSUE THREAD

**Issue by Fenntasy** [asciidoctor/asciidoctor.js#736]
Hi, i'm trying to make a block macro that represent a block with an URL and a HTTP verb, like so: 

```asciidoc
url::http://localhost:8000/api[verb=PATCH]
```

Here is what I have at the moment:

```js
registry.inlineMacro("url", function() {
    this.process(
      (_parent, target, attrs) =>
        `<div class="openblock url-block">
          ${attrs.verb ? `<div class="title">POST</div>` : ""}
          <div class="content">
            <div class="listingblock">
              <div class="content">
                <pre class="highlight">
                  <code>${target}</code>
                </pre>
              </div>
            </div>
          </div>
        </div>`
    )
  })
```

I faked it with an `inlineMacro` as I don't know how to create this HTML properly.

It produces almost what I want but with a caveat: this HTML is inside a `<div class="paragraph">` and I would like to have it be its own block or at least, be inside a section.

I tried changing the `paragraph` context to `section` but this does not seem to work and I don't know where to look in the documentation.
Is it even possible? 

Thanks in advance.

**Comment by Mogztter** [comment]
`<div class="paragraph">` is added because you are using the default doctype `article`: https://asciidoctor.org/docs/user-manual/#document-types

If you have a single line you should use `inline`:

```js
const opts =  { doctype: 'inline', extension_registry: registry }
const html = asciidoctor.convert(`url::http://localhost:8000/api[verb=PATCH]`, opts)
console.log(html)
/*
<div class="openblock url-block">
  <div class="title">POST</div>
    <div class="content">
      <div class="listingblock">
        <div class="content">
          <pre class="highlight">
            <code>:http://localhost:8000/api</code>
          </pre>
        </div>
      </div>
    </div>
  </div>
</div>
*/
```

You should also use `self.createBlock(parent, 'pass', html, attrs, {})` to return a `Block` instead of a `string` object.

**Comment by Fenntasy** [comment]
Thank you!, the `pass` was what I needed, here is my end result:

```js
  registry.blockMacro("url", function() {
    this.process((parent, target, attrs) => {
      return this.createBlock(
        parent,
        "pass",
        `<div class="openblock url-block">
          ${attrs.verb ? `<div class="title">POST</div>` : ""}
          <div class="content">
            <div class="listingblock">
              <div class="content">
                <pre class="highlight">
                  <code>${target}</code>
                </pre>
              </div>
            </div>
          </div>
        </div>`
      )
    })
  })
```

**Comment by mojavelinux** [comment]
I strongly advice against returning a pass block from a macro. That should only be done for quick prototyping or when you are returning a very specific HTML structure.

Instead, you should create a listing block object, then create an open block object, add the listing block object to the blocks of the open block, and return the open block. Stay within the AST.

**Comment by Fenntasy** [comment]
@mojavelinux Thanks for the feedback, I'm trying another go, here's what I got:

```js
  registry.blockMacro("url", function() {
    this.process((parent, target, attrs) => {
      const openBlock = this.createBlock(parent, "open", "", {
        title: attrs.verb,
        style: "url-block",
      })
      const listingblock = this.createBlock(
        openBlock,
        "listing",
        `<code>${target}</code>`,
        { style: "source" }
      )
      openBlock.append(listingblock)
      return openBlock
    })
  })
```

It gives me almost what I got before except for setting the `class="highlight"` to the `pre` in the listing block. I thought setting `style: "source"` could do the trick, looking at the generated attributes for the rest of my document but it does not seem to work.
Do you know what I'm missing? I assume the class is added by the source highlighter but I don't know how I could get it to trigger (or add the class myself).

I would gladly accept any more help 🙂

**Comment by mojavelinux** [comment]
You can't use createBlock to set the title or style. You need to use a direct assignment. So it would look something like this:

```js
  registry.blockMacro("url", function() {
    this.process((parent, target, attrs) => {
      const openBlock = this.createBlock(parent, "open", [], {})
      openBlock.title = attrs.verb
      const listingBlock = this.createBlock(openBlock, "listing", target, {})
      listingBlock.style = 'source'
      openBlock.append(listingBlock)
      return openBlock
    })
  })
```

I'm not sure what you're using target for, but you definitely shouldn't have any HTML in your extension code, so no need to wrap it in `<code>`.

**Comment by mojavelinux** [comment]
@Mogztter I think setTitle and setStyle should be mapped. No?

**Comment by mojavelinux** [comment]
When working with the AST, you have to think about it like you are writing AsciiDoc with the API. If you woudln't use HTML in AsciiDoc, then you wouldn't use HTML in the API.

**Comment by Fenntasy** [comment]
>When working with the AST, you have to think about it like you are writing AsciiDoc with the API. If you woudln't use HTML in AsciiDoc, then you wouldn't use HTML in the API.

Duly noted, thank you!

I have just one question though, this work as I intented (I use the `url-block` class to add some styling):

```js
  registry.blockMacro("url", function() {
    this.process((parent, target, attrs) => {
      const openBlock = this.createBlock(parent, "open", [], {
        style: "url-block",
      })
      openBlock.title = attrs.verb
      const listingBlock = this.createBlock(openBlock, "listing", target, {})
      listingBlock.style = "source"
      openBlock.append(listingBlock)
      return openBlock
    })
  })
```

But this does not work:

```js
      const openBlock = this.createBlock(parent, "open", [], {})
      openBlock.title = attrs.verb
      openBlock.style = "url-block"
```

Which is quite disturbing as this does not work either:

```js
      const listingBlock = this.createBlock(openBlock, "listing", target, { style: "source" })
```

In the case of the open block, I need to set `style` as a member of the option object but in the case of the listing block, I need to use a direct `style` assignation. Is there a reason for those not being equivalent and not working the same way?


>I think setTitle and setStyle should be mapped. No?

I don't know what you mean by mapped but I tried both `openBlock.setTitle(attrs.verb)` and `listingBlock.setStyle("source")` and neither or them work (they throw).

**Comment by mojavelinux** [comment]
> I have just one question though, this work as I intented (I use the url-block class to add some styling):

"style" in AsciiDoc is not a CSS construct. What you're looking for is "role". "role" is an attribute that you set on the block. It becomes the CSS class.

**Comment by mojavelinux** [comment]
> Which is quite disturbing as this does not work either:

style is simply not an option that createBlock accepts. createBlock is a helper function and it doesn't process the style.

**Comment by mojavelinux** [comment]
> I don't know what you mean by mapped but I tried both openBlock.setTitle(attrs.verb) and listingBlock.setStyle("source") and neither or them work (they throw).

That's what I meant.

**Comment by Mogztter** [comment]
> I think setTitle and setStyle should be mapped. No?

@mojavelinux Yes most likely an oversight
