### ISSUE TITLE
How to create a block link?

### ISSUE THREAD

**Issue by Fenntasy** [asciidoctor/asciidoctor.js#744]
Hi, I would like to make a block macro that presents an external link with some added icons and that displays both the URL and the name of the link, something like that:

```asciidoc
external-link::http://github.com[title="GitHub"]
```

For now I'm creating an open block where I'm setting the title and the content with a paragraph block:

```js
function externalUrlMacro(registry) {
  registry.blockMacro("external-link", function() {
    this.process((parent, target, attrs) => {
      const openBlock = this.createBlock(parent, "open", [], {
        role: "external-url",
      })
      openBlock.title = attrs.title
       const contentBlock = this.createBlock(openBlock, "paragraph", target)
       openBlock.append(contentBlock)
      return openBlock
    })
  })
}
```

But I would need to have an `<a>` tag around all that for my macro to be finished and I don't know how to go about this.
Furthermore, I don't know if an open block is the best choice here.

I would appreciate any help :)

**Comment by Mogztter** [comment]
Hello @Fenntasy 

> But I would need to have an <a> tag around all that for my macro to be finished and I don't know how to go about this.

You can use the `createInline` function with an `anchor` context:

```js
asciidoctor.Extensions.register(function () {
  this.blockMacro('external-link', function () {
    const self = this
    self.process(function (parent, target, attrs) {
      let text
      if (attrs.text === '') {
        text = target
      }
      const openBlock = self.createBlock(parent, 'open', [], {role: 'external-url'})
      openBlock.title = attrs.title
      const link = self.createInline(parent, 'anchor', text, {type: 'link', target: target})
      openBlock.append(link)
      return openBlock
    })
  })
})
console.log(asciidoctor.convert('external-link::http://github.com[title="GitHub"]'))
// <div class="openblock external-url">
// <div class="title">GitHub</div>
// <div class="content">
// <a href="http://github.com"></a>
// </div>
// </div>
```

> Furthermore, I don't know if an open block is the best choice here.

Open blocks are the most versatile blocks.
I think the "rule" is to create meaningful blocks.
In your case, the block has a title and a role so I think it's fine to use an open block.

**Comment by Mogztter** [comment]
Ideally we should create a function named `createAnchor` and map it to: https://github.com/asciidoctor/asciidoctor/blob/56e1148f6c424e9a9b21c06612b912039e236215/lib/asciidoctor/extensions.rb#L243

**Comment by Fenntasy** [comment]
I know it's not a good practice to put too much stuff into a link but my goal is to have the whole block inside the `<a>` ^^'. Is it not possible?

But other than that, I don't understand, your code works in the browser but if I try to set it in node, I get that error `Failed to load AsciiDoc document - undefined method `find_by_internal' for #<Asciidoctor::Inline:0x872>`. Do you have an idea of where the problem could come from?

**Comment by Mogztter** [comment]
> I know it's not a good practice to put too much stuff into a link but my goal is to have the whole block inside the <a> ^^'. Is it not possible?

I don't think you can add children to an `Inline` node (ie. an anchor).
One possible solution is to create a custom HTML5 converter to override the `convert_inline_anchor`.
With this solution you don't need to use a block macro or an inline macro. You can write the following:

```adoc
link:http://github.com[title=GitHub,role=external]
```

If the link contains the `external` role (or a `title`) then you can put a `<div>` inside a `<a>` element (otherwise you can call the default HTML5 converter).
If you want to learn how to create a custom converter, please read the documentation: https://asciidoctor-docs.netlify.com/asciidoctor.js/extend/converter/custom-converter/

The other option is to output HTML5 in your extension:

```js
asciidoctor.Extensions.register(function () {
  this.blockMacro('external-link', function () {
    const self = this
    self.process(function (parent, target, attrs) {
      const content = `<div class="title">${attrs.title}</div>`
      const html = `<a href="${target}">${content}</a>`
      return self.createBlock(parent, 'pass', html)
    })
  })
})
```

It's not recommended because now your extension is highly coupled with the backend (ie. it will only work if you convert your document to HTML5).

> But other than that, I don't understand, your code works in the browser but if I try to set it in node, I get that error
Failed to load AsciiDoc document - undefined method `find_by_internal' for #<Asciidoctor::Inline:0x872>
Do you have an idea of where the problem could come from?

No... which version of Node.js are you using ?
It's running fine on [Travis](https://travis-ci.org/asciidoctor/asciidoctor.js/builds/563087619) with Node.js v12.7.0 and v10.16.0.

**Comment by Fenntasy** [comment]
> No... which version of Node.js are you using ?

Sorry, it's a bit weirder than that, it's running on my browser but with gatsby, I'm trying to isolate the problem.

**Comment by Fenntasy** [comment]
So here is a repo that reproduces it. I would totally understand if that was asking too much though: https://github.com/Fenntasy/asciidoc-gatsby-test.

But everything is on this page : https://github.com/Fenntasy/asciidoc-gatsby-test/blob/master/src/pages/index.js I just created an empty gatsby repo and added `asciidoctor` to the dependencies. If you `yarn install` and `yarn start` you would see the error I have.

**Comment by Mogztter** [comment]
The error is not the same, I get:

> asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `style=' for #<Asciidoctor::Inline:0x48e>

This error is thrown because you've declared a block macro but the extension returns an `Inline` node (not a Block). So you should update your code to return a `Block`.

**Comment by Mogztter** [comment]
`createAnchor` was added in https://github.com/asciidoctor/asciidoctor.js/releases/tag/v2.1.0
