### ISSUE TITLE
Cannot render SVGs as <object>

### ISSUE THREAD

**Issue by ghtyrant** [asciidoctor/asciidoctor.js#751]
The Asciidoctor [user manual](https://asciidoctor.org/docs/user-manual/#taming-svgs) claims that `image::myimage.svg[opts=interactive]` will render as `<object type="image/svg+xml" data="myimage.svg"></object>`, so we can have interactive SVGs. In my tests with asciidoctor.js (v2.0.3), this renders as `<img src="myimage.svg">`.

Reproduce it like that:
```
Asciidoctor().convert("image::myimage.svg[opts=interactive]")
```
This will return:
```
<div class="imageblock">
<div class="content">
<img src="myimage.svg" alt="myimage">
</div>
</div>
```

**Comment by mojavelinux** [comment]
You need to set the safe mode to safe. By default, this is not considered a "secure" operation, so you have to be expiclit.

See https://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely and https://asciidoctor.org/docs/user-manual/#set-the-safe-mode-in-the-api

**Comment by ghtyrant** [comment]
Works as expected, thanks for your quick response!
