### ISSUE TITLE
Menu macro breaks other macros later in paragraph

### ISSUE THREAD

**Issue by zwaldowski** [asciidoctor/asciidoctor.js#754]
This is asciidoctor/asciidoctor#3433 and asciidoctor/asciidoctor#3279. Output from asciidoctor.js is from [here](https://gist.github.com/zwaldowski/a7b3257e97f9ce1d786f6cbd9d7247e2)

Strangely, I have confirmed via a debugger that JS is using 2.0.9 with the fix applied from asciidoctor/asciidoctor#3280:

<img width="561" alt="Screen Shot 2019-09-29 at 11 43 55 PM" src="https://user-images.githubusercontent.com/170812/65848245-2d92f400-e313-11e9-90ac-470900a41c81.png">

… but it appears that fix isn't working in the transpile.

**Comment by zwaldowski** [comment]
Actually executing said fixed regex:

```
asciidoctor.InlineMenuMacroRx.exec('menu:Manually Run[] and then menu:Automatically Run[].')
Array(3) ["menu:Manually Run[] and then menu:Automatically Ru…", "Manually Run", "] and then menu:Automatically Run["]
```

So, to Opal, I guess? This yak I'm shaving is going to be bald soon. 😅

**Comment by mojavelinux** [comment]
Aha! There is an error in the regexp in core. It just *happens* to work with Ruby. The problem is that the regexp matches empty string, but then also makes it optional. This seems to confuse the regexp engine in JavaScript. If the fix works in Ruby, I'll go ahead and change it in core.
