### ISSUE TITLE
broken links in docs

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor.js#761]
example: http://asciidoctor.github.io/asciidoctor.js/master/#section
links to github sources (packges...) are broken. They are rendered as

```
https://git@github.com/:asciidoctor/asciidoctor.js/blob/f1b2e32e984fbb3ad2917cd2913327dbb9ad3763/packages/core/src/asciidoctor-core-api.js#L547-L547
```

when you remove the `:` between `github.com/` and `asciidoctor`, you get the correct link.

I already tried to search the repsitory for the `:` but couldn't find one :-) Could it be that antora introduces the `:`?

**Comment by Mogztter** [comment]
The API documentation is generated using https://github.com/documentationjs/documentation from the source code.

Probably a bug or a misconfiguration because the links are auto-generated by the library...

**Comment by Mogztter** [comment]
Good catch, it was indeed an issue in a dependency of documentation:  https://github.com/documentationjs/documentation/issues/1295

Tom just merged my fix and released a new version! :tada:
