### ISSUE TITLE
Produce and publish binaries for the asciidoctor package

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#767]
Using https://github.com/zeit/pkg

```
$ npm install -g pkg
$ cd packages/asciidoctor
$ mkdir dist
```
```console
$ pkg bin/asciidoctor --out-path dist
> pkg@4.4.0
> Targets not specified. Assuming:
  node12-linux-x64, node12-macos-x64, node12-win-x64
```

```console
$ ls dist/
asciidoctor-linux  asciidoctor-macos  asciidoctor-win.exe*
```

```console
$ ./dist/asciidoctor-win.exe --version
Asciidoctor.js 2.0.3 (Asciidoctor 2.0.9) [https://asciidoctor.org]
Runtime Environment (node v12.2.0 on win32)
CLI version 2.0.1
```

**Comment by Mogztter** [comment]
I've added the binaries on the GitHub release page: https://github.com/asciidoctor/asciidoctor.js/releases/tag/v2.0.3

We should probably automate the process using Travis.

**Comment by obilodeau** [comment]
As mentioned on twitter, I would appreciate if the reveal.js converter could be included in that binary release. Ref: https://twitter.com/obilodeau/status/1214944480245276672

**Comment by obilodeau** [comment]
Thinking about it more, maybe the asciidoctor-reveal.js project should be the one to create that binary? Thoughts?

**Comment by Mogztter** [comment]
@obilodeau I think it's the other way around. Asciidoctor.js should not depend on the Asciidoctor reveal.js converter.
That's why I've suggested to produce a binary `asciidoctor-revealjs`: https://github.com/asciidoctor/asciidoctor-reveal.js/issues/259

The Asciidoctor CLI (JavaScript) can be extended so it's pretty straightforward to create a CLI. Once we have a CLI we can create a statically linked binary with `pkg`.

That's what I'm doing in https://github.com/Mogztter/asciidoctor-pdf.js/blob/master/bin/asciidoctor-pdf

**Comment by Mogztter** [comment]
> Thinking about it more, maybe the asciidoctor-reveal.js project should be the one to create that binary? Thoughts?

Great minds think alike :wink:

**Comment by obilodeau** [comment]
> That's why I've suggested to produce a binary asciidoctor-revealjs: asciidoctor/asciidoctor-reveal.js#259

Oh my, how could I miss that...

Thanks! asciidoctor-reveal.js parenthesis closed.
