### ISSUE TITLE
Docker Images use only latest tag

### ISSUE THREAD

**Issue by chess-levin** [asciidoctor/asciidoctor.js#771]
Sorry, wrong project. Ignore this.

Hi guys,
I fell in love with Asciidoctor in just one week. Now I try to promote your docker image to my colleges and we were wondering why don't you provide a version tag for each new image you are releasing on dockerhub? https://hub.docker.com/r/asciidoctor/docker-asciidoctor/tags

It is best practice to tag each new version with a unique version tag. It is not reliable to use only latest. There is so much caching going on in a docker cluster, that you never know which version of an image is actually running.
It would be great if you could tag your images. 
Thank you for great tool :-)

**Comment by oncletom** [comment]
@chess-levin do you want to open it again on https://github.com/asciidoctor/docker-asciidoctor or are you happy that someone uses the "Transfer issue" feature to move the issue around?

**Comment by Mogztter** [comment]
Sorry I don't have the right to move this issue to https://github.com/asciidoctor/docker-asciidoctor :disappointed:

**Comment by chess-levin** [comment]
> @chess-levin do you want to open it again on https://github.com/asciidoctor/docker-asciidoctor or are you happy that someone uses the "Transfer issue" feature to move the issue around?

I already created a new issue. This one could be close.

**Comment by mojavelinux** [comment]
It's already and open issue anyway and a work in progress.
