### ISSUE TITLE
How to use asciidoctor-extensions-lab extensions in asciidoctorjs

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#84]
I'm thinking to write extension in ruby and transpiling it to js. I'm seeing there is "asciidoctor-extensions-lab" extensions written in ruby. How can i use these extensions in asciidoctor.js ?

**Comment by Mogztter** [comment]
Writing extensions in Ruby and transpile them to JavaScript is not encourage anymore.
In the next release (1.5.6), it's recommended to write extension directly in JavaScript using the public API.

**Comment by mojavelinux** [comment]
I agree where possible, the JavaScript API should be preferred. However, I do still see benefits for taking the transpile approach, esp if the extension is being maintained in Ruby.

**Comment by rahmanusta** [comment]
@Mogztter How can I compile ruby files in extensions-lab folder to JavaScript? There was an option to add extension name to the builder, but it looks like changed.

**Comment by Mogztter** [comment]
Hi @rahmanusta,
Indeed I've removed the `extensions-lab` submodule.
You should be able to compile a Ruby extension with the Opal Node Compiler or the Bestikk Opal Compiler:

 * https://github.com/mogztter/opal-node-compiler
 * https://github.com/bestikk/bestikk-opal-compiler/blob/master/index.js

Are you using a Node build or a Ruby build ?

**Comment by rahmanusta** [comment]
I try to switch to new Node build system from the latest code base. I can compile the extensions with opal-node-compiler, thanks.

**Comment by Mogztter** [comment]
@rahmanusta I've added a section to describe how to compile/use a Ruby extension in Asciidoctor.js: https://github.com/asciidoctor/asciidoctor.js/pull/377/files 

Let me know if you have any questions

**Comment by rahmanusta** [comment]
@Mogztter Thank you for the update on the manual. It looks great, I will try it.
