### ISSUE TITLE
Map Table and subclasses 

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor.js#848]
Although the current API is very good :clap: I'd like to see the [Table class](https://www.rubydoc.info/gems/asciidoctor/2.0.9/Asciidoctor/Table) mapped and also its subclasses: the Cell, Column and Rows classes and perhaps while we're there ParserContext.

My use case for this is described in https://github.com/asciidoctor/asciidoctor/issues/1338#issuecomment-592927295

**Comment by henriette-einstein** [comment]
I have implemented the API and some tests in a fork. The branch "tablesupport" includes the changes. Look at

* https://github.com/henriette-einstein/asciidoctor.js/tree/tablesupport

The implementation is in the file

* https://github.com/henriette-einstein/asciidoctor.js/blob/tablesupport/packages/core/src/asciidoctor-core-api.js

The tests are in

* https://github.com/henriette-einstein/asciidoctor.js/blob/tablesupport/packages/core/spec/share/asciidoctor-spec.js

If you are interested, I can create a pull request.

**Comment by Mogztter** [comment]
@henriette-einstein Thanks, that's awesome!

> If you are interested, I can create a pull request.

Of course! I will gladly review it.

**Comment by henriette-einstein** [comment]
Done. 

Hope it helps this great project

**Comment by Mogztter** [comment]
It sure does, thanks for taking the time to contribute.
I left a few comments on the pull request.

**Comment by Mogztter** [comment]
Fixed in https://github.com/asciidoctor/asciidoctor.js/commit/02222791b07df8baafbf7584df9030b126691342
