### ISSUE TITLE
How can i integrate backends or How can i create a new backend for Asciidoctorjs

### ISSUE THREAD

**Issue by rahmanusta** [asciidoctor/asciidoctor.js#85]
How can i integrate backends or How can i create a new backend for Asciidoctorjs?

**Comment by Mogztter** [comment]
> I'm adding the documentation label to this issue since, at the very least, this needs to be documented.

@mojavelinux Speaking of documentation, I'm wondering if I should use the GitHub wiki, stick with the "user manual" page (where all topics are mixed) or use http://asciidoctor.org/docs/ ?

**Comment by mojavelinux** [comment]
Awesome work!
