### ISSUE TITLE
Provide a CLI interface

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#87]
It would be amazing if Asciidoctor.js could provide the same CLI interface (or at the very least, a minimal CLI interface) just like Asciidoctor. That way, people could install Asciidoctor.js (perhaps using npm) and get the asciidoctor command (or perhaps the asciidoctorjs command, to be consistent with AsciidoctorJ and not cause conflicts).

**Comment by Mogztter** [comment]
See https://github.com/asciidoctor/asciidoctor-cli.js

**Comment by mojavelinux** [comment]
Just tried it and it works great. Nice work!

**Comment by mojavelinux** [comment]
Now that we've published the "asciidoctor-cli" package, it makes me wonder whether we should rename (or alias) the core package as "asciidoctor" instead of (or in addition to) "asciidoctor.js".

```
$ npm install asciidoctor
$ npm install asciidoctor-cli
```

Is it possible to add a package alias? If not, I'm okay with renaming the package. I think we agreed that it's understood that this is a JavaScript package given that we are using npm.
