### ISSUE TITLE
Run jdk8_ea and jdk9_ea tasks every night on Travis CI

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#88]
Now that we have smoke test again Java Early Access Release (see #78), we need to run the task `jdk8_ea` and `jdk9_ea` every night on master branch.

Ideas:

 * [Tron CI](http://tron-ci.herokuapp.com/) 
 * Set [environment variables](http://docs.travis-ci.com/user/ci-environment/#Environment-variables)  on Travis
 * Use [Travis API](https://github.com/travis-ci/travis.rb)

**Comment by Mogztter** [comment]
https://ci.appveyor.com/project/asciidoctor/asciidoctor-js/build/25 :beers: 
I expected JDK 9 to be a little faster but that quite the opposite (or maybe I messed up with `Time.now` ?). Do you think we should report that ?

JDK8
```
Smoke test with jjs... OK in 72377.42 ms
Smoke test with java... OK in 68581.778 ms
```

JDK9
```
Smoke test with jjs... OK in 212526.665 ms
Smoke test with java... OK in 214483.205 ms
```

**Comment by mojavelinux** [comment]
> https://ci.appveyor.com/project/asciidoctor/asciidoctor-js/build/25

Woot!

> I expected JDK 9 to be a little faster but that quite the opposite

Very strange. Perhaps it's an issue with Nashorn on Windows? I'll need to fire up my Windows test box to see if I can confirm the increase. If we can confirm outside of CI, then I think it's worth reporting.

Way to stick with this issue!

**Comment by mojavelinux** [comment]
I can confirm on my windows box that the JDK9 test is running considerably slower.

**Comment by mojavelinux** [comment]
I think you can enable the logic for the scheduled build in AppVeyor again and we can call this working. wdyt?

**Comment by Mogztter** [comment]
> Very strange. Perhaps it's an issue with Nashorn on Windows

Did you test Nashorn JDK 9 on Linux ? Is it faster thant Nashorn JDK 8 Linux ?

> I think you can enable the logic for the scheduled build in AppVeyor again and we can call this working. wdyt?

Yes sure

**Comment by mojavelinux** [comment]
> Did you test Nashorn JDK 9 on Linux ? Is it faster thant Nashorn JDK 8 Linux ?

Yep, I tested JDK 9 EA on Fedora 21. It's slower by the same multiplier as we are observing on Windows. So this doesn't seem to be a platform-specific issue. (I still need to test locally on Windows).

It would be interesting to have a baseline test that just runs a basic JavaScript test so we know what parts are overhead unrelated to Asciidoctor.js.

...also, I don't think the `print()` statement is necessary in the smoke test.

**Comment by Mogztter** [comment]
> Yep, I tested JDK 9 EA on Fedora 21. It's slower by the same multiplier as we are observing on Windows. So this doesn't seem to be a platform-specific issue. (I still need to test locally on Windows).

Ok

> It would be interesting to have a baseline test that just runs a basic JavaScript test so we know what parts are overhead unrelated to Asciidoctor.js.

Yes that's a good idea.

> ...also, I don't think the print() statement is necessary in the smoke test.

I need the `print()` statement to assert the output:

 * AsciiDoc source is converted : https://github.com/asciidoctor/asciidoctor.js/blob/master/Rakefile#L137
 * include directive is processed and rendered : https://github.com/asciidoctor/asciidoctor.js/blob/master/Rakefile#L141

**Comment by Mogztter** [comment]
I think we are good now.
I sent an email to the Nashorn dev mailing list to provide as much information as I can to help them investigate.

Time to close this issue ?

**Comment by mojavelinux** [comment]
> I need the print() statement to assert the output:

Oh, nevermind. I see.

**Comment by mojavelinux** [comment]
> Time to close this issue ?

Close & party! :beers:

**Comment by Mogztter** [comment]
:tada:
