### ISSUE TITLE
Create a JavaScript API to make extensions easier to write and register

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#92]
@mojavelinux 

> Just like we have the Groovy DSL for AsciidoctorJ to make extensions easier to write and register, I think we can offer a JavaScript API that is optimized for the author. It's completely reasonable to hide some of the Opal interfaces behind a simpler, clearer JavaScript API.
> 
> We should aim to make it as similar to the original Asciidoctor API as possible, where possible, so it's easy to reason about the relationship.

Related to #84 #76

**Comment by Mogztter** [comment]
This is harder than I though :persevere:

**Comment by Mogztter** [comment]
I define methods explicitly and provide a convenient method to create `Opal.hash2`:
```javascript
Opal.Asciidoctor.Extensions.register = function (block, name) {
  Opal.block_send(Opal.Asciidoctor.Extensions, 'register', block, name);
};

Opal.Asciidoctor.Extensions.Registry._proto.inline_macro = function (block, name) {
  return Opal.block_send(this, 'inline_macro', block, name);
};

Opal.Asciidoctor.Extensions.InlineMacroProcessor._proto.process = function (block) {
  return Opal.block_send(this, 'process', block);
};

Opal.to_hash = function (data) {
  var keys = [];
  for (var key in data) {
    if (data.hasOwnProperty(key)) {
      keys.push(key);
    }
  }
  return Opal.hash2(keys, data);
};
```
**Before:**
```javascript
Opal.block_send(Opal.Asciidoctor.Extensions, 'register', function () {
  Opal.block_send(this, 'inline_macro', function () {
    var inlineMacro = this;
    inlineMacro.$parse_content_as("text");
    Opal.block_send(inlineMacro, 'process', function (parent, target, attrs) {
      var link = "chrome:" + target;
      var text = attrs.map['text'];
      if (!text) {
        text = link;
      }
      return (inlineMacro.$create_anchor(parent, text, Opal.hash2(["type", "target"], {"type": "link", "target": link}))).$render();
    });
  }, "chrome");
}, "uri_schemes");
```

**After:**
```javascript
Opal.Asciidoctor.Extensions.register(function () {
  this.inline_macro(function () {
    var inlineMacro = this;
    inlineMacro.$parse_content_as("text");
	this.process(function (parent, target, attrs) {
      var link = "chrome:" + target;
      var text = attrs.map['text'];
      if (!text) {
        text = link;
      }
      return (inlineMacro.$create_anchor(parent, text, Opal.to_hash({"type": "link", "target": link}))).$render();
    });
  }, "chrome");
}, "uri_schemes");
```

Thoughts ?

**Comment by mojavelinux** [comment]
Wow, that's quite an improvement.

I like the `to_hash` function, but I'm nervous about namespacing it to Opal since we don't control that namespace. Perhaps you can make a top-level function or put it in the Asciidoctor namespace.

Another idea is to decorate the JavaScript object with a `to_h` or `$to_h` method so it could be written as:

```javascript
{type: "link", target: link}.$to_h()
```

Ideally, Opal should just offer a cleaner way to make a hash. Would you be willing to file an issue in Opal to track this request? https://github.com/opal/opal/

**Comment by Mogztter** [comment]
Done https://github.com/opal/opal/issues/758

**Comment by mojavelinux** [comment]
...and we learned something! Now it's time to update all the code that uses Asciidoctor.js to use Opal#hash now that we know about it :)

**Comment by Mogztter** [comment]
I think we did a good job on the public API.
I'm going to close this issue but feel free to open specific issue to improve the public API for  a writing extension.

**Comment by mojavelinux** [comment]
Agreed. We've reached the point where we should address improvements on a case-by-case basis.

Great job!
