### ISSUE TITLE
Registered Handlebars helper functions are unintentionally global for all templates

### ISSUE THREAD

**Issue by henriette-einstein** [asciidoctor/asciidoctor.js#924]
The current implementation of the `helper.js` module creates the handlebars instance with

```
const handlebars = require('handlebars')
```
This method returns a singleton instance of Handlebars. If you register a Handlebars helper function using this instance, the helper function will be global to all Handlebars templates.

If you have two (or more) different transformers in two (or more) directories, which all have a `helper.js` with the code above, the helper functions are mixed. I had a property "content" which is used in my template. However I got errors, because another `helper.js`had registered a function `content` before me. That function got called, when I used `{{content}}` in my templates.

To fix that, a non-singleton Handlebars instance is required. That is possible with the Handlebars.Create function. See
https://handlebarsjs.com/api-reference/runtime.html#handlebars-create

The template engine should instantiate a separate Handlebars instance for every template directory. Probably this instance should be passed to the `helper.js` module, which the does not create it's own instance, but reuse the one provided by the engine

**Comment by Mogztter** [comment]
> Probably this instance should be passed to the helper.js module, which the does not create it's own instance, but reuse the one provided by the engine

I think we will need to define an "API" (ie. a contract between the helpers.js file and Asciidoctor.js). We could call a `configure` function (if it exists) with a "context object" as argument:

```js
const handlebars = Handlebars.create()
const helpers = require('helpers.js')
if (typeof helpers.configure === 'function') {
  helpers.configure({engine: handlebars})
}
```

I'm using a "context object" to make the API more flexible. We could add additional data if needed.

**Comment by henriette-einstein** [comment]
I have prepared the helper.js in handlebars-json to be configured via module.expotts.configure. To try it out, uncomment line 303 ( configure({}) ) and then use the code scetched before to configure the helper

**Comment by Mogztter** [comment]
Some references for other template engines:

**Nunjucks**
Use an `Environment` class: https://mozilla.github.io/nunjucks/api.html#environment
I think this class is used to provide isolation so we should probably pass it to the `configure` function.
To make sure that it's working we should add a test where we define two filters with the same name on two "Environments": https://mozilla.github.io/nunjucks/api.html#addfilter

**Pug**
Pug seems to be "stateless" so we don't need to change anything.
However additional options can be passed to the `compileFile` function, see https://github.com/asciidoctor/asciidoctor.js/issues/925

**EJS**
Same as Pug.

**Comment by Mogztter** [comment]
It's actually possible to mixed template engines in a single directory. So the `configure` function should take an object:

```js
helpers.configure({ 
  handlebars: {}, 
  nunjucks: {}
})
```

I also decided to use the term `environment` instead of `engine` because both Nunjucks and Handlebars are using this terminology:

> The Environment class is the central object which handles templates. It knows how to load your templates, and internally templates depend on it for inheritance and including templates. The simple API above dispatches everything to an Environment instance that it keeps for you.
-- Nunjucks documentation

> Creates an isolated Handlebars environment.
Each environment has its own helpers and partials. This is only necessary for use cases that demand distinct helpers or partials. Most use cases can use the root Handlebars environment directly.
-- Handlebars documentation
