### ISSUE TITLE
Remove unnecessary call to configure-method

### ISSUE THREAD

**Issue by henriette-einstein** [asciidoctor/asciidoctor.js#933]
In /packages/core/spec/fixtures/templates/handlebars-json/helpers.js

line 309: configure({}) 

can be removed. The configure method is called by the template mechanism.

I don't know whether I should create a pull request or whether it is easier just to remove it

**Comment by Mogztter** [comment]
> In /packages/core/spec/fixtures/templates/handlebars-json/helpers.js
line 309: configure({})
can be removed. The configure method is called by the template mechanism.

Nice catch :+1: 

> I don't know whether I should create a pull request or whether it is easier just to remove it

It's a good practice to create an issue so I don't mind :wink: 
You might not have time to fix it right away so even if it's a tiny fix it can serve as a reminder.
