### ISSUE TITLE
Support pure JSON objects in place of Opal.hash

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.js#94]
Ideally, the Asciidoctor APIs should be able to accept a regular JSON data structure where a Hash is required instead of Opal.hash2. The latter is awkward and redundant (keys have to be listed twice). It would feel much more comfortable for developers if they could continue to use the familiar JSON data structure.

**Comment by Mogztter** [comment]
We now use `Opal.hash` which is quite close to regular JSON data structure. But I agree we should provide a simpler and more JavaScript friendly API.

**Comment by mojavelinux** [comment]
I'll update the title of the image to reflect that we're using Opal.hash now.

**Comment by mojavelinux** [comment]
:+1:
