### ISSUE TITLE
doc.$header().$attr() does not return only header attributes

### ISSUE THREAD

**Issue by nerk** [asciidoctor/asciidoctor.js#96]
(This is most likely more of an issue with ruby asciidoctor. However, I am reporting it here because I only tried asciidoctor.js).

If each of the following snippets (containing an additional source code block not listed here) is rendered as a full document with header and  footer, the source code in the third snipped is not highlighted with 'prettify'. This is expected behavior because of the blank line after the title. The attribute is not considered a header attribute in this case.

```
:source-highlighter: prettify

= Title
```

```
= Title
:source-highlighter: prettify
```

```
= Title

:source-highlighter: prettify
```

However, parsing the three document snippets and reading the attribute by invoking

```
var h = doc.$header().$attr('source-highlighter');
```
or
```
var h = doc.$attr('source-highlighter');
```

always returns `prettify`. I think for the third case, it should not. Am I right or am I missing something?

**Comment by mojavelinux** [comment]
This is an area of the API that is not well defined (and thus not behaving as expected). The results you are observing trace back to an implementation detail that we need to fix in Asciidoctor. See https://github.com/asciidoctor/asciidoctor/issues/692 and https://github.com/asciidoctor/asciidoctor/issues/1255.

To provide some background, AsciiDoc Python never had an AST, so some parts of the parser did not map cleanly when we introduce one in Asciidoctor. One of those parts is attributes. Attributes are not stored discretely in the tree as they should be. Instead, they are "played" as the tree is walked. This is something that needs to change in order to provide proper access to them from the AST.

**Comment by mojavelinux** [comment]
In the change that is being proposed for 1.5.3 (see asciidoctor/asciidoctor#1511), restore_attributes will be called immediately after parse. That means that after you load the document, the attributes will be:

a) the attributes as defined at the end of the header (or those overridden by the API)
b) the attributes will be modifiable

**Comment by mojavelinux** [comment]
So your assumption will become true once 1.5.3 is released.

**Comment by rahmanusta** [comment]
+1 @mojavelinux

**Comment by Mogztter** [comment]
@nerk Could you please test with the latest release `1.5.3.preview.2` ?

**Comment by nerk** [comment]
With `1.5.3.preview.2`, it seems as if all attributes are now empty/unset after `Opal.Asciidoctor.$load()`. 
I defined an attribute `test` in the document 

```
= Changelog of Brackets AsciiDoc Preview
:test: xxxx
```

and tried to access it with

```
doc.$header().$attr('test');
doc.$attr('test');
```

Both calls return null.

**Comment by mojavelinux** [comment]
You should never really access `doc.$header()` as that's really an internal block. I'm checking the other case.

**Comment by mojavelinux** [comment]
From the Ruby side, the following works:

```
str = <<-EOS
= Changelog of Brackets AsciiDoc Preview
:test: xxxx
EOS

require 'asciidoctor'

doc = Asciidoctor.load str, safe: :safe
puts doc.attr 'test'
```

**Comment by nerk** [comment]
I used the latest `asciidoctor-all-min.js` without success. I might try a small node.js test case tomorrow. Oops, I meant later today... ;-)

**Comment by mojavelinux** [comment]
I just tried with Asciidoctor.js and it works...however, I am noticing a major problem.

It seems that the attribute splitting code is not returning the right values when attributes are passed as a string to the API. Opal seems to have "fixed" the regexp replacement pattern and now it is breaking Asciidoctor.js.

**Comment by mojavelinux** [comment]
...and that may have something to do with why you are getting attributes you don't expect...maybe.

**Comment by mojavelinux** [comment]
@Mogztter the following line needs to be replaced in lib/asciidoctor.rb

```ruby
capture_1 = ::RUBY_ENGINE_OPAL ? '$1' : '\1'
```

to

```ruby
capture_1 = '\1'
```

That will enable the attributes string to be properly chopped up into attributes. I'll fix it in core, but we'll need a patch for the 1.5.3 release.

I don't see any other instances of this in the code (yet).

**Comment by mojavelinux** [comment]
I addressed the issue with attribute parsing in core: https://github.com/asciidoctor/asciidoctor/commit/df49f227bab51f2b1197862e7ac95f2a0b844f2b

**Comment by mojavelinux** [comment]
Btw, here's the code I'm using to verify that I can access the attributes defined in the header:

```js
if (typeof console === 'undefined') {
  console = {
    log: function(str) {
      print(str);
    },
    warn: function(str) {
      print(str);
    }
  };
}

asciidoctor = false;
if (typeof load === 'function') {
  load('./bower_components/opal/opal/0.8.0/opal.js')
  load('./build/asciidoctor-core.js');
}
else {
  Opal = require('opal-npm-wrapper').Opal;
  asciidoctor = require('./build/npm/asciidoctor-core.js')(Opal, (typeof phantom !== undefined ? false : null)).Asciidoctor();
}
Opal.require('asciidoctor');

var data = "= Document Title\n:test: xxxx\n\ncontent"

var options = Opal.hash({safe: 'safe', header_footer: true, attributes: 'linkcss copycss!'});
doc = (asciidoctor ? asciidoctor : Opal.Asciidoctor).$load(data, options);
console.log(doc.$attr('test'))
```

This works using `js`, `node` or `phantomjs`.

@Mogztter it might be useful to include a test script like this in the repository. We might want to make it more generic (not just print attributes), but the initialization is what is important.

**Comment by mojavelinux** [comment]
For testing outside the project, I used:

```js
if (typeof load === 'function') {
  load('./bower_components/asciidoctor.js/dist/asciidoctor-all.min.js');
}
```

and

```js
else {
  Opal = require('opal-npm-wrapper').Opal;
  asciidoctor = require('./node_modules/asciidoctor.js/dist/npm/asciidoctor-core.min.js')(Opal, (typeof phantom !== undefined ? false : null)).Asciidoctor();
}
```

I'm confused, however, how npm finds the Opal code. I didn't think we bundled it in asciidoctor-core.min.js and I don't see any Opal code loaded by opal-npm-wrapper. But it works :)

**Comment by Mogztter** [comment]
@mojavelinux 
> This is an area of the API that is not well defined (and thus not behaving as expected). The results you are observing trace back to an implementation detail that we need to fix in Asciidoctor

Indeed, I'm a little bit confused about how this should work:

```javascript
var options = Opal.hash({'attributes': 'source-highlighter=highlightjs'});
var doc = Asciidoctor.$load('= Document Title\n:source-highlighter: prettify\n\ncontent', options);
// header attributes
console.log(doc.header_attributes.smap['source-highlighter']);
console.log(doc.$header().$attr('source-highlighter'));
console.log(doc.$header().attributes.smap['source-highlighter']);
console.log(' ');
// document attributes
console.log(doc.$attr('source-highlighter'));
console.log(doc.attributes.smap['source-highlighter']);
```

I'm using Asciidoctor.js `1.5.3-preview.4` and the code above prints:

```
highlightjs
highlightjs
highlightjs

highlightjs
highlightjs
```

Document attributes are overridden, how do I get the document attribute value (`prettify`) ?
With `var options = Opal.hash({'attributes': 'source-highlighter=highlightjs@'});`  (note the `@`), I get:

```
prettify
prettify
prettify

prettify
prettify
```

**Comment by nerk** [comment]
@Mogztter The output of your example is what I would expect. 
The first case prevents modification of the attribute from within the document. The second case with the '@' does allow it. This is the defined behavior.

**Comment by nerk** [comment]
Just did a quick test with the brackets preview and it still does not seem to work. I need to create a test case to reproduce the behavior.

**Comment by nerk** [comment]
I put asciidoctor-all.min.js from preview.4 into the local directory and ran:

```
require('./asciidoctor-all.min.js');

var options = Opal.hash({'attributes': 'source-highlighter=highlightjs'});
var doc = Opal.Asciidoctor.$load('= Document Title\n:source-highlighter: prettify\n\ncontent', options);
// header attributes
console.log(doc.header_attributes.smap['source-highlighter']);
console.log(doc.$header().$attr('source-highlighter'));
console.log(doc.$header().attributes.smap['source-highlighter']);
console.log(' ');
// document attributes
console.log(doc.$attr('source-highlighter'));
console.log(doc.attributes.smap['source-highlighter']);
```

Output:
```
highlightjs
highlightjs
undefined

highlightjs
highlightjs
```

Note the `undefined`

With `var options = Opal.hash({'attributes': 'source-highlighter=highlightjs@'});`, the output is
```
prettify
prettify
undefined

prettify
prettify
```

Does the `undefined` matter?

**Comment by nerk** [comment]
With Asciidoctor.js 1.5.2, the following worked:

```
var options = Opal.hash2(['attributes'], {'attributes': 'source-highlighter=highlight.js@'});
var doc = Opal.Asciidoctor.$load('= Document Title\n:source-highlighter: prettify\n\ncontent', options);

console.log(doc.attributes.map['source-highlighter']);
```

Note `hash2` and `doc.attributes.map`

This does not work with 1.5.3.preview.4 anymore and will output `undefined`. 

Instead, we need to use `hash`and `doc.attributes.smap`.
```
var options = Opal.hash({'attributes': 'source-highlighter=highlight.js@'});
var doc = Opal.Asciidoctor.$load('= Document Title\n:source-highlighter: prettify\n\ncontent', options);

console.log(doc.attributes.smap['source-highlighter']);
```

**Comment by nerk** [comment]
As @mojavelinus mentioned, `doc.$header()` should not be used to access attributes, that's fine with me. However, I still do not know if it is possible to access attributes defined anywhere in a document.

```
 var text = '= Document Title\n:source-highlighter: prettify\n\n\ncontent\n\n:stem:\n== test\n\n:stem:\n';

var options = Opal.hash({'attributes': 'source-highlighter=highlight.js@'});
var doc = Opal.Asciidoctor.$load(text, options);

console.log(doc.$attr('source-highlighter'));
console.log(doc.$attr('stem'));
```
Output:

```
prettify
{ '$$id': 4, apply: [Function], call: [Function] }
```

**Comment by Mogztter** [comment]
@nerk 
> Note the undefined

Yes you're correct, I made a mistake.

> Does the undefined matter?

Yes and no, this mean that `attributes` on the header are empty.

> Note `hash2` and `doc.attributes.map`. This does not work with `1.5.3.preview.4` anymore and will output `undefined`.

`smap` is an internal property and Opal can decide to modify it or remove it in future version :disappointed:
Instead you should use Hash's public methods instead: https://github.com/opal/opal/blob/master/opal/corelib/hash.rb (`$has_key?`, `$fetch`...)

`hash2` is too verbose and we decided to use `hash` instead but `hash2` should still work.

Maybe we should write a migration guide :smile: :book: 

> However, I still do not know if it is possible to access attributes defined anywhere in a document.

I don't know either.

> As @mojavelinux mentioned, doc.$header() should not be used to access attributes, that's fine with me. 

Yes but the AST should contains all the information.

```asciidoc
= Document Title
:source-highlighter: prettify

content
:source-highlighter: coderay

== test

:source-highlighter: highlightjs
```

In the above example, I want to know that:

 * document header defined `:source-highlighter: prettify`
 * preamble block defined `:source-highlighter: coderay`
 * section block defined `:source-highlighter: highlightjs`

**Comment by nerk** [comment]
> `hash2` is too verbose and we decided to use hash instead but hash2 should still work.

Apparently it does not. Maybe I am doing something wrong...

**Comment by nerk** [comment]
Ok, I think I now understand after reading https://github.com/asciidoctor/docgist/issues/21

`hash2` still works, but doc.attributes.map should not be used. I am going to change my code to using `hash` and the `$has_key?` and `$fetch`

**Comment by mojavelinux** [comment]
> I still do not know if it is possible to access attributes defined anywhere in a document.

There is not currently an official API for doing this. You can access the attributes in the header (after loading the document) and you can access the attributes when converting a node. But we don't have a way yet to access document attributes defined beyond the header. We need to design and implement it.

**Comment by mojavelinux** [comment]
> we don't have a way yet to access document attributes defined beyond the header

à la carte

**Comment by Mogztter** [comment]
@nerk @mojavelinux  can we close this issue and open a new feature request on Asciidoctor core to access document attributes defined in the "body" ?

**Comment by mojavelinux** [comment]
Yes. Link back to this issue and the other one related to attribute access in this repository. That way, we don't lose the context but we can start with a clear goal in mind.

**Comment by nerk** [comment]
Closing this, follow-up #140

**Comment by nerk** [comment]
Follow-up is https://github.com/asciidoctor/asciidoctor/issues/1575
