### ISSUE TITLE
Promote chart-block-macro extension

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#97]

**Comment by Mogztter** [comment]
The `chart-block-macro` extension relies on the `csv` gem but I think we need to remove this dependency. 

```
rake aborted!
Sprockets::FileNotFound: couldn't find file 'csv'
  (in /workspace/asciidoctor.js/extensions-lab/lib/chart-block-macro/extension.rb)
```

Asciidoctore core is using a  [simple method](https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/substitutors.rb#L1281) to do that, can we reuse that code or just copy-paste into the extension ?

**Comment by mojavelinux** [comment]
We could definitely reuse that logic that's inside Asciidoctor. I've found it to be more than sufficient for any CSV content I've used and it saves a lot of headache. Feel free to rework the API if necessary so that you can use it to create the data structure you need in the chart extension.

**Comment by Mogztter** [comment]
I've created an issue in the asciidoctor-extension-lab repository: https://github.com/asciidoctor/asciidoctor-extensions-lab/pull/40
