### ISSUE TITLE
Promote gist-block-macro extension

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor.js#99]

**Comment by mojavelinux** [comment]
I agree, though I'd also like to have this extension reviewed. It was a super quick hack. Are there things about it we need to add before we make it "live"? I'm really looking for people who like to use gists in blog posts since that's when I imagine it will be used the most.

**Comment by Mogztter** [comment]
@mojavelinux Actually we can't use the embed script in the chrome extension because the script use `document.write`

```
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
gist.github.com/mojavelinux/5546622.js?_=1427023194250:2 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
```

Instead we could use the `json` format. For instance `https://gist.github.com/mojavelinux/5546622.js` gives us the script and `https://gist.github.com/mojavelinux/5546622.json` gives us the json representation of the Gist.
The extension can then use the `div` attribute and the `stylesheet` attribute ? Wdyt ?

Quick implementation in JavaScript:
```javascript
$.getJSON("https://gist.github.com/mojavelinux/5546622.json", function(data) {
  var gistLink = document.createElement('link');
  gistLink.rel = 'stylesheet';
  gistLink.id = 'gist-style';
  gistLink.href = data.stylesheet;
  document.head.appendChild(gistLink);
  $(".gist-content-script").append(data.div);
});
```

**Comment by mojavelinux** [comment]
Great thinking! I wasn't aware the gist was served as JSON. That makes things a lot simpler (in theory). I'm perfectly happy with the idea of reworking the extension to use this approach instead. As long as the snippet gets into the browser, I don't care how it happens. Perhaps we should have a parallel issue in the extension lab to change the implementation.

**Comment by Mogztter** [comment]
> Perhaps we should have a parallel issue in the extension lab to change the implementation.

Yes, if you are OK with this change, I will create an issue in the extension lab repository.

**Comment by mojavelinux** [comment]
:+1:

**Comment by Mogztter** [comment]
I think this issue is not relevant anymore since Asciidoctor.js does not contains (or promote) extensions.
